### PR TITLE
Pip: Remove Command Keyword

### LINKED ISSUE #818: Pip Suggestion: Remove command keyword
### Description

This fathead is pretty cool, but it's not triggering. I think this is because people are searching for commands such as:

```
pip freeze
pip search
```

and not:

```
pip freeze command
pip search command
```
In this low-hanging fruit issue, we need to removed the command word from the trigger sequence.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/{ID}

### PR DESCRIPTION
**Pull request by BillyBarbaro**
## Description of new Instant Answer, or changes

Removes the command keyword from the titles in output.txt and hopefully fixes the issues that caused PR #829 not to work.

## Related Issues and Discussions
Fixes #818 
Updates PR #829 

## People to notify
@pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/pip

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by BillyBarbaro** [comment]
Looks like this go at it is actually working!  A couple more things I think:

1)  The original output.txt included an entry for just "pip".  While this is useful, "pip pip" won't trigger it.  The only way I can get it to trigger is using "python pip pip".  Any thoughts on what to do about this?

2)  I removed "pip" from trigger_words.txt since it's the ID of the fathead and should be used as a trigger word automatically.

3)  @karanchahal, since we've changed the searches on this fathead, could you update the IA page to reflect that?  The examples present there will still work, you just need to remove the word command from the end of them.

**Comment by karanchahal** [comment]
@BillyBarbaro I am not sure why you removed the keyword 'command' from the output file. The keyword was there for a reason please refer to #465 . Your current PR fails to recognise pip uninstall,pip show,pip freeze,pip install and pip.
The command keyword solved that. 
If you can make all the above work without the command keyword, credit to you :+1:

**Comment by pjhampton** [comment]
@karanchahal I looked at the data and this IA wasn't triggering at all so I created: https://github.com/duckduckgo/zeroclickinfo-fathead/issues/818

Can you explain what you mean by the following?

```
Your current PR fails to recognise pip uninstall,pip show,pip freeze,pip install and pip.
The command keyword solved that.
```

Removing this keyword will make it work.

@moollaza wrote in that issue:

> Once possible fix is to create redirects in that Fathead for more specific queries:
> 
> pip install usage -> pip install
> pip install command -> pip install
> That way queries like "pip install command" should be able to trigger this Fathead.
> 

You didn't do this, and that is why this issue was created, and patched by @BillyBarbaro

**Comment by moollaza** [comment]
> I removed "pip" from trigger_words.txt since it's the ID of the fathead and should be used as a trigger word automatically.

@BillyBarbaro there are no "automatic" trigger words for Fatheads. We still need it in the `output.txt` 👍

**Comment by BillyBarbaro** [comment]
@moollaza I removed pip from trigger_words.txt.  I can't find it in the documentation, but I was under the impression that a query containing the ID of the fathead triggered it.

Should I revert that commit and add pip back into trigger_words.txt?

**Comment by BillyBarbaro** [comment]
@pjhampton I think I see what @karanchahal was pointing out.  Since the [PyPi](https://duck.co/ia/view/py_pi) IA triggers on queries of the form "pip <package_name>", the two will collide on queries like "[pip freeze](https://duckduckgo.com/?q=pip+freeze&ia=about)" since there's a python package named Freeze.

From my personal experience, I feel that the pip IA would be more useful to users in these cases.  I don't know if there's any way to check this in the search data.  And if this is the case, how would we make sure the right IA is displayed if both are triggered? 

Also, to address my above question:

> The original output.txt included an entry for just "pip". While this is useful, "pip pip" won't trigger it. The only way I can get it to trigger is using "python pip pip". Any thoughts on what to do about this?

I was thinking of switching the entry to something like "pip usage".

**Comment by pjhampton** [comment]
Hey @BillyBarbaro!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
