### PR TITLE
MDN CSS: Add category pages and more redirects

### PR DESCRIPTION
**Pull request by moollaza**
- Adds a YAML file defining categories for various CSS Articles
- Uses this file to lookup the categories an article falls under and adds them accordingly
- Also creates redirects for the article title based on the categories

----

IA Page: https://duck.co/ia/view/mdn_css

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by hchienjo** [comment]
@moollaza Looks good. Do we merge it right now but work on integrating this into the script after ironing out [this](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/343)?

**Comment by moollaza** [comment]
@hchienjo my PR isn't actually done yet so we still have some time. If I manage to finish it today then I think we should be OK to merge and then adjust your PR. It shouldn't cause too much trouble for you

**Comment by moollaza** [comment]
@hchienjo I ended up making some breaking changes here. I think we should move ahead with my PR and refactor yours once this is merged.

I've tried to better organize and name the functions. I've also simplified some of the `sub`s. This should help make it easier to redirects once category pages are working.

It should also help us check for duplicates in the `_build_article` and `_build_redirect` functions

**Comment by hchienjo** [comment]
@moollaza No problem. I will take a look.

**Comment by hchienjo** [comment]
@moollaza Do I start working on this on a branch based off `zaahir/mdn-css-categories`?

**Comment by hchienjo** [comment]
@moollaza Should I start my own branch based off `zaahir/mdn-css-categories` in order to help out?

**Comment by moollaza** [comment]
> @moollaza Should I start my own branch based off zaahir/mdn-css-categories in order to help out?

@hchienjo sorry for the delay -- would you like to take a look at this to see where I've headed with things?

**Comment by hchienjo** [comment]
@moollaza Yes of course, if it is not too much of a problem.

**Comment by moollaza** [comment]
@hchienjo this is now live on Beta:
- https://beta.duckduckgo.com/180/c/Css_pseudo_elements?ia=list
- https://beta.duckduckgo.com/?q=%3A%3Abefore+pseudo+element&ia=about
 -https://beta.duckduckgo.com/?q=background-size+property&ia=about

**Comment by hchienjo** [comment]
Awesome!

**Pull request merged**
