### PR TITLE
SwiftDocs

### PR DESCRIPTION
**Pull request by jagtalon**
Introduction:
-------------
This is used to crawl swiftdoc.org to create a Fathead output
that's specified in http://docs.duckduckhack.com/resources/fathead-overview.html

See: https://forum.duckduckhack.com/t/create-swiftdoc-instant-answer/242

Page Structure:
---------------
Crawling swiftdoc.org is simple. All the links can be found in the root domain (index.html)
so all we have to do is to collect all those links and send them off to processing.

Pipeline:
---------
Fetch -> Scrape / Process -> Output

Screencaps:
--------

screen shot 2016-07-27 at 3 04 21 pm
screen shot 2016-07-27 at 3 04 32 pm

What's missing?
----

Disambiguation is currently missing but I think we can make a PR for that instead in the future. What we have here should be an MVP.

How do I test this?
-----
You need `node` and `npm` installed on your machine. After that, run:

`cd lib/fathead/swift && npm install && ./parse.sh`

IA Page: https://duck.co/ia/view/swiftdocs

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jagtalon** [comment]
@jdorweiler @MariagraziaAlastra  @zachthompson it should be ready for review!

**Comment by jdorweiler** [comment]
Can you add an IA page to your first post?

**Comment by jagtalon** [comment]
@jdorweiler done!

**Comment by jdorweiler** [comment]
Can you rename to directory from swift to swiftdocs?

**Comment by jdorweiler** [comment]
It's on beta to test. 
https://beta.duckduckgo.com/?q=swift+successor&t=ha&ia=about

**Comment by jagtalon** [comment]
@jdorweiler done!

**Comment by jdorweiler** [comment]
Do you want to try parsing out the class and module that the methods belong to and add them as categories?

For example this entry:
'String.UnicodeScalarView.Index.predecessor' would belong to the String and UnicodeScalarView categories. 

Categories go in the 5th field. http://docs.duckduckhack.com/resources/fathead-overview.html

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=swift foreach)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/swiftdocs_mobile.png?el3jZ7m1dj)

**Comment by jagtalon** [comment]
@jdorweiler I think I'd like to leave some things TODO for people to help out with (Low-hanging fruit stuff). Unless it's a showstopper for you, I'll just make an issue for that!

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=swift foreach)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/swiftdocs_mobile.png?GsKucNftfE)

**Comment by jdorweiler** [comment]
Can you add a README that show show to install the dependencies?

**Comment by jagtalon** [comment]
@jdorweiler added a readme!

**Comment by soleo** [comment]
@jagtalon this can be replaced with https://github.com/SwiftDocOrg/swiftdoc-parser if we ever need to get different version of documentation for swift

**Comment by jagtalon** [comment]
@soleo I'm down for that! So I think we should launch this just to see how much of the query space it covers, but I'm definitely down to replace this with either a Spice of swiftdoc-parser. :)

**Comment by jdorweiler** [comment]
@jagtalon :+1:

**Pull request merged**
