### PR TITLE
Ruby: Adding coverage for stdlib docs

### LINKED ISSUE #706: Ruby: Improve Reference Coverage (Stdlib)
# Description

Currently, the [Ruby Docs Fathead](https://duck.co/ia/view/ruby) is only parsing the [Ruby Core documentation](http://ruby-doc.org/core-2.4.0/) and has left out the [Stdlib documentation](http://ruby-doc.org/stdlib-2.4.0/). This means that some developers are missing out on an IA. For example: 

**Core: Ruby Time** 👍 

screen shot 2017-01-23 at 6 19 47 pm

**Stdlib: Ruby Date** 👎 

screen shot 2017-01-23 at 6 19 33 pm

## Task

Update or extend parser to parse the stdlib docs. 

## Future Steps

Update the redirects.

## People to notify
@kotoshenya (Language Leader)

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/ruby

### PR DESCRIPTION
**Pull request by acflint**
## Description of new Instant Answer, or changes
Adding Ruby STDLIB docs parser

## Related Issues and Discussions
Fixes #706

## People to notify
@kotoshenya @pjhampton @moollaza 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/ruby_stdlib

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Nice, @acflint!

**Comment by acflint** [comment]
@pjhampton thanks! I hope it's all okay. Let me know if there are any issues.

**Comment by acflint** [comment]
Thanks @kotoshenya ! I've made those suggested changes.

**Comment by moollaza** [comment]
@acflint please push the generated output.txt. This will automatically install the Fathead on Beta for us to test 👍 

As well, please remove the empty `redirects.txt` file.

Please add `ruby` to the `trigger_words.txt` as well

**Comment by acflint** [comment]
@moollaza Done! Hope that's all good now. Let me know if there's anything else I can fix. Cheers.

**Comment by acflint** [comment]
Thanks @moollaza! I've made those changes.

**Comment by pjhampton** [comment]
Hey @acflint!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
