### PR TITLE
Perl 6 Documentation: Fix the parser so that it generates correct links

### PR DESCRIPTION
**Pull request by titsuki**
## Description of new Instant Answer, or changes

The "More at Perl 6 Documentation" links are broken.

For example, 
the "More at Perl 6 Documentation" link of https://duckduckgo.com/?q=perl6+List.reduce&t=h_&ia=about
links http://doc.perl6.org/type/List#reduce, but the correct link is https://docs.perl6.org/type/List.html#routine_reduce .

Therefore, I've tweaked the `parser.pl` to generate correct links.

## Related Issues and Discussions
https://github.com/duckduckgo/zeroclickinfo-fathead/issues/681

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page**
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Code**
- [x] Uniformly indented, well commented
- [x] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/perl6doc

### CODE REVIEW

**Comment by daxtheduck** [comment]
@titsuki Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@titsuki great work! Please generate the new `output.txt` and push it here. This way the updates will be automatically deployed to beta.duckduckgo.com.

After we confirm it all works correctly on Beta we can then merge the PR 👍

**Comment by titsuki** [comment]
@vigzmv @moollaza
Thanks for reviewing my PR.
I updated output.txt.

**Comment by moollaza** [comment]
@titsuki Thanks! This LGTM :+1:

I noticed that `perl 6 str` no longer works though...can you investigate why this is? Has the data changed? Or are your changes affecting this?

Also would you be interested in fixing the duplicates? Currently there are over 200 duplicates in the `output.txt` that should be addressed! (these aren't created by your code though..)

**Comment by moollaza** [comment]
@titsuki actually, with your changes, there are 243 titles missing that are being references in disambiguation entries. Can you confirm that your changes aren't removing any titles?

You can see the list of titles if you run `duckpan test perl6doc` from inside the repo 👍

**Comment by titsuki** [comment]
@moollaza 
Thanks for reviewing.
I confirmed that something has been wrong since my change.
I'll check later in detail.

command:
```
$ git checkout 1f6b446e456 -- lib/fathead/perl6doc/output.txt # previous version
```
result:
https://gist.github.com/titsuki/bb2277010c7aa2e814c4ae51de509b2d


command:
```
$ git checkout 7d998fed6c777f -- lib/fathead/perl6doc/output.txt # current version
```
result:
https://gist.github.com/titsuki/0185063251ce32e68c9d367a64e3504c

**Comment by titsuki** [comment]
Parsing the latest dump with the previous parser also cause many title missing.
So I think it's not a parser's problem but a dump's problem.

command:
```
$ git checkout 1f6b446e456130 # previous version
$ duckpan test perl6doc
```
result:
https://gist.github.com/titsuki/655741d60dac40a496a6a46c9ac9a2b4

**Comment by moollaza** [comment]
@titsuki okay, it sounds like your changes don't introduce any problems then, but we do still have an issues with duplicates, and we will have broken disambiguations moving forward because the data must have changed.

Would you like to investigate this further? If not I'll create a task for the community.

Thanks again for that awesome work 👍 💯

**Comment by titsuki** [comment]
@moollaza
ok. I'll check difference between the html files by generating them with htmlify.p6:
https://github.com/perl6/doc/blob/master/htmlify.p6

**Pull request merged**
