### PR TITLE
Python: Fix #526 add coverage for more classes

### LINKED ISSUE #526: Python: add coverage for more classes
### Description
Add coverage for more classes.

https://duckduckgo.com/?q=python+subprocess&atb=v23&ia=meanings
should show a summary of the class and an infobox link to this category page

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

### PR DESCRIPTION
**Pull request by Hestben**
## Related Issues and Discussions
Issue #526 
I have created this PR to discuss what we should do, and comment on the code.
@souravbadami I see you have touched the code last. Maybe you would like to take this issue, if you have time. I don't want us to do double work =).
From my initial investigation, I have found that the view that is shown in the search result in #526 example comes from a Disambiguation entry created in redirect.py.
Does anybody have an example where a Disambiguation is the correct thing to show? If we strip out some stuff, we wouldn't want to destroy cases where disambiguations should be used.
I have found more cases where I think we would like to change the view, as @jdorweiler suggested in the #526:
https://duckduckgo.com/?q=python+shlex&t=ffsb&ia=meanings&iai=%2F35%2Fshlex.quote
https://duckduckgo.com/?q=python+pickletools&t=ffsb&ia=meanings&iai=%2F35%2Fpickletools.genops
https://duckduckgo.com/?q=python+msvcrt&t=ffsb&ia=meanings

The two solutions I can think of after my brief investigation are

1. Manually specify which classes should not be displayed as disambiguations.
2. Device a way to mine classes from the python docs that don't destroy the disambiguations that should be displayed as disambiguations.

## People to notify
@jdorweiler @souravbadami 

---

Instant Answer Page: https://duck.co/ia/view/python

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
> Does anybody have an example where a Disambiguation is the correct thing to show?

I don't know of any examples but there could be some (see 3, below).

The three use cases for the pypi fathead that I can think of are:

1. searching for a python class. We could show a brief summary of the class. Some short example would be nice to have too but I know not all pages in the docs have that. Then we could link to the disambiguation through the infobox. 

2. searching for a python class method or attribute. In this case the user knows what they're looking for so we can show them a single fathead result. 

3. search for a python class but the documentation doesn't have a summary or usage example. In this case we don't really have anything to show other than a disambiguation. 

> I have found more cases where I think we would like to change the view, as @jdorweiler suggested in the #526:
> https://duckduckgo.com/?q=python+shlex&t=ffsb&ia=meanings&iai=%2F35%2Fshlex.quote
> https://duckduckgo.com/?q=python+pickletools&t=ffsb&ia=meanings&iai=%2F35%2Fpickletools.genops
> https://duckduckgo.com/?q=python+msvcrt&t=ffsb&ia=meanings

Yes, these are good examples.

**Comment by Hestben** [comment]
I have extracted all the answers that are outputted as Disambiguations right now:
https://duckduckgo.com/?q=python+inspect
https://duckduckgo.com/?q=python+asyncio
https://duckduckgo.com/?q=python+python2+xml.dom.pulldom
https://duckduckgo.com/?q=python+collections
https://duckduckgo.com/?q=python+stat
https://duckduckgo.com/?q=python+hmac
https://duckduckgo.com/?q=python+concurrent.futures
https://duckduckgo.com/?q=python+cmath
https://duckduckgo.com/?q=python+uu
https://duckduckgo.com/?q=python+email.header
https://duckduckgo.com/?q=python+colorsys
https://duckduckgo.com/?q=python+python2+sysconfig
https://duckduckgo.com/?q=python+python2+binascii
https://duckduckgo.com/?q=python+glob
https://duckduckgo.com/?q=python+urllib.parse
https://duckduckgo.com/?q=python+http
https://duckduckgo.com/?q=python+python2+winsound
https://duckduckgo.com/?q=python+getpass
https://duckduckgo.com/?q=python+random
https://duckduckgo.com/?q=python+python2+sys
https://duckduckgo.com/?q=python+lzma
https://duckduckgo.com/?q=python+xml.dom.minidom
https://duckduckgo.com/?q=python+python2+socket
https://duckduckgo.com/?q=python+python2+xml.sax
https://duckduckgo.com/?q=python+python2+warnings
https://duckduckgo.com/?q=python+unittest.mock
https://duckduckgo.com/?q=python+parser
https://duckduckgo.com/?q=python+python2+xml.sax.saxutils
https://duckduckgo.com/?q=python+calendar
https://duckduckgo.com/?q=python+signal
https://duckduckgo.com/?q=python+heapq
https://duckduckgo.com/?q=python+python2+operator
https://duckduckgo.com/?q=python+socket
https://duckduckgo.com/?q=python+csv
https://duckduckgo.com/?q=python+imp
https://duckduckgo.com/?q=python+python2+pprint
https://duckduckgo.com/?q=python+select.devpoll
https://duckduckgo.com/?q=python+python2+collections
https://duckduckgo.com/?q=python+xml.sax
https://duckduckgo.com/?q=python+plistlib
https://duckduckgo.com/?q=python+python2+getpass
https://duckduckgo.com/?q=python+python2+curses
https://duckduckgo.com/?q=python+python2+plistlib
https://duckduckgo.com/?q=python+pdb
https://duckduckgo.com/?q=python+fpectl
https://duckduckgo.com/?q=python+mimetypes
https://duckduckgo.com/?q=python+python2+socket.socket
https://duckduckgo.com/?q=python+bz2
https://duckduckgo.com/?q=python+marshal
https://duckduckgo.com/?q=python+shutil
https://duckduckgo.com/?q=python+re.match
https://duckduckgo.com/?q=python+python2+difflib
https://duckduckgo.com/?q=python+hashlib
https://duckduckgo.com/?q=python+json
https://duckduckgo.com/?q=python+decimal
https://duckduckgo.com/?q=python+compileall
https://duckduckgo.com/?q=python+traceback
https://duckduckgo.com/?q=python+fractions
https://duckduckgo.com/?q=python+quopri
https://duckduckgo.com/?q=python+python2+uuid
https://duckduckgo.com/?q=python+unicodedata
https://duckduckgo.com/?q=python+shelve
https://duckduckgo.com/?q=python+python2+heapq
https://duckduckgo.com/?q=python+email.encoders
https://duckduckgo.com/?q=python+tkinter
https://duckduckgo.com/?q=python+zipfile
https://duckduckgo.com/?q=python+types
https://duckduckgo.com/?q=python+multiprocessing
https://duckduckgo.com/?q=python+python2+ast
https://duckduckgo.com/?q=python+msilib
https://duckduckgo.com/?q=python+subprocess
https://duckduckgo.com/?q=python+msvcrt
https://duckduckgo.com/?q=python+resource
https://duckduckgo.com/?q=python+select
https://duckduckgo.com/?q=python+pickletools
https://duckduckgo.com/?q=python+select.poll
https://duckduckgo.com/?q=python+shlex
https://duckduckgo.com/?q=python+time
https://duckduckgo.com/?q=python+ctypes
https://duckduckgo.com/?q=python+dis
https://duckduckgo.com/?q=python+operator
https://duckduckgo.com/?q=python+syslog
https://duckduckgo.com/?q=python+email.utils
https://duckduckgo.com/?q=python+xml.dom.pulldom
https://duckduckgo.com/?q=python+zlib
https://duckduckgo.com/?q=python+python2+tty
https://duckduckgo.com/?q=python+re
https://duckduckgo.com/?q=python+python2+xml.etree.ElementTree
https://duckduckgo.com/?q=python+base64
https://duckduckgo.com/?q=python+fileinput
https://duckduckgo.com/?q=python+python2+logging
https://duckduckgo.com/?q=python+io
https://duckduckgo.com/?q=python+tty
https://duckduckgo.com/?q=python+python2+csv
https://duckduckgo.com/?q=python+curses.panel
https://duckduckgo.com/?q=python+difflib
https://duckduckgo.com/?q=python+ast
https://duckduckgo.com/?q=python+pkgutil
https://duckduckgo.com/?q=python+winsound
https://duckduckgo.com/?q=python+statistics
https://duckduckgo.com/?q=python+python2+os
https://duckduckgo.com/?q=python+gc
https://duckduckgo.com/?q=python+stringprep
https://duckduckgo.com/?q=python+webbrowser
https://duckduckgo.com/?q=python+curses.ascii
https://duckduckgo.com/?q=python+linecache
https://duckduckgo.com/?q=python+zipapp
https://duckduckgo.com/?q=python+python2+pickle
https://duckduckgo.com/?q=python+socket.socket
https://duckduckgo.com/?q=python+python2+doctest
https://duckduckgo.com/?q=python+python2+linecache
https://duckduckgo.com/?q=python+os.path
https://duckduckgo.com/?q=python+curses
https://duckduckgo.com/?q=python+doctest
https://duckduckgo.com/?q=python+python2+inspect
https://duckduckgo.com/?q=python+turtle
https://duckduckgo.com/?q=python+sys
https://duckduckgo.com/?q=python+modulefinder
https://duckduckgo.com/?q=python+typing
https://duckduckgo.com/?q=python+python2+bz2
https://duckduckgo.com/?q=python+python2+itertools
https://duckduckgo.com/?q=python+ossaudiodev
https://duckduckgo.com/?q=python+imaplib
https://duckduckgo.com/?q=python+python2+hmac
https://duckduckgo.com/?q=python+ssl
https://duckduckgo.com/?q=python+urllib.request
https://duckduckgo.com/?q=python+sysconfig
https://duckduckgo.com/?q=python+threading
https://duckduckgo.com/?q=python+locale
https://duckduckgo.com/?q=python+wave
https://duckduckgo.com/?q=python+python2+decimal
https://duckduckgo.com/?q=python+winreg
https://duckduckgo.com/?q=python+contextlib
https://duckduckgo.com/?q=python+python2+fcntl
https://duckduckgo.com/?q=python+pprint
https://duckduckgo.com/?q=python+code
https://duckduckgo.com/?q=python+sunau
https://duckduckgo.com/?q=python+readline
https://duckduckgo.com/?q=python+textwrap
https://duckduckgo.com/?q=python+python2+traceback
https://duckduckgo.com/?q=python+_thread
https://duckduckgo.com/?q=python+python2+functools
https://duckduckgo.com/?q=python+xml.etree.ElementTree
https://duckduckgo.com/?q=python+bdb
https://duckduckgo.com/?q=python+python2+cgitb
https://duckduckgo.com/?q=python+python2+ensurepip
https://duckduckgo.com/?q=python+python2+ssl
https://duckduckgo.com/?q=python+xml.dom
https://duckduckgo.com/?q=python+python2+crypt
https://duckduckgo.com/?q=python+binhex
https://duckduckgo.com/?q=python+unittest.mock.call
https://duckduckgo.com/?q=python+filecmp
https://duckduckgo.com/?q=python+logging
https://duckduckgo.com/?q=python+tokenize
https://duckduckgo.com/?q=python+distutils
https://duckduckgo.com/?q=python+python2+audioop
https://duckduckgo.com/?q=python+python2+pkgutil
https://duckduckgo.com/?q=python+cgi
https://duckduckgo.com/?q=python+string
https://duckduckgo.com/?q=python+pyclbr
https://duckduckgo.com/?q=python+math
https://duckduckgo.com/?q=python+itertools
https://duckduckgo.com/?q=python+email.contentmanager
https://duckduckgo.com/?q=python+keyword
https://duckduckgo.com/?q=python+python2+select.epoll
https://duckduckgo.com/?q=python+getopt
https://duckduckgo.com/?q=python+python2+os.path
https://duckduckgo.com/?q=python+email
https://duckduckgo.com/?q=python+python2+xml.dom
https://duckduckgo.com/?q=python+fnmatch
https://duckduckgo.com/?q=python+dbm
https://duckduckgo.com/?q=python+termios
https://duckduckgo.com/?q=python+os
https://duckduckgo.com/?q=python+select.epoll
https://duckduckgo.com/?q=python+python2+tempfile
https://duckduckgo.com/?q=python+codecs
https://duckduckgo.com/?q=python+python2+unittest
https://duckduckgo.com/?q=python+python2+textwrap
https://duckduckgo.com/?q=python+bisect
https://duckduckgo.com/?q=python+python2+dbm
https://duckduckgo.com/?q=python+python2+binhex
https://duckduckgo.com/?q=python+binascii
https://duckduckgo.com/?q=python+ipaddress
https://duckduckgo.com/?q=python+python2+codecs
https://duckduckgo.com/?q=python+faulthandler
https://duckduckgo.com/?q=python+python2+threading
https://duckduckgo.com/?q=python+importlib
https://duckduckgo.com/?q=python+pickle
https://duckduckgo.com/?q=python+unittest
https://duckduckgo.com/?q=python+struct
https://duckduckgo.com/?q=python+python2+sndhdr
https://duckduckgo.com/?q=python+tarfile
https://duckduckgo.com/?q=python+python2+unicodedata
https://duckduckgo.com/?q=python+pty
https://duckduckgo.com/?q=python+tracemalloc
https://duckduckgo.com/?q=python+py_compile
https://duckduckgo.com/?q=python+xml.sax.saxutils
https://duckduckgo.com/?q=python+python2+locale
https://duckduckgo.com/?q=python+aifc
https://duckduckgo.com/?q=python+email.iterators
https://duckduckgo.com/?q=python+python2+turtle
https://duckduckgo.com/?q=python+collections.OrderedDict
https://duckduckgo.com/?q=python+functools
https://duckduckgo.com/?q=python+python2+io
https://duckduckgo.com/?q=python+gzip
https://duckduckgo.com/?q=python+python2+importlib
https://duckduckgo.com/?q=python+python2+json
https://duckduckgo.com/?q=python+runpy
https://duckduckgo.com/?q=python+python2+xml.dom.minidom
https://duckduckgo.com/?q=python+python2+subprocess
https://duckduckgo.com/?q=python+python2+string
https://duckduckgo.com/?q=python+timeit
https://duckduckgo.com/?q=python+python2+timeit
https://duckduckgo.com/?q=python+site
https://duckduckgo.com/?q=python+audioop
https://duckduckgo.com/?q=python+xml.parsers.expat

Some don't trigger an IA, though, like 
https://duckduckgo.com/?q=python+concurrent.futures
The disambiguations with "python2" seems to be an error, like
https://duckduckgo.com/?q=python+python2+string

**Comment by Hestben** [comment]
I added more comments in the code with questions from me in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/538/commits/e35b5bf84e7d14a1da2b44c37fabd5792d23cbec
I'll let the weekend pass (to wait for comments) before I do any more work on this.
@jdorweiler Is there anyone else familiar with the code that can clarify my questions?

**Comment by jdorweiler** [comment]
@jrasanen created `redirect.py` so maybe he could help too. The basic idea is to handle conflicting class method names by looking at the whole python name space. If we don't find a conflicting name we add redirects. 
So for example searching for `python assertequal` shows the article for `unittest.testcase.assertequal` because we looked through the whole name space and know that this is the only `assertEqual` method.

**Comment by Hestben** [comment]
Thanks for the explanation @jdorweiler.
I also found that this leads to that if the python2 and python3 abstracts differs, no redirect will be generated.
An example is st2tuple:
https://duckduckgo.com/?q=python+st2tuple&t=ffsb&ia=web
st2tuple is actually only in the parsers module, but since the abstract between python2 and python3 documentation differ, you have to search for the whole to get an IA:
https://duckduckgo.com/?q=python+parser+st2tuple&t=ffsb&ia=about
https://duckduckgo.com/?q=python2+parser+st2tuple&t=ffsb&ia=about

**Comment by jdorweiler** [comment]
That sounds like a bug to me. We would want to show the python3 result in that case.

**Comment by Hestben** [comment]
I just pushed two commits that change the output type to Article, and adds the topics we used to add in the Disambiguation abstract field to the "Related Topics" field instead.

There are still a lot of articles that have a Category, and in those cases, my understanding is that the entries with the same category will be displayed in the "Related Topics".

Categories are set in parse.py. As far as I have understood the categories are set because of python2/python3 disambiguations. Related to this is this issue: https://github.com/duckduckgo/zeroclickinfo-fathead/issues/555

**Comment by jdorweiler** [comment]
@Hestben sorry for the delay. Looks like it got rid of the disambiguations though. 
What about removing this bit from the abstracts. 
selection_052

**Comment by Hestben** [comment]
> Looks like it got rid of the disambiguations though.

Yes, I decided to change the entry type to Article, for all entries. Were there any cases where Disambiguation would be the correct type?

Regarding the "python functools" query above. In the docs, it is unfortunately using a different layout, and that information is first on the site (https://docs.python.org/3.6/library/functools.html). To get rid of that, it looks like we would have to tweak the fathead mining.

**Comment by Hestben** [comment]
@jdorweiler 
> Regarding the "python functools" query above. In the docs, it is unfortunately using a different layout, and that information is first on the site (https://docs.python.org/3.6/library/functools.html). To get rid of that, it looks like we would have to tweak the fathead mining.

I think I have a possible solution for that. We could look for the tag `<hr class="docutils" />`, and take the paragraphs after this tag as intro text. But, in some documents this tag isn't present, namely: https://docs.python.org/3/library/functions.html?highlight=built%20functions. There, I found that we provide a strange IA for https://duckduckgo.com/?q=python+abs%28%29&t=ffsb&ia=about
Should I continue work on a general solution for this "intro text"-issue in this PR, or should I start a new. Or should I rather continue with some more pressing issues (like #555)?

**Comment by jdorweiler** [comment]
@Hestben I'll make issues to look into the weird result for `python abs` and fixing the intro text. #555 is higher priority so if you're looking for something to work on I'd pick that.  Thanks!

**Comment by jdorweiler** [comment]
:+1: looks good. Thanks @Hestben

**Pull request merged**
