### PR TITLE
Removed redirects 'lenient', 'downloads' and 'push', changed SKIndex to use macOS SKIndex instead

### PR DESCRIPTION
**Pull request by usernameisntallowed**
Apple Docs MacOS: Removed redirects 'lenient', 'downloads' and 'push', changed SKIndex to use macOS SKIndex instead for overtriggering bug.

## Description of new Instant Answer, or changes
Removed redirects 'lenient', 'downloads' and 'push', changed SKIndex to use macOS SKIndex instead for overtriggering bug in the relevant output.txt s.

## Related Issues and Discussions
https://github.com/duckduckgo/zeroclickinfo-fathead/issues/501

## People to notify
@jagtalon @GuiltyDolphin @souravbadami @tagawa
## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)
https://duck.co/ia/view/apple_docs_macos

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/apple_docs_macos

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@doorknob22 TMK I believe you will have to update the parser - just updating the `output.txt` files will cause your changes to be overwritten when the parser is re-run. 

Why not have a look at the parser and sources and see what other queries are causing issues, perhaps there's some kind of pattern. If there is, you may well be able to update the parser to fix many cases at once.

**Comment by doorknob22** [comment]
Understood, I'll begin taking a look at the parsing as I find the time. If anybody has pointers about how it works, recommended reading or similar examples, thanks.

**Comment by doorknob22** [comment]
Ready for review again at your convenience.

**Comment by doorknob22** [comment]
Just wanted to check in if there's anything I can do for this bug fix, I'm not sure who kicked off the daxtheduck deploy to beta and if there's anything I can do to help.

**Comment by pjhampton** [comment]
Hey @usernameisntallowed!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
