### PR TITLE
MDN CSS: Put cleaned title in the redirect field.

### PR DESCRIPTION
**Pull request by hchienjo**
Put cleaned title in redirect field as opposed to the uncleaned title.

cc @moollaza 

https://duck.co/ia/view/mdn_css

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@hchienjo looks like this branch is a little behind. Can you `git reset --hard upsteam/mdn_css` and then `git cherry-pick fdf52b018868a9673b9120ed760af7622d8e2fd5`, then `git push -f`.

That should reset this PR so that it only contains the commit where you've adjusted the `title`

**Comment by hchienjo** [comment]
@moollaza Sorry. 

I have done as you have adviced now am not sure if I have made the situation worse.

**Comment by hchienjo** [comment]
I think I messed this PR. Let me close it for now.

**Pull request closed without merging**
