### PR TITLE
New IdrisDoc FatHead

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
FatHead for Idris documentation.

---
IA Page: https://duck.co/ia/view/idris_doc
Maintainer: @GuiltyDolphin

### CODE REVIEW

**Comment by daxtheduck** [comment]
@GuiltyDolphin Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
thanks ben!

**Comment by GuiltyDolphin** [comment]
@jdorweiler Could we get this deployed? This is pretty much done :)

**Comment by jdorweiler** [comment]
@GuiltyDolphin getting an error when I run parse. 
```
Duplicate article with title 'JS_Types' detected
Duplicate article with title 'JS_IntTypes' detected
Duplicate article with title 'JS_FnTypes' detected
Duplicate article with title 'IO'' detected
Duplicate article with title 'FTy' detected
Duplicate article with title '=' detected
Duplicate article with title 'FFI' detected
Can't call method "all_text" on an undefined value at parse.pl line 425.
```

**Comment by GuiltyDolphin** [comment]
@jdorweiler Sorry about that - had a bit of uncommited code :worried: 

Please ignore the 'duplicate article' messages for the mo' (I'm working on a fix) - there are some duplicated pages.

**Comment by jdorweiler** [comment]
It's on beta now. 
https://beta.duckduckgo.com/?q=idris+ifThenElse&ia=about

**Comment by GuiltyDolphin** [comment]
@jdorweiler Thanks! Looks like I've got a bug straight off ^.^

**Comment by GuiltyDolphin** [comment]
@jdorweiler Can we try deploying this?

Locally `<pre><code>` just displays normally, but on Beta everything gets escaped, so I've tried using just `<pre>`; this is a nightmare w/o access to the final parser!

**Comment by jdorweiler** [comment]
What does it look like on duckpan? Can you post a screenshot?

**Comment by GuiltyDolphin** [comment]
@jdorweiler 

Locally:

screenshot-2016-08-04-15 57 37_726_326

**Comment by GuiltyDolphin** [comment]
@jdorweiler Could you deploy this?

Assuming everything works in terms of Beta, this is everything I want to do (for now).

**Comment by moollaza** [comment]
@GuiltyDolphin everything up to the last two comments should be deployed (if my Beta deploy worked..)

**Comment by moollaza** [comment]
@GuiltyDolphin the code blocks now look correct!

https://beta.duckduckgo.com/?q=Data.Vect.Vect&t=hd&ia=about

**Comment by GuiltyDolphin** [comment]
@moollaza Mostly! Yeah, I've had to comprimise a couple of things due to some issues with the FatHead parser/back-end; but ignoring those - this should be ready (it's kitted out with everything it needs :cat: )

**Comment by moollaza** [comment]
@jdorweiler @GuiltyDolphin by the way, thanks to @mrshu I was able to determine today that a Fathead with Categories and Related Topics will always produce an Infobox that only links to the Categories. If Categories aren't present, then Related Topics will be used for the infobox.

For now I think we'll have to tolerate this, but it's definitely something we'll need to fix.

**Comment by moollaza** [comment]
@GuiltyDolphin just tried ["idris vect"](https://beta.duckduckgo.com/?q=idris+vect&t=hd&ia=meanings&iai=%2F187%2FData.VectType.Vect.Vect_(Data_Type_-_effects)) and it looks like most of those disambiguation results aren't working.

Can you verify if the output.txt is correct?

It looks like your disambiguation here is pointing to more disambiguations but they don't seem to work...

**Comment by GuiltyDolphin** [comment]
@moollaza Yeah, everything is fine locally - it seems to be the `(X - package)` entries that aren't working on Beta.

The disambiguations seem to be working though:

https://beta.duckduckgo.com/?q=idris+vect&t=hd&ia=meanings

Then click on the page with `Module`:

https://beta.duckduckgo.com/187/d/Data.Vect_(module)?ia=meanings

I think everything is working 'correctly' up to how the FH parser/front-end modifications are affecting it; most things seem to be working okay though.

**Comment by moollaza** [comment]
@GuiltyDolphin looking at the links those redirects point to, the issues is the `()` in the article title.

We actually strip those out of the article's title in the DB (I believe) and use the content inside the `()` as the subtitle.

The title without the `()` works as expect: https://beta.duckduckgo.com/?q=Data.VectType.Vect.Vect+Data+Type+contrib&ia=about

@jdorweiler do you know how we should be handling these?

**Comment by GuiltyDolphin** [comment]
@moollaza Hmm... It's not stripping it *completely*, as the subtitle has the `-` in: https://beta.duckduckgo.com/?q=Data.VectType.Vect.Vect+(Data+Type++effects)&ia=about&iax=1

screenshot-2016-08-15-16 31 57_322_34

It just seems to be the triggering :confused:

**Comment by GuiltyDolphin** [comment]
@moollaza Are these issues pressing, or would it be possible to get this merged and sort these out separately? The issues seem to be entirely based around the external parser/back-end, so I'm not sure there's much I can do which isn't a terrible hack.

It'd be useful to start getting some user feedback on this (and I'm tired of typing `!beta` all the time :wink:).

**Comment by daxtheduck** [comment]
@GuiltyDolphin this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
