### PR TITLE
restore dist.ini and FatheadBundle namespace, add metadata.json bundling

### PR DESCRIPTION
**Pull request by moollaza**
/cc @jdorweiler @russellholt 

It seems that Getty added this functionality back on Nov 9th, 2012 (looking at, https://github.com/duckduckgo/zeroclickinfo-fathead/commit/62ebb8f554641bb85868345d4ae7abe68d4103ff and https://github.com/duckduckgo/zeroclickinfo-fathead/releases)

But somehow the changes were removed from history (an incorrect force push?) and can no longer be found in the Git log.

This commit brings back the required files to make this dist releasable and adds in the new `Before::Build` code to store the Fathead metadata.json file in the repo

### CODE REVIEW

**Comment by jdorweiler** [comment]
should all the fatheads be in `share/fathead/` to fit with the other repos?  Currently they're in `/share/`

**Comment by moollaza** [comment]
Hmm browsing the Fathead repo files at the time of Getty's initial release, they *were* organized like that and then it seems there was a confusing series of changes and reverts. I think the intention was to organize everything the same way. Given the way that DDG::Meta::ShareDir.pm works, which uses the package name to build the `share_path` -- so if we ever plan to use the `share` function to access share files it should be organized that way. I'm not sure if it would cause problems on the backend, but for now it should be OK to ignore

**Comment by jdorweiler** [comment]
I only see one spot the fathead install scripts that would be a problem.  I can easily fix that though.

**Comment by jdorweiler** [comment]
:+1:  Thanks!

**Pull request merged**
