### PR TITLE
Python: New Scipy fathead

### PR DESCRIPTION
**Pull request by ashishbhate**
## Description of new Instant Answer, or changes
Scipy Fathead

## Related Issues and Discussions

Fixes: #685 

## People to notify

@pjhampton 
@moollaza 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [x] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [x] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/scipy

## Notes

This is nearly the same code as the numpy fathead. The changes are mostly just changing references to numpy (triggers words, urls, paths etc.) to scipy.

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by ashishbhate** [comment]
The `output.txt` file is 2.2MB so I haven't pushed it yet.

**Comment by pjhampton** [comment]
This rocks @ashishbhate! :metal: Yeah, I really like your code. Maybe we could abstract it into a reusable template at some stage. As for the output.txt, please push it for now. We can uncommit it later but it's important to push it to a dev machine in the reviewing stage. Also, please update the IA page with some example queries.

**Comment by ashishbhate** [comment]
Thanks @pjhampton! I've pushed the `output.txt` file and updated the IA page.

**Comment by moollaza** [comment]
@ashishbhate Thanks! This LGTM :+1:

I don't like the use of a `<pre><code>` block for the parameters though because we're applying syntax highlighting to the description text of each parameter. (e.g. https://beta.duckduckgo.com/?q=scipy.interpolate.UnivariateSpline&ia=about&iax=1)

I think we should instead build ` <ul>` or possibly a `<table>` (I'm not sure if that will work) 

e.g.

```html
<ul>
  <li>
    <code>x</code>: <em>(N,) array_like</em>
    <p>1-D array of independent input data. Must be increasing.</p>
  </li>
  <li>
    <code>y</code>: <em>(N,) array_like</em>
    <p>1-D array of dependent input data, of the same length as x. </p>
  </li>
  ...
```

**Comment by daxtheduck** [comment]
@ashishbhate this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
