### PR TITLE
C++: CPP Boost Data source updated and a minor bug fix in fetch.sh

### LINKED ISSUE #739: Cpp Boost Suggestion: Update the data source
**Suggestion**

Update  the data source link http://www.boost.org/doc/libs/1_62_0/ to the new data source link
http://www.boost.org/doc/libs/1_63_0/

------
IA Page:  http://duck.co/ia/view/cpp_boost 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nikhilsingh291

### PR DESCRIPTION
**Pull request by adityatandon007**
## Description of new Instant Answer, or changes
Source updated from  http://www.boost.org/doc/libs/1_62_0/ to
http://www.boost.org/doc/libs/1_63_0/ and a minor fix in file fetch.sh 

- **removed** wget http://www.boost.org/doc/libs/1_62_0

- **added**     wget http://www.boost.org/doc/libs/1_62_0 -O index.html

## Related Issues and Discussions
Fixes #739 

## People to notify
@pjhampton @nikhilsingh291 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [x] Uniformly indented, well commented
- [x] Fetch.sh and Parse.sh run without errors
- [x] Output contains no blank lines, or multi-line entries
- [x] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/cpp_boost

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
This is good! Thanks @adityatandon007 
I'm going to hold of merging this until @moollaza looks at it. It seems that the 1_62_0 is showing up instead of 1_63_0 on beta which is strange

**Comment by adityatandon007** [comment]
@pjhampton @moollaza It seems the maintainer was using URL_DOC variable in parse.py to hard code the url link therefore our output.txt is not showing that updated link when clicking on more at but I have updated that URL_DOC. Can you look into it. Hope this helps :+1:

**Comment by adityatandon007** [comment]
@pjhampton can you merge this PR it is sitting ideal for the last 8 days

**Comment by pjhampton** [comment]
Hey @adityatandon007 

We really appreciate your enthusiasm 💜 . _Sitting idle_ is not a reason to merge code into a codebase. We need to investigate the versioning I discussed above. 53ef45b has not addressed the issue.

**Comment by moollaza** [comment]
@adityatandon007 Thanks! This LGTM :+1:

**Pull request merged**
