### PR TITLE
Create Instant Answer for HTTP headers information

### PR DESCRIPTION
**Pull request by andrewalker**
**What does your Instant Answer do?**

It shows information about HTTP headers.

**What problem does your Instant Answer solve (Why is it better than organic links)?**

When somebody searches for an HTTP header by name, what they are probably looking for is to know what it means and an example of usage, which is what this PR implements.

**What is the data source for your Instant Answer? (Provide a link if possible)**

Wikipedia: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

**Why did you choose this data source?**

Because it was mentioned as a possible data source in the idea posted to duck.co: https://duck.co/ideas/idea/4859/http-headers-description, and it seemed like a good choice.

**Are there any other alternative (better) data sources?**

There is an alternative: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
I don't know if it is better. It doesn't include non-standard headers (even if they are really common).

**What are some example queries that trigger this Instant Answer?**

   - ``http header content-type``
   - ``user agent http header``
   - ``if-modified-since``

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Programmers.

**Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?**

Yes: https://duck.co/ideas/idea/4859/http-headers-description

**Which existing Instant Answers will this one supersede/overlap with?**

If I type "user-agent", it actually shows my current user agent. If I type "accept", it'll show audio tracks by a band with that name. I'm sure there will be other overlaps, mostly when only the header name is typed, not followed by ``http header`` or something like that.

**Are you having any problems? Do you need our help with anything?**

This is my first Instant Answer. It seemed to work fine, but I'd love to have some feedback on whether it follows all best practices, works as expected, and didn't miss anything.

**Where did you hear about DuckDuckHack? (For first time contributors)**

DuckDuckGo's hiring page :smile: I had visited DuckDuckHack a few times before, and I don't know where I first heard about it, but that is what motivated me to make a first contribution.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

I don't know! How can I test Fathead instant answers?

### CODE REVIEW

**Comment by MrChrisW** [comment]
@andrewalker Thanks for your contribution. This will be reviewed shortly.

**Comment by moollaza** [comment]
Hi @andrewalker thanks a lot for making this! We really appreciate it. After a quick glance I don't see any big problems.

>I don't know! How can I test Fathead instant answers?

Haha sorry about that! Currently developers can't test their Fatheads, we'll have to test it on our end and give you feedback.

@jdorweiler will review this and give you some feedback shortly :smiley:

**Comment by andrewalker** [comment]
@moollaza thank you for taking a look :)

About testing, ok, no problem. I'll wait for the tests on ddg's end and @jdorweiler's review.

**Comment by jdorweiler** [comment]
@andrewalker thanks, looks pretty good.  Can you create redirect entries (R for the type field) for the hyphenated titles.  That way searches for `Access Control Allow Origin` would show the entry for `Access-Control-Allow-Origin `.  Do you have any trigger words in mind?

**Comment by andrewalker** [comment]
@jdorweiler sure, I'll create redirect entries. I couldn't think of any other trigger words...

**Comment by andrewalker** [comment]
@jdorweiler I found another issue, I'm not quite sure how to fix it.

Some headers (e.g. ``Content-Type``, ``Cache-Control``, ``Connection``) will have more than one definition, because they are listed both in the ``Request fields`` and ``Response fields``.

We could use disambiguation, I guess, though generally they look very similar.

Example:

**Connection (request)**: Control options for the current connection and list of hop-by-hop request fields.
**Connection (response)**: Control options for the current connection and list of hop-by-hop response fields.

I tried to look for how to create disambiguation entries, but the [Fathead docs](https://duck.co/duckduckhack/fathead_overview) don't seem to include any information about it.

How should I proceed?

**Comment by andrewalker** [comment]
Oh, and I also implemented the redirection in 26ad0a3 :)

**Comment by andrewalker** [comment]
@jdorweiler, did you have a chance to take a look?

**Comment by jdorweiler** [comment]
@andrewalker looks pretty good.  You can test it out here: https://ddh10.duckduckgo.com/?q=http+content+type&ia=about

Could you link to the actual entry in to table on the wiki page?

**Comment by andrewalker** [comment]
Right. So do you think it's okay to leave the ambiguous results as is?

> Could you link to the actual entry in to table on the wiki page?

I'm not sure it is possible. Looking at the source code, very few \<tr\>'s have id's. Maybe I could edit the Wikipedia page to set the id's, though I've never edited anything there before. Another possibility is to link to the table at least.

Which way should I go?

**Comment by andrewalker** [comment]
@jdorweiler also, thanks for the link! It's nice to see it is working :smile:

**Comment by jdorweiler** [comment]
@andrewalker You're right, I remember a similar problem linking into a wiki table on another fathead.  You can just leave it linking to the main page then.  I'll look into the disambiguations and get back to you.  I think we only use that type for scraping mediawiki articles.

**Comment by jdorweiler** [comment]
@andrewalker after some playing around I got a disambiguation to work.  The format should look like this:
```
title \t D \t \t \t \t \t \t \t \t* [[title]],text that you want to show for this\n*[[another one]],and some more text

```

**Comment by andrewalker** [comment]
Awesome, thank you, @jdorweiler! I'll try and implement this. If it doesn't fit well (if it really only works for mediawiki articles), we can just revert it.

**Comment by jdorweiler** [comment]
@andrewalker the disambiguation would show up on a "meanings" tab like this https://duckduckgo.com/?q=orange&t=canonical&ia=meanings

**Comment by jdorweiler** [comment]
@andrewalker did you get a chance to try the disambiguation out or do you have any questions?

**Comment by andrewalker** [comment]
@jdorweiler, yes, I tried it :)

Sorry for the delay, my current job demanded a lot this last week. It was a little tough finding the time to finish this up.

Anyway, please take a look at be1847e3c9732ed2e5215e20f0826d7bbfb4d560. It seems a little weird to have things like:

```
*[[Response]],The date and time that the message was sent (in "HTTP-date" format as defined by RFC 7231).<br><pre><code>Date: Tue, 15 Nov 1994 08:12:31 GMT</code></pre>\n*[[Request]],The date and time that the message was sent (in "HTTP-date" format as defined by RFC 7231).<br><pre><code>Date: Tue, 15 Nov 1994 08:12:31 GMT</code></pre>\n
```

They are both very similar. I don't know how we could improve that. Maybe it's more of a UI/UX issue, it's a little out of my league :P

Also, I basically copied the same content that was in the "A" types, including HTML in the description/example, and the link to the wikipedia article. Is that OK? Should I remove it? I see in your example you didn't use HTML, and left the URL empty.

**Comment by jdorweiler** [comment]
@andrewalker thanks!  the disambiguation entries look good.  The linking on the tiles is a little weird but that's a problem on my end. 
https://ddh10.duckduckgo.com/?q=http+connection&ia=meanings
selection_359

A few more examples. 
https://ddh10.duckduckgo.com/?q=http+dnt&ia=about
selection_358

https://ddh10.duckduckgo.com/?q=http+header+user+agent&ia=about

selection_360

**Comment by jdorweiler** [comment]
Try it out on ddh10.duckduckgo.com and let me know what you think.

**Comment by moollaza** [comment]
This is looking awesome guys, nicely done!

**Comment by andrewalker** [comment]
looks great, @jdorweiler and @moollaza. Thank you so much for reviewing it!

**Comment by jdorweiler** [comment]
@andrewalker what about adding "header" or "headers" to each title as a redirect.  That way things like "http location header" would redirect to the "location" entry?

**Comment by andrewalker** [comment]
@jdorweiler sure! will do.

**Comment by jdorweiler** [comment]
@andrewalker thanks! It's ready to merge after that.

**Comment by andrewalker** [comment]
@jdorweiler done! :smile:

**Comment by jdorweiler** [comment]
Thanks @andrewalker! :cake:

**Pull request merged**
