### PR TITLE
Missing parse file added of C++ Reference fathead

### PR DESCRIPTION
**Pull request by amarlearning**
## Description of new Instant Answer, or changes

[C++ Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/cppreference_doc) : Missing `parse.py` file added of C++ Reference Fathead

## People to notify

@rasikapohankar 

---

Instant Answer Page: https://duck.co/ia/view/cppreference_doc

### CODE REVIEW

**Comment by daxtheduck** [comment]
@amarlearning Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@amarlearning how big is the generated `output.txt` file? If it's < 1MB please add it to your commit!

**Comment by rasikapohankar** [comment]
@moollaza @amarlearning any idea how the link of the archive for DDG will be updated? It has `http://upload.cppreference.com/mwiki/images/9/9e/cppreference-doc-20151129-ddg.tar.gz` while the latest archive [here](http://en.cppreference.com/w/Cppreference:Archives) is for 29-10-2016

**Comment by moollaza** [comment]
> any idea how the link of the archive for DDG will be updated?

@rasikapohankar @amarlearning that's a good point -- honestly, I'm not quite sure. This Fathead is very old and came before I was involved in this stuff.

I would read through the [original PR](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/50) and see if anything was mentioned about the script being updated.

Also, you could reach out to the developer, or open an issue in their GitHub repo to get CPPReference involved in working with us. That'd be ideal 👍

**Comment by amarlearning** [comment]
@moollaza It's around 2MB. what do you say should i add it ?

**Comment by rasikapohankar** [comment]
@moollaza The original PR does not mention the link for DDG but it looks like it was added in #177. I will reach out to the developer.

**Comment by moollaza** [comment]
@rasikapohankar nice find!

I would ask the dev if the tarball located at http://upload.cppreference.com/w/Cppreference:DDG-link?action=raw is still the most up to date, and if so we should be fine 👍

**Comment by p12tic** [comment]
Hi,

I'm the main maintainer of the cppreference-doc repository containing various auxiliary code that supports the cppreference.com website. Currently it also includes the code for creating the output.txt of the cppreference_doc Fathead plugin.

First of all, thanks to @rasikapohankar who brought this PR to light to me.

With regard to the tarball the Fathead plugin currently links to, the archive at upload.cppreference.com/w/Cppreference:DDG-link?action=raw is updated by linking to the most recent cppreference archive that someone actually tested to work. This way we don't accidentally break the Fathead plugin when new cppreference archives are released. Also, we have the freedom to create "special" archives specifically for DuckDuckGo. IIRC the latter was the case for
the 20151129-ddg version: the 20151129 version needed a couple of small fixes for the Fathead plugin to work.

With regard to the pull request: I would strongly advise not to extract the output.txt generation code to a separate repository. It strongly depends not only on another chunk of python code in the repository, but also on the exact structure of the website. The structure of the website
may be changed at any point, therefore various website-related code may, and often does become out-of-sync with the contents of the website. Putting that website-related code into a single repository, bundling it with snapshots of the website, testing and releasing semi-regularly is pretty much the only way to guarantee that the functionality provide by the said website-related code does not break out of the blue.

This approach makes it much easier for the cppreference team to update and support the auxiliary code. In fact, since I wrote the original code of the fathead plugin, it wouldn't be a significant task to update the output to a new format. Nobody did that yet simply because no one was aware that the format of the fathead plugins has changed.

I've skimmed the discussion in the pull request and the related issue (https://github.com/duckduckgo/zeroclickinfo-fathead/pull/177). I understand the organizational reasons for putting the code of the cppreference fathead plugin under the DuckDuckGo umbrella. Unfortunately that would mean that I personally wouldn't be able to support its development because doing so would greatly increase the amount of required time for few technical reasons. I'm afraid that as the cppreference website evolves, the fathead plugin code will inevitably bit rot to the point of unusability. Thus I don't recommend going that route.

I think it should be possible to collaborate on cppreference-doc repository without friction. All code on the repository is supported. I'm open to improving the parts that need work myself or accepting third-party PRs. The release schedule of the fathead plugin tarballs does not need to be aligned to the release schedule of the public "offline archive" versions they are based on, so the release cycle may be as short as we want it to be.

Having said that, I'm would be happy regardless of which direction is chosen. I just wanted to make sure the pros and cons of both options are known :-)

**Comment by rasikapohankar** [comment]
Hi @p12tic, thank you for the explanation! :)

@amarlearning @p12tic Since the [cppreference-doc](https://github.com/p12tic/cppreference-doc) is active, we can make a PR to that repository to update the output.txt generation. I will close this PR since adding the parsing script to our repository will now not be needed.

cc: @moollaza

**Comment by amarlearning** [comment]
@rasikapohankar I think parsing script should be added to the  cppreference-doc repository, because it will help the developers to make changes in the near future.

**rest is upto you!** :+1:

**Comment by sahildua2305** [comment]
Go ahead @rasikapohankar!

**Comment by sahildua2305** [comment]
@amarlearning I see your point. Valid enough! However, since we're going to maintain the parse script in the other repo (not in fathead repo), it makes no sense to copy it here (in fathead repo) as well. It will just create an overhead of keeping the two scripts in sync (updating it in fathead whenever it's updated in the other repo).

Hence, closing this PR. Let me know if you have any concerns 🙂

**Pull request closed without merging**
