### PR TITLE
Update cppreference_doc fathead

### LINKED ISSUE #407: C++ Reference Docs: Switch to use new Fathead Template Elements
We now have [Fathead Template Elements](https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract) designed specifically for Programming Fatheads. These are HTML elements that should be added to the output.txt by each Programming Fathead's parsing script(s).

This Fathead should be updated to use the templates:
- The entire abstract should be wrapped in a `<div>` with class `prog__container`
- Any text before/after the code blocks must be wrapped in `<p>` tags
- Any subheadings should be wrapped in a `<div>` with class `prog__sub`

Here is an example:

``` html
<section class="prog__container">
    <p>Creates a JavaScript Date instance that represents a single moment in time.</p>
    <pre>
        <code>
            new Date;
            new Date(value);
            new Date(dateString);
            new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
        </code>
    </pre>
    <span class="prog__sub">Return Value</span>
    <p>The removed element.</p>
</section>
```

---

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [C++ related searches](https://forum.duckduckhack.com/t/https://forum.duckduckhack.com/c/programming/66-category)!

---

IA Page:  http://duck.co/ia/view/cppreference_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ManrajGrover

### PR DESCRIPTION
**Pull request by p12tic**
## Description of new Instant Answer, or changes
 - Commits output.txt generated from cppreference.com archive as of 2017-02-14

## Related Issues and Discussions
Fixes #407

## People to notify
@moollaza, @sahildua2305, @ManrajGrover, @sergey-krusch, @pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/cppreference_doc

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by p12tic** [comment]
OK, so beta.duckduckgo.com indicates that this PR introduces certain changes that shouldn't have been introduced. Please don't approve nor merge.

**Comment by p12tic** [comment]
I'd like to retract the previous comment: it seems that the change was deliberately introduced by me.
A couple of questions to the maintainer:
 - Do you prefer split code sections for each function like it is in the currently published version or should they be merged into single code section? (compare https://duckduckgo.com/?q=cpp+array+end&ia=about and https://beta.duckduckgo.com/?q=cpp+array+end&ia=about). The latter seems more confusing to me, but I guess I was originally unsure whether the new guidelines allow it.
 - The output.txt is around 2MB of size. Should this be stripped? 8 other fatheads include larger output.txt files in the repository (two as large as 8MB).

**Comment by moollaza** [comment]
> Do you prefer split code sections for each function like it is in the currently published version or should they be merged into single code section?

Split looks good. DDG has no preference. I'm happy with whatever C++ developers prefer.

> The output.txt is around 2MB of size. Should this be stripped?

Nope that's fine, as you can see we've relaxed that requirement. It just makes life easier though the repo is a bigger.

> Stripping of parentheses in certain code snippets is a bug present in core DuckDuckGo for as long as I can remember :-) I have informed several DuckDuckGo members about this over the years, could you ping someone again to actually do something about it?

@p12tic can you give me an example? No parenthese should be removed from `<pre><code>` blocks. By default we treat parenthese in the article title as a subtitle, so we strip it out, but the IA page has the `skip parent` (its a typo...) checked so it should be ignoring the titles and leaving them as is. 

If I have an example I can investigate further 👍

**Comment by p12tic** [comment]
> Split looks good. DDG has no preference. I'm happy with whatever C++ developers prefer.
OK then, I'll revert back to split.

> Nope that's fine, as you can see we've relaxed that requirement. It just makes life easier though the repo is a bigger.

That's great to hear :-) output.txt and its diffs should be very compressible, so the actual increase of repo size is not that much.

> No parenthese should be removed from <pre><code> blocks. By default we treat parenthese in the article title as a subtitle, so we strip it out, but the IA page has the skip parent (its a typo...) checked so it should be ignoring the titles and leaving them as is.

For example, see this search: https://beta.duckduckgo.com/?q=cpp+array+cend&ia=about

The code example displays `constexpr const_iterator cend const;` whereas the expected code snippet is `constexpr const_iterator cend() const;`.

**Comment by moollaza** [comment]
> The code example displays constexpr const_iterator cend const; whereas the expected code snippet is constexpr const_iterator cend() const;.

We'll have to investigate this further -- oddly our database has the `()` in the text, so we're not stripping out in the processing of the output.txt -- I'm not sure where or why that's being removed, and I wasn't able to find what is removing it yet..

**Comment by moollaza** [comment]
> The code example displays constexpr const_iterator cend const; whereas the expected code snippet is constexpr const_iterator cend() const;.

We'll have to investigate this further -- oddly our database has the `()` in the text, so we're not stripping out in the processing of the output.txt -- I'm not sure where or why that's being removed, and I wasn't able to find what is removing it yet..

**Comment by p12tic** [comment]
@moollaza: I've updated the PR and think it's good to go. Could you please review it?

**Comment by p12tic** [comment]
@ManrajGrover Ping :-)

**Comment by ManrajGrover** [comment]
@p12tic I'll review it ASAP. Thank you for pinging. 😄

**Comment by ManrajGrover** [comment]
Hi @p12tic, 😄 

This looks good to me apart from stripping of parenthesis. Since it is important to fix it, I believe we should fix the cause of it before moving ahead with this.

**Comment by p12tic** [comment]
@ManrajGrover: The currently live fathead has the same issue; this PR does not make matters worse.

**Comment by ManrajGrover** [comment]
@p12tic True! Just thinking if we could fix it in this PR itself as syntax is something people search for and this is something that would require urgent addressing for the same reason.

**Comment by p12tic** [comment]
Updated with possible work around. Let's see how beta looks like.

**Comment by p12tic** [comment]
@ManrajGrover, @moollaza: It looks like this parentheses bug is impossible to work around properly, because the internal duckduckgo parser ignores whitespace characters (even various Unicode space characters) between otherwise empty parentheses. For the time being, I've inserted `void` between the parentheses. The syntax is not fully valid C++, but it's better than the previous situation.

**Comment by p12tic** [comment]
@ManrajGrover, @moollaza: Is there anything else I could do in order to speed up this PR? Holding back the PR for an unrelated bug makes it worse for everyone, because the old content no longer matches the current website. E.g. searching for `cpp experimental dynarray` will bring a broken link. This is only one example I remember right now, there are lots of such cases.

If this delay is because of the fathead not following DuckDuckGo guidelines of maintaining all code within this repository, I have good news :-) I figured a sensible way of tracking all the parsing code in this repo that is maintainable long term. I will do a PR as soon as this PR lands.

**Comment by p12tic** [comment]
@ManrajGrover, @moollaza: Ping :)

**Comment by ManrajGrover** [comment]
@p12tic Would love to hear from a DDG Staff member regarding this

**Comment by p12tic** [comment]
Ping @pjhampton, @tagawa, @moollaza . Could someone shed some light on how should I proceed? Thank you!

**Comment by moollaza** [comment]
Sorry for the delay and thanks! This LGTM :+1:

**Comment by p12tic** [comment]
Thanks!

**Pull request merged**
