### PR TITLE
AppleDocsMacOS: Remove unnecessary iOS referrences

### PR DESCRIPTION
**Pull request by sahildua2305**
/cc @jagtalon

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jagtalon** [comment]
@sahildua2305 nice! Please update the default path to be "/Applications/Xcode.app/Contents/Developer/Documentation/DocSets/com.apple.adc.documentation.OSX.docset/Contents/Resources/docSet.dsidx" though instead of your home directory.

Thank you!

**Comment by sahildua2305** [comment]
@jagtalon Ah! yes! I noticed it just after pushing (and left for dinner then). I'll fix this.

**Comment by jagtalon** [comment]
LGTM!

**Pull request merged**
