### PR TITLE
Perl6doc unbreak

### PR DESCRIPTION
**Pull request by pfirsichbluete**
perl6doc uses <br> within code blocks. But according to

  https://github.com/duckduckgo/zeroclickinfo-fathead/pull/116#issuecomment-76443652

this seems undesired and \n should be used instead. Since perl6doc is somewhat a reference fathead,
trying to move it from "<br> within code blocks" to "\n within code blocks".

However, the documentation format of doc.perl6.org no longer matches this fathead's parser. So I am updating the parser beforehand, and while I am at it fixing some historic hiccups with it.

### CODE REVIEW

**Comment by moollaza** [comment]
@pfirsichbluete thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by jdorweiler** [comment]
@pfirsichbluete looks like there should be another `:` after the `X` in these titles so that their disambiguation links properly.  The highlighted tile should be `X::Proc::Async::MustBeStarted.method`


selection_383

**Comment by pfirsichbluete** [comment]
@jdorweiler: Thanks!

> looks like there should be another : after the X in these titles so that their disambiguation links properly.

I added the third colon to the top-level scope operator of links in disambiguation pages in 86bae99f62bc265f4bdd9ab58c8bdaafab32f9a3 .


Thereby disambiguation switched from

```
method D  [...]  *[[X::Method::InvalidQualifier.method]], returns [...].\n*[[X::Method::NotFound.method]], returns [...]
```

to

```
method D  [...]  *[[X:::Method::InvalidQualifier.method]], returns [...].\n*[[X:::Method::NotFound.method]], returns [...]
                       ^                                                         ^
                       |                                                         |
                 additional colon                                          additional colon
```

Since I cannot reproduce on my end ... are further colons needed elsewhere too?

**Comment by jdorweiler** [comment]
@pfirsichbluete sorry, for the delay.  It looks like the colon is being stripped from the title somewhere on the backend.  Could you revert back to the previous commit with two colons?  Your data looks good so there's no reason to keep this PR waiting.

**Comment by pfirsichbluete** [comment]
> Could you revert back to the previous commit with two colons?

@jdorweiler: Sure.

Done.

Pull Request is again at 9241dc98c1ae98685aad1b3a967c6edea0f4f495 which is the commit with 2 colons.

**Comment by jdorweiler** [comment]
@pfirsichbluete Thanks looks good.  I'll merge this and make an internal issue for the colons.

**Pull request merged**
