### PR TITLE
Improving mdn_css Fathead

### PR DESCRIPTION
**Pull request by moollaza**
### Changes:
- Make PerlCritic happpy
- Reduce code nesting
- Use subs for common functions
- Added support for code snippets in descriptions
- Ensure lowercased, cleaned article titles
- Create redirects as necessary (e.g. CSS functions with `()` in title)

### TODO:
- [ ] Properly handle units of `<length>` -- @hchienjo is working on this in #284 
   - Each unit has a `<dt id=$unit_name>` that needs to be parsed instead of page title/description
- [ ] Are there other pages like these? We need to investigate! -- @hchienjo is working on this in #284 
 - Look for pages that have the same URL
- [x] Some pages have `<a>` after `<h2 id="Syntax">` -- this is causing issues for code snippets
 - Now fixed in this PR using a better selector: '#Syntax ~ pre'
- [ ] Parse "In This Article" sidebar, create `external-links` array -- @hchienjo is working on this in #284 
- [ ] Parse out "Initial Value" where applicable

/cc @hchienjo 

This is still a work in progress. Feedback welcome.

https://duck.co/ia/view/mdn_css

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@hchienjo there's definitely lots of work left to get this IA working as well as it can! Would you be interested in tackling some of this?

**Comment by hchienjo** [comment]
Yes I am.

**Comment by hchienjo** [comment]
Do I submit another pull request so that I can be aided in making the proposed changes?

**Comment by hchienjo** [comment]
Also, I would like to recommend the use of [Carton](https://metacpan.org/pod/Carton) for module
management so make dependency management seamless.

I have began using it on my [end](https://github.com/hchienjo/zeroclickinfo-fathead/tree/zaahir/improve-mdn-css/lib/fathead/mdn_css)

What do you think?

**Comment by hchienjo** [comment]
Fetching of external links has been implemented from [here](https://github.com/hchienjo/zeroclickinfo-fathead/commit/7e5327b23e4fbb4bc0a82396d7b2cdb744cecc93) to [here](https://github.com/hchienjo/zeroclickinfo-fathead/commit/bedd62275cd998f5f2f20f36a6c4cf43b908027e).

@moollaza Please review... Thanks.
Working on the other features.

**Comment by hchienjo** [comment]
@moollaza I tried to get rid if the `<a>` after `<h2 id="Syntax">` over [here](https://github.com/hchienjo/zeroclickinfo-fathead/commit/7829bc86a0f5e0301cebd602bd5e0e681672f677). Is that what you meant?

**Comment by hchienjo** [comment]
@moollaza for the `length` issue,  does it mean that we ignore its definition and parse each unit into its own title/description? Or, the units will be combined into the description of `length`?

**Comment by moollaza** [comment]
@hchienjo sorry for the delay, I was away this past week.

> @moollaza I tried to get rid if the <a> after <h2 id="Syntax"> over here. Is that what you meant?

I believe I've solved the problem of the `<a>` with my updated selector -- I'll take another look to confirm

> for the length issue, does it mean that we ignore its definition and parse each unit into its own title/description?

Yes! We should probably inspect the link to see if it goes to a page anchor (instead of a top level page) and in that case we'll need to parse out the description for "length" within the page to make the `length` result correct and unique.

**Comment by hchienjo** [comment]
@moollaza I am working on it right now! Great to have you back!

**Comment by moollaza** [comment]
> Also, I would like to recommend the use of Carton for module
> management so make dependency management seamless.
> 
> I have began using it on my end
> 
> What do you think?

Yes! This is awesome 💯  -- Carton will definitely simplify things 👍

**Comment by hchienjo** [comment]
Found the following that have the same case as the `length` one. Working on them.

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#matrix3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant#styleset()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#translateY()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#translateZ()
https://developer.mozilla.org/en-US/docs/Web/CSS/url#The_url()_functional_notation
https://developer.mozilla.org/en-US/docs/Web/CSS/angle#grad
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#scaleX()
https://developer.mozilla.org/en-US/docs/Web/CSS/time#s
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#scaleY()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#px
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#skewX()
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#grayscale()
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#brightness()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#vmin
https://developer.mozilla.org/en-US/docs/Web/CSS/length#rem
https://developer.mozilla.org/en-US/docs/Web/CSS/length#pc
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#format()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#ex
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#scale3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/frequency#khz
https://developer.mozilla.org/en-US/docs/Web/CSS/length#pt
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#rotate3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/angle#turn
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant#character-variant()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#in
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#perspective()
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgba()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#translate3d()
https://developer.mozilla.org/en-US/docs/Web/CSS/frequency#hz
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#scaleZ()
https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/Selectors#Information_Selectors_based_on_relationships
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#rotate()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#cm
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#drop-shadow()
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#hue-rotate()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#rotateY()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#mm
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#invert()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#translateX()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#ch
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#blur()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#vh
https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#dppx
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#translate()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#vw
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant#swash()
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#sepia()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#skewY()
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#scale()
https://developer.mozilla.org/en-US/docs/Web/CSS/angle#rad
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant#stylistic()
https://developer.mozilla.org/en-US/docs/Web/CSS/image#The_image()_functional_notation
https://developer.mozilla.org/en-US/docs/Web/CSS/length#vmax
https://developer.mozilla.org/en-US/docs/Web/CSS/length#em
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-variant#ornaments()
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#contrast()
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#saturate()
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#hsla()
https://developer.mozilla.org/en-US/docs/Web/CSS/length#q
https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#dpcm
https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#dpi
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#hsl()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#skew()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#rotateX()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#matrix()
https://developer.mozilla.org/en-US/docs/Web/CSS/time#ms
https://developer.mozilla.org/en-US/docs/Web/CSS/filter#opacity()
https://developer.mozilla.org/en-US/docs/Web/CSS/angle#deg
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#local()
https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function#rotateZ()
https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates#annotation()

**Comment by moollaza** [comment]
> Fetching of external links has been implemented from here to here.
> 
> @moollaza Please review... Thanks.
> Working on the other features.

@hchienjo I'm going to merge this code for now. Please make PR's for your changes so I can review and provide feedback.

If you'd prefer, I can make a new "mdn_css" branch for us to work against so we're not bothering with Master for now? Happy either way.

**Comment by hchienjo** [comment]
@moollaza I have a branch that I am working right now, let me submit a PR and then we
can synchronize the work together.

**Comment by hchienjo** [comment]
@moollaza Here it [is](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/284).

**Comment by moollaza** [comment]
Merging this as it's working well. Will continue with any improvements over in #284

**Pull request merged**
