### PR TITLE
Can i use: allow plural search

### PR DESCRIPTION
**Pull request by alexnewmannn**
## Description of new Instant Answer, or changes
https://duck.co/ia/view/caniuse does not allow searches for non-plural terms, like css filter as mentioned in https://github.com/duckduckgo/zeroclickinfo-fathead/issues/171 I've never used python, or many backend languages to be honest, however, this seemed the most logical way. Do a regex lookup for anything ending in an `s` and create a keyword without that `s`; also works for other searches like `serviceworker`

## Related Issues and Discussions
Fixes https://github.com/duckduckgo/zeroclickinfo-fathead/issues/171

## People to notify

Not sure who's best to notify, however, original issue was reported by @jagtalon and spoke to @pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [x] Uniformly indented, well commented
- [x] Fetch.sh and Parse.sh run without errors
- [x] Output contains no blank lines, or multi-line entries
- [x] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/caniuse

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@alexnewmannn thanks for contributing. Unfortunately this isn't the right approach, and the correct solution is much simpler, and doesn't require any coding :)

We have a list of all the article titles in that articles.txt file.

We need to create a `redirect.txt` file, which is a simple comma delimited file.

This file should be manually composed, and will map singular form phrases to the existing plural form.

e.g.

```
singular form1,plural form1
singular form2,plural form2
...
```

There are many examples of redirect.txt files in the repo, and doc.duckduckhack.com should provide further details as well

**Comment by alexnewmannn** [comment]
Ah-ha I see, I was hoping there'd be an easier way, I'll take a look and get this sorted 👍

**Comment by pjhampton** [comment]
Hey @alexnewmannn!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
