### PR TITLE
Test PR, ignore

### PR DESCRIPTION
**Pull request by jdorweiler**
---
https://duck.co/ia/view/template_comments

### CODE REVIEW

**Comment by mrshu** [comment]
Description: 
Example Query: 
Tab Name: 
Source:

**Comment by daxtheduck** [comment]
Description: testing template comments
Example Query: some example query
Tab Name: Software
Source: www.wikipedia.org

**Comment by jdorweiler** [comment]
Looks like it works
:cactus:

**Comment by MariagraziaAlastra** [comment]
:cactus:

**Comment by daxtheduck** [comment]
Automated data from [IA page](https://duck.co/ia/view/template_comments)

---
**Description**: testing template comments
**Example Query**: some example query
**Tab Name**: About
**Source**: www.duckduckgo.com

**Comment by jdorweiler** [comment]
works again! :cactus:

**Comment by daxtheduck** [comment]
Automated data from [IA page](https://duck.co/ia/view/template_comments)

---
**Description**: testing template comments
**Example Query**: some example query
**Tab Name**: About
**Source**: duck.co

**Comment by daxtheduck** [comment]
Automated data from [IA page](https://duck.co/ia/view/template_comments)

---
**Description**: testing template comments
**Example Query**: some example query
**Tab Name**: About
**Source**: duck.co

**Comment by jdorweiler** [comment]
:cactus:

**Comment by daxtheduck** [comment]
Automated data from [IA page](https://duck.co/ia/view/template_comments)

---
**Description**: testing template comments
**Example Query**: some example query
**Tab Name**: About
**Source**: duckduckhack.com

**Comment by jdorweiler** [comment]
:cake:

**Comment by daxtheduck** [comment]
## Instant Answer Metadata from [IA page](https://duck.co/ia/view/template_comments)

**Description**: testing pr template posted to comment

**Example Query**: example query 1, another example query

**Tab Name**: About

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/template_comments)*

---
**Testing**

**Browsers**
- [ ] safari
- [ ] firefox
- [ ] ie
- [ ] opera
- [ ] chrome


**Mobile**
- [ ] android
- [ ] ios


---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/template_comments)*

**Comment by daxtheduck** [comment]
## Instant Answer Metadata from [IA page](https://duck.co/ia/view/template_comments)

**Description**: testing pr template posted to comment

**Example Query**: example query 1, another example query

**Tab Name**: About

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/template_comments)*

---
**Testing**

**Browsers**
- [ ] safari
- [ ] firefox
- [ ] ie
- [ ] opera
- [ ] chrome


**Mobile**
- [ ] android
- [ ] ios


---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/template_comments)*

**Comment by daxtheduck** [comment]
## Instant Answer Metadata from [IA page](https://duck.co/ia/view/template_comments)

**Description**: testing pr template posted to comment

**Example Query**: example query 1, another example query

**Tab Name**: About

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/template_comments)*

---
**Testing**

**Browsers**
- [ ] safari
- [ ] firefox
- [ ] ie
- [ ] opera
- [ ] chrome


**Mobile**
- [ ] android
- [ ] ios


---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/template_comments)*

**Comment by daxtheduck** [comment]
## [Template_comments](https://duck.co/ia/view/template_comments)

**Description**: testing pr template posted to comment

**Example Query**: [example query 1](https://beta.duckduckgo.com/?q=example query 1)

**Tab Name**: About

**Source**:  

*These are the important fields from the IA page.  Please check these for errors or missing information and update the [IA page](https://duck.co/ia/view/template_comments)*

---
*This is an automated message which will be updated as changes are made to the [IA page](https://duck.co/ia/view/template_comments)*

**Pull request closed without merging**
