### PR TITLE
CanIUse: Switch to new Fathead Template Elements

### LINKED ISSUE #422: CanIUse: Switch to use new Fathead Template Elements
We now have [Fathead Template Elements](https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract) designed specifically for Programming Fatheads. These are HTML elements that should be added to the output.txt by each Programming Fathead's parsing script(s).

This Fathead should be updated to use the templates:
- The entire abstract should be wrapped in a `<section>` with class `prog__container`
- Any text before/after the code blocks must be wrapped in `<p>` tags
- Any subheadings should be wrapped in a `<span>` with class `prog__sub`

Here is an example:

``` html
<section class="prog__container">
    <p>Creates a JavaScript Date instance that represents a single moment in time.</p>
    <pre>
        <code>
            new Date;
            new Date(value);
            new Date(dateString);
            new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
        </code>
    </pre>
    <span class="prog__sub">Return Value</span>
    <p>The removed element.</p>
</section>
```

---

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [CSS related searches](https://forum.duckduckhack.com/t/css-search-overview)!

---

IA Page:  http://duck.co/ia/view/caniuse 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @csytan

### PR DESCRIPTION
**Pull request by sahildua2305**
## Description of new Instant Answer, or changes

Switch to new Fathead Template Elements

## Related Issues and Discussions

Fixes #422 

## People to notify

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/caniuse

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@sahildua2305 I'm getting errors when trying to run the parser -- they aren't related to your changes, but are you able to run the scripts?

**Comment by moollaza** [comment]
looks like we need `from bs4` instead of `from BeautifulSoup` ? -- Perhaps the rest of the parsing scripts need to be updated for bs4?

**Comment by sahildua2305** [comment]
Looks like it should be `from beautifulsoup4` instead.

**Comment by moollaza** [comment]
> Looks like it should be from beautifulsoup4 instead.

@sahildua2305 that still gives me an error. In the BS4 docs they show `from bs4 import BeautifulSoup`. When I switch it to `bs4` the code runs, but I see other errors later in the processing:

```
Traceback (most recent call last):
  File "parse.py", line 160, in <module>
    main()
  File "parse.py", line 16, in main
    answers = generate_answers(data)
  File "parse.py", line 61, in generate_answers
    abstract += '<p><b>Notes:</b> {}</p>'.format(bs.renderContents())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 90: ordinal not in range(128)
```

**Comment by samskeller** [comment]
@moollaza @sahildua2305 the import works for me -- I'm using Python 2.7.10 and `BeautifulSoup==3.2.1`

However, I do get that UnicodeDecodeError you're getting, @moollaza -- I think I have a fix that involves basically trying to use Unicode strings everywhere until the end when everything is being written out to a file -- let me know if you want me to commit it to this PR or somewhere else or @sahildua2305 if you wanted to work on it (I just jumped the gun because it looks like it was my fault originally :) )

**Comment by samskeller** [comment]
@moollaza I'm actually not sure on the best way to add my changes -- is there a good way to add them to this PR? Or do I need to open up my own?

**Comment by sahildua2305** [comment]
@samskeller you can create a PR to this branch.

**Comment by tagawa** [comment]
@samskeller If it helps, there's an explanation of how to send a PR to somebody else's fork here: https://duck.co/blog/post/320/weekly-update-112-scratching-your-own-itch#tip

**Comment by samskeller** [comment]
@tagawa thanks for the very helpful article! And sorry it took me so long to do this @sahildua2305. I've submitted my changes in this PR: https://github.com/sahildua2305/zeroclickinfo-fathead/pull/1/files

Take a look and let me know what you think!

**Comment by moollaza** [comment]
@sahildua2305 @samskeller Thanks! This LGTM :+1:

I just noticed a few bugs with this, but they can be solved later. I'll open up a new issue 👍

**Pull request merged**
