### PR TITLE
Apple Docs

### PR DESCRIPTION
**Pull request by jagtalon**
Introduction:
-------------
This is used to open an SQLite database that's installed on your computer to create a Fathead output
that's specified in http://docs.duckduckhack.com/resources/fathead-overview.html

See: https://forum.duckduckhack.com/t/improve-apple-os-x-macos-documentation/240

Page Structure:
---------------
There is no page structure here because we're essentially scraping a database. The only requirement is that you have XCode.

Pipeline:
---------
Read DB -> Scrape / Process -> Output

How do I test this?
-----
You'll need to have XCode installed on your computer. It comes bundled with the documentation that we need.

Screenshots:
---
screen shot 2016-07-28 at 2 29 43 pm
screen shot 2016-07-28 at 2 29 58 pm

IA Page: https://duck.co/ia/view/appledocs

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jagtalon** [comment]
@jdorweiler @zachthompson @MariagraziaAlastra This should be ready for review! Tested on duckpan:

screen shot 2016-07-28 at 2 29 43 pm

screen shot 2016-07-28 at 2 29 58 pm

**Comment by jdorweiler** [comment]
I get this error when I try running it. 
```
Traceback (most recent call last):
  File "parse.py", line 104, in <module>
    create_fathead(ios, 'iOS')
  File "parse.py", line 54, in create_fathead
    conn = sqlite3.connect(database)
sqlite3.OperationalError: unable to open database file
```

**Comment by jdorweiler** [comment]
Can you add a README?

**Comment by jagtalon** [comment]
@jdorweiler you'd need the SQLite files on your system (which is distributed by XCode https://github.com/duckduckgo/zeroclickinfo-fathead/blob/ba829298c91c26502f276048a9567b27ff29cf72/lib/fathead/apple/parse.py#L32..L33)

**Comment by jagtalon** [comment]
@jdorweiler I meant this https://github.com/duckduckgo/zeroclickinfo-fathead/blob/ba829298c91c26502f276048a9567b27ff29cf72/lib/fathead/apple/parse.py#L1 to be the README but probably having an actual README.md is better thanks!

**Comment by jagtalon** [comment]
@jdorweiler added a readme!

**Comment by jdorweiler** [comment]
Can you change the directory name to "ios" to match the metadata ID.

**Comment by jdorweiler** [comment]
Installed on beta. Check it out and let me know what you think. 
https://beta.duckduckgo.com/?q=ios+ABSourceType&atb=v23&ia=about&iax=1

**Comment by jagtalon** [comment]
@jdorweiler Renamed the directory and added a new IA Page!

**Comment by jdorweiler** [comment]
Ok, installed on beta again. Use the trigger word `appledocs` so you can distinguish your data from the existing ios fathead. Just for testing. We can give it better trigger words when it's ready. 
https://beta.duckduckgo.com/?q=appledocs+ABSourceType&atb=v23&ia=about

**Comment by jdorweiler** [comment]
:+1:

**Comment by jagtalon** [comment]
<3

**Pull request merged**
