### PR TITLE
New Angular.js Fathead

### LINKED ISSUE #471: JavaScript: Create New AngularJS Fathead
# AngularJS Fathead

Contribute to DuckDuckGo!

screen shot 2016-10-21 at 16 36 35
### What you will need to know?

Either **JavaScript**, Python, Ruby, or Perl for Fatheads. Bash is also useful. You will download the reference source and create an **output.txt** file containing the parsed documentation. Read more about Fatheads here: 
https://docs.duckduckhack.com/resources/fathead-overview.html
### The source :rocket:

https://docs.angularjs.org/api
#### Update Search Json contains partial url for the API source files

https://docs.angularjs.org/js/search-data.json

Example:
path: "api/ng/function/angular.merge",
https://docs.angularjs.org/partials/api/ng/function/angular.merge.html
### The goal

Help _[improve JavaScript language search results](https://forum.duckduckhack.com/t/javascript-search-overview)_ on DuckDuckGo as part of our Programming Mission! We're trying to reach 100% Instant Answer (IA) coverage for JavaScript-related searches by creating new Instant Answers or improving existing ones.

Code to some relevant examples:
- [jQuery Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/jquery)
- [NodeJS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/node_js)
- [MDN JS Reference](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/master/lib/fathead/mdnjs)

**Fathead Example (jQuery Reference)**

screen shot 2016-10-21 at 17 06 36
### The steps

- [x] Claim this issue (Comment Below)
- [ ] Please review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] Set up codio environment (See: https://docs.duckduckhack.com/welcome/setup-dev-environment.html) and fork this repository
- [x] Create the Fathead (https://duck.co/ia/view/angularjs)
- [ ] Create a PR
- [ ] Ping @bfmags for a review
### Questions?
- [Documentation](https://docs.duckduckhack.com/)
- [The Forum](https://forum.duckduckhack.com/c/programming/javascript)
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) 
- Ping one of the [Community Leaders](https://duck.co/help/community/community-leaders) or @bfmags

---

Instant Answer Page: https://duck.co/ia/view/angularjs

_Thanks to @pjhampton for the template_

### PR DESCRIPTION
**Pull request by rafaelpadovezi**
New AngularJS Fathead

## Description of new Instant Answer, or changes
AngularJS Reference

## Related Issues and Discussions
Fixes #471 
(Create New AngularJS Fathead)

## People to notify
@bfmags

---

Instant Answer Page: https://duck.co/ia/view/angularjs

### CODE REVIEW

**Comment by daxtheduck** [comment]
@rafaelpadovezi Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
Hey @rafaelpadovezi thanks, just deployed to beta: [angular.forEach](https://beta.duckduckgo.com?q=angular.forEach&t=ho&ia=about) :smile:

**Comment by MariagraziaAlastra** [comment]
@bfmags @moollaza Doing any testing on beta? The latest changes are there. If this looks good I'd like to merge and release it

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra Just a second. Testing the beta I saw a bug with hiperlinks.

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi No rush, this should be tested throughly. Thanks!

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi Just deployed the latest changes to beta :smile:

**Comment by bfmags** [comment]
@rafaelpadovezi Great job! :)

screen shot 2016-11-16 at 08 08 34

@rafaelpadovezi @MariagraziaAlastra testing [angular.forEach](https://beta.duckduckgo.com?q=angular.forEach&t=ho&ia=about)

*  the 'more at' line is missing the Angular website

* redirects like 'angular for each' and 'angular forEach' don't seem to be triggering 

________________
    forEach	R	angular.forEach										
    for each	R	angular.forEach

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra Can you deploy to beta again? I made some changes and want to test the result.

@bfmags Can these 2 problems be fixed by me?

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi Just deployed to beta, thanks 😄

**Comment by bfmags** [comment]
@rafaelpadovezi output.txt file has all the data and seems to be correct :confused:

**Comment by rafaelpadovezi** [comment]
@bfmags I updated the IA page, what I think that solves the "more at" problem.
image

Also, it looks like the redirects are working.

**Comment by bfmags** [comment]
@rafaelpadovezi yes, it's all sorted! 😄 👍

**Comment by daxtheduck** [comment]
@rafaelpadovezi this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Comment by tagawa** [comment]
Hi @rafaelpadovezi. Just wanted to let you know this is now live on DuckDuckGo!
https://duckduckgo.com/?q=angularjs+ng-repeat&ia=about

You can also see a chart showing coverage and engagement in the forum topic:
https://forum.duckduckhack.com/t/angularjs-fathead-1-x/994

Thanks again for creating this for JS developers 😃

**Pull request merged**
