### PR TITLE
Delete appledocs

### LINKED ISSUE #315: Apple Docs: Split the instant answer to two Fatheads
Currently it's putting both APIs of iOS and macOS in one file. This means it's not easy to trigger something with "ios" or "osx" because they're showing the same IA. A good way to solve this is to split it in two. If we're going to add a new set of APIs like tvOS #314, that would go in another separate IA as well.

---

IA Page: https://duck.co/ia/view/appledocs

### PR DESCRIPTION
**Pull request by jagtalon**
Changes:
- Splits it into two IAs because the triggers are different for each, e.g., "ios nsstring" should show apple_docs_ios and "osx nsstring" should show apple_docs_macos. Fixes #315 

https://duck.co/ia/view/appledocs

See https://github.com/duckduckgo/zeroclickinfo-fathead/pull/354 and https://github.com/duckduckgo/zeroclickinfo-fathead/pull/355

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jagtalon** [comment]
Ready for review!

**Comment by jagtalon** [comment]
Also needed:
- Deprecate https://duck.co/ia/view/appledocs
- Probably drop the tables.

**Comment by moollaza** [comment]
@jagtalon Thanks! This LGTM :+1:

**Comment by moollaza** [comment]
@jdorweiler how do we delete a Fathead?

/cc @MariagraziaAlastra

**Comment by moollaza** [comment]
Made a task internally. We can discuss there 👍

**Pull request merged**
