### PR TITLE
PHP: Make PHP parser load any file that isn't a class

### LINKED ISSUE #616: PHP: Improve parser to cover more of the documentation and create redirect entries
### Description

We've added the names of all PHP Functions to the `cover/` directory, and after running the test, it reported that over 18,000 functions from our coverage are missing in the output.txt.

We need to investigate why the output only contains approximately 4000 articles, and update the parser to grab the missing 14,000 articles.

We also need to create redirects appropriately so that our output.txt also satisfies our coverage data. It may be that our coverage data needs to be modified, but that should be a last resort.

## People to notify
@VitorVRS @gautamkrishnar 

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/php

### PR DESCRIPTION
**Pull request by ioanmoldovan**
## Description of new Instant Answer, or changes
This PR makes the PHP parser look at every file inside phpdoc except ones that contain the word class in the name. Also every file that doesn't start with "class" is checked to see if it contains the word "methodname", to further make sure it isn't a class/object/attribute.
If it passes all tests, the html file is parser generating output.txt

## Related Issues and Discussions
Fixes #616 

## People to notify
@moollaza

------------------

IA Page: https://duck.co/ia/view/php

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@ioanmoldovan please push the updated `output.txt` to the pull request. It will then be deployed automatically to Beta.duckduckgo.com for testing 👍

**Comment by gautamkrishnar** [comment]
Looking good... Lets see the output... Please push `output.txt`

**Comment by moollaza** [comment]
@ioanmoldovan Happy New Year! Whenever you have a chance, please push the `output.txt` file to your PR so that this can be installed to Beta for testing and merge!

**Comment by ioanmoldovan** [comment]
@moollaza I'm sorry but I can't do that, due to a few technical issues (no longer have modified the repo in my Github and I'm not even sure how to do that), can someone else please put the output.txt?

**Comment by bfmags** [comment]
@moollaza @ioanmoldovan I think we'll have to create a [new PR](https://github.com/isaacs/github/issues/168), since you have only 1 commit it will be easy to recreate it by cloning master, and [cherry-picking](http://think-like-a-git.net/sections/rebase-from-the-ground-up/cherry-picking-explained.html) your commit `git cherry-pick f5c723eb95dd3d84b14c3907e728411d7ec7567f` into a new branch

**Pull request closed without merging**
