### PR TITLE
PerlDoc: Add categories

### LINKED ISSUE #321: PerlDoc: Improve assigned categories
As mentioned in https://github.com/duckduckgo/zeroclickinfo-fathead/pull/247#discussion_r75753147 we should be using more specific categories.

While fixing that, we should add some categories for the following:

- Variables
   - For each sub-section in http://perldoc.perl.org/perlvar.html we should have a category, e.g, `General Variables`, `Error Variables` etc.
- Functions
  - We could use the categories on http://perldoc.perl.org/index-functions-by-cat.html to add more specific categories.
- Operators
   - We could use some of the sections in http://perldoc.perl.org/perlop.html to categorize the operators, eg., `Additive Operators`, `Equality Operators`.

------
IA Page:  http://duck.co/ia/view/perl_doc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @duckduckgo

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Adds categories to perl_doc, fixes #321.

### Notes

- `Perl Error Variables` (category) may clash with `Error Variables` (FAQ article).

cc @jbarrett 

---
IA Page: https://duck.co/ia/view/perl_doc
Maintainer: @GuiltyDolphin

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@jbarrett Any pressing issues with this?

**Comment by moollaza** [comment]
@GuiltyDolphin I'll take a look 👍

**Comment by jbarrett** [comment]
Sorry @GuiltyDolphin - this slipped through the cracks somehow :frowning:

**Comment by moollaza** [comment]
@GuiltyDolphin this should be live on Beta now -- can you try some queries to confirm?

**Comment by GuiltyDolphin** [comment]
@moollaza 

https://beta.duckduckgo.com/?q=perl+variables&ia=list :+1:

https://beta.duckduckgo.com/?q=perl+glossary&ia=list :+1:

https://beta.duckduckgo.com/?q=perl+functions&ia=list :+1:

Seems pretty good.

**Comment by moollaza** [comment]
@GuiltyDolphin thanks 👍 

Our tile view sorting looks kinda broken, but that's an internal bug:

perl_variables__perl_5__at_duckduckgo

This LGTM :+1:

**Comment by moollaza** [comment]
Yeah, definitely some bugs with our tile view sorting...

perl_glossary__perl_5__at_duckduckgo

**Comment by moollaza** [comment]
Going to hold off on releasing this to Production until the team can investigate the broken topic links/sorting here

**Pull request merged**
