### PR TITLE
New PHP FatHead

### PR DESCRIPTION
**Pull request by sahildua2305**
This is PHP FatHead (work in progress)

https://duck.co/ia/view/php_doc

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
👍

**Comment by davidofferman** [comment]
I'm wondering how the progress on this is going? I was looking into taking on this project until I saw this PR.

I was going to use SVN to download the repository at http://svn.php.net/repository/phpdoc/en/trunk/. It has a folder called "reference" that lists all functions, parameters, etc. Probably a lot easier to parse that than the HTML manuals.

**Comment by alohaas** [comment]
@davidofferman that's a cool idea! I think @moollaza and @sahildua2305 would love more input like this!

Also, do you know about the forum for our open source community? Along with GitHub, it's the best place to see what programming-related instant answers the community is focusing on and where you can discuss ideas like yours above. 
Check it out here: https://forum.duckduckhack.com/

**Comment by sahildua2305** [comment]
@davidofferman That's a great idea. I was too much involved in other work that I forgot to work on this. I'll get back to this soon.

**Comment by moollaza** [comment]
A PR for a new Fathead has been opened: #399

**Pull request closed without merging**
