### PR TITLE
Redirects for Flask fathead

### PR DESCRIPTION
**Pull request by shanmbic**
Hey @pjhampton !! I have added the redirects by modifying the parser. Please have a look at it suggest any improvements . Thanks :)  

Issue : #817 

---
IA Page: https://duck.co/ia/view/flask

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@shanmbic it looks like this is un-mergable due to some conflicts. Can you please fix?

**Comment by shanmbic** [comment]
Hey @moollaza !! Done :)

**Comment by pjhampton** [comment]
Thanks @shanmbic 💛

**Pull request merged**
