### PR TITLE
Revert "Swift Docs: Readme updated and url changed from 2.2 to 3.1"

### PR DESCRIPTION
**Pull request by moollaza**
Reverts duckduckgo/zeroclickinfo-fathead#768

Unfortunately the page anchor URLs are too long and our database has a limit of 500 characters.

Several are over 1000 characters!

We should speak to swift doc about using more sensible URLs

/cc @pjhampton

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
After reading http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers#417184 it seems like technically urls under 2K characters are OK. 

I will see if we can raise our character limit to 2K so we can use swiftdocs.com

**Comment by pjhampton** [comment]
👀  This surprises me, @moollaza 
Let's keep 2.2 but keep this sitting here for a while. I can reach out to them

**Comment by adityatandon007** [comment]
@moollaza that sounds great . Increasing the URL length to 2k is good because we don't want to show user older docs 3.1 is a major version release if in case it was a minor release then perhaps we can stick to 2.2 but since it's not we must increase our URL length :smile

**Comment by moollaza** [comment]
I've made a task to increase our URL length limit. After that I should be able to re-install this updated Fathead 👍

**Pull request merged**
