### PR TITLE
add python functions

### PR DESCRIPTION
**Pull request by jdorweiler**
Add function coverage for Python.

Instant Answer Page: https://duck.co/ia/view/python

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
I think `functions.txt` should be within a `cover` directory.

**Comment by jdorweiler** [comment]
Thanks @tagawa 
How does it look @jbarrett?

**Comment by MariagraziaAlastra** [comment]
Works!
 https://beta.duckduckgo.com/?q=python+print+function&ia=about
screen shot 2016-12-15 at 2 39 40 pm

**Pull request merged**
