### PR TITLE
How Products Are Made fathead

### PR DESCRIPTION
**Pull request by marcantonio**
**What does your Instant Answer do?**
References How Products Are Made (http://www.madehow.com) for information on how different products are manufactured.  This was initial proposed [here](https://duck.co/ideas/idea/4750/how-things-are-made).

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It gives you quick info immediately with the option to find out more.

**What is the data source for your Instant Answer? (Provide a link if possible)**
How Products Are Made (http://www.madehow.com)

**Why did you choose this data source?**
It was listed in the initial proposal.  It's a really cool site too.

**Are there any other alternative (better) data sources?**
Not that I know of.

**What are some example queries that trigger this Instant Answer?**
Anything that they have an entry for:
- solar cells
- artificial heart
- fire extinguisher

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
I think this is general reference for the curious.

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
Yes:  https://duck.co/ideas/idea/4750/how-things-are-made

**Which existing Instant Answers will this one supercede/overlap with?**
None that I know of.

**Are you having any problems? Do you need our help with anything?**
Right now it returns the first sentence of the article, per the fathead guidelines.  However, I think it should include a little more.  On the site they have a nice little synopsis for each entry that I think would be perfect.

**Where did you hear about DuckDuckHack? (For first time contributors)**
Looking into DuckDuckGo more closely.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
I can't say exactly as it seems you can't test a fathead with duck pan.

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[] Wrote test file and added to t/ directory
[X] Verified that Instant Answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that Instant Answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
```
/cc @nilnilnil

https://duck.co/ia/view/madehow

### CODE REVIEW

**Comment by moollaza** [comment]
@marcantonio thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by jdorweiler** [comment]
@marcantonio Cool!  I remember looking at that site a while ago and thinking it would make a good instant answer.  

The data is live on this server: https://ddh4.duckduckgo.com/?q=make+optical+fiber&ia=about
Let me know what you think. 
selection_382

**Comment by marcantonio** [comment]
@jdorweiler, That's great!  Two things:

- I noticed you used 'make' as a trigger.  Do I need to include that in the PR?

- Can we include more than one sentence in the result?  The site has a nice little synopsis about each article that we could easily use.

Thanks a lot!

**Comment by jdorweiler** [comment]
>    I noticed you used 'make' as a trigger. Do I need to include that in the PR?

No I'll add in the trigger words on the backend.  Any others you can think of?  I was thinking triggers like "make", "how to make", and "how to build" would be a good start. 

 >  Can we include more than one sentence in the result? The site has a nice little synopsis about each article that we could easily use.

Good idea.  Do you want to grab 3-4 sentences of the synopsis and we can see how it looks?

**Comment by marcantonio** [comment]
I like the triggers you picked.  Maybe add "build" too.

I changed it so that, at most, 3 sentences are pulled in.  Most are only 2-3 anyway.

**Comment by jdorweiler** [comment]
@marcantonio looks good! What do you think?
selection_388
ttps://ddh10.duckduckgo.com/?q=how+to+make+paper&ia=about

**Comment by marcantonio** [comment]
Perfect!

**Comment by jdorweiler** [comment]
@marcantonio looks good to me.  Let's get some design feedback from @abeyang.

**Comment by abeyang** [comment]
Looks good! :+1:

**Comment by jdorweiler** [comment]
@marcantonio Looks good.  What about trying to grab a relevant snippet from the manufacturing process?  It's seems like some are more relevant than others though.

**Comment by jdorweiler** [comment]
@marcantonio This looks good.  I'll make an issue to look  at getting the manufacturing description.

**Comment by marcantonio** [comment]
Thanks @jdorweiler.  I will do my best to take a look at including manufacturing snippets this coming week.

**Comment by jdorweiler** [comment]
@marcantonio  https://duckduckgo.com/?q=make+a+bulletproof+vest&ia=about

**Comment by moollaza** [comment]
@marcantonio Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Comment by marcantonio** [comment]
Thanks a lot guys!  That's awesome!

**Pull request merged**
