### PR TITLE
New Objective-C fathead

### PR DESCRIPTION
**Pull request by shanmbic**
The PR adds the Objective-C fathead.

- Fixes - #718 
- Documentation : https://developer.apple.com/reference/objectivec
- IA Page : https://duck.co/ia/view/objective_c

Hi Guys, This is the initial parsed documentation of Objective-C. Each class, function has a separate page in the documentation (i.e. https://developer.apple.com/reference/objectivec/nsobject/1418815-load). Please review it and suggest changes :) 

---

Instant Answer Page: https://duck.co/ia/view/objective_c

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Hey @shanmbic

This is awesome! Can you please rename the fatheads directory to `objective_c/` please?

**Comment by shanmbic** [comment]
@pjhampton Done :)

**Comment by moollaza** [comment]
@shanmbic this is looking great -- I just wanted to clarify here that you're currently grabbing the Swift code for Apple's Objective-C Framework.

You're off to a great start though and I think we have a very big opportunity to really improve our coverage of Apples documentation.

Currently we have 4 Swift Fatheads: apple_docs_macos, apple_docs_ios, apple_docs_tvos, and apple_docs_watchos.

These are OK, but the triggering needs improvements, and the content needs to be improved to be more useful. For example https://duckduckgo.com/?q=vImageGamma_PlanarF&ia=about should really be talking about https://developer.apple.com/reference/accelerate/1546983-vimagegamma_planarf?language=objc and linking to that

With Xcode 8, the approach we used to build those Fathead will no longer work as the DocSets are no longer separate files that can be found on an Apple machine -- they're built into the Xcode SDK.

This means we need a new approach, and you have now created one.

I propose we deprecate our existing Fatheads and build three new ones:

apple_docs, apple_docs_swift, and apple_docs_objectivec

These first should cover the symbols (classes) for every **Framework**

e.g. https://developer.apple.com/reference/metalperformanceshaders#symbols

Queries like "nsatstypesetter" or "appkit nsatstypesetter", "Protocol WKCrownDelegate"
 should trigger this fathead

The apple_docs_swift Fathead should cover the Swift implementation of the symbols (class method, instance property, type method, etc) for each **Class**

e.g. "MPSUnaryImageKernel encode" should show https://developer.apple.com/reference/metalperformanceshaders/mpsunaryimagekernel/1618873-encode

Likewise apple_docs_objectivec should cover the Objective-C implementation of the symbols for each **Class**

e.g. "objectivec MPSUnaryImageKernel encode" should show https://developer.apple.com/reference/metalperformanceshaders/mpsunaryimagekernel/1618873-encodetocommandbuffer?language=objc

The Swift and Obj-C Fatheads should provide the description, declaration, parameters and return value (as appropriate) as shown in the docs.

---

What do you think about this @shanmbic @pjhampton ?

**Comment by moollaza** [comment]
One other think to note -- Apple has restructured their docs and it's no longer broken down by OS -- rather it's separated by framework -- you can see the more at links from our existing Apple Docs fatheads are redirecting now

**Comment by moollaza** [comment]
@shanmbic any thoughts? Would you be interested in doing this?

**Comment by shanmbic** [comment]
Hey @moollaza ! This looks cool to me . I like the way of structuring the documents i.e. classes for each framework should be stored in a separate fathead and then the symbols should be separated according to the language Swift or Objective-C. So I guess I should start by creating apple_docs fathead , covering the classes for every framework. Should I also merge the current fathead (the objective-c) into it ??

**Comment by moollaza** [comment]
> So I guess I should start by creating apple_docs fathead , covering the classes for every framework. 

@shanmbic sounds good! 

Should I also merge the current fathead (the objective-c) into it ??

Yes please. We should end up with only 3 Fatheads related to Apples Swift/Obj-C Docs 👍

**Comment by moollaza** [comment]
Closing as this will be continued in your new PR(s)

**Pull request closed without merging**
