### PR TITLE
SysctlProcSysKernel

### PR DESCRIPTION
**Pull request by majuscule**
**What does your instant answer do?**

Provides documentation for the files under /proc/sys/kernel on a Linux system.

**What problem does your instant answer solve (Why is it better than organic links)?**

The current organic results for these queries are inconsistent, when then do provide relevant links at all.

**What is the data source for your instant answer? (Provide a link if possible)**

https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/plain/Documentation/sysctl/kernel.txt

**Why did you choose this data source?**

It's the data source to be!

**Are there any other alternative (better) data sources?**

No.

**What are some example queries that trigger this instant answer?**

/proc/sys/kernel/watchdog_thresh
proc sys kernel overflowuid
kernel rtsig-maxnux
linux printk_ratelimit
kexec_load_disabled

**Which communities will this instant answer be especially useful for? (gamers, book lovers, etc)**

Linux!

**Is this instant answer connected to a DuckDuckHack instant answer idea?**

Not to my knowledge.

**Which existing instant answers will this one supercede/overlap with?**

It's the first of it's kind!

**Are you having any problems? Do you need our help with anything?**

Please let me know any/all thoughts you have design-wise.

### CODE REVIEW

**Comment by javathunderman** [comment]
ping @jagtalon

**Comment by jdorweiler** [comment]
@majuscule any interest in picking this back up?  Looks like it was almost done.

**Comment by jdorweiler** [comment]
This pull request is being closed due to inactivity but, if anyone would like to continue it, please @ mention 'duckduckhack-contributors' for help and http://docs.duckduckhack.com/submitting/submitting-overview.html for reference.

**Comment by majuscule** [comment]
Hey, sorry for missing your previous message. My understanding is that this was ready to go though.

**Comment by jdorweiler** [comment]
@majuscule no problem.  I'll reopen and get this on our beta server to test.

**Comment by jdorweiler** [comment]
What words should this trigger on?

**Comment by majuscule** [comment]
Keyword examples are listed in `share/sysctl_proc_sys_kernel/meta.txt`. Additionally, as I no longer have write access on this repository, I am creating a new pull request referencing my forked branch with updated attribution.

**Pull request closed without merging**
