### PR TITLE
Fix #533: Python -  Limit pypi to only popular packages.

### LINKED ISSUE #533: Python: limit pypi to only popular packages
### Description

Limit pypi to only popular packages. 
I've found several cases where pypi shouldn't be showing. The problem is that a pypi package can have any name, which includes things like "lambda", "list".
https://duckduckgo.com/?q=python+lambda&atb=v23&ia=about
https://duckduckgo.com/?q=python+lists&atb=v23&ia=about

Let's limit it to only the first few thousand packages based on popularity from http://pypi-ranking.info/alltime

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/py_pi

### PR DESCRIPTION
**Pull request by souravbadami**
## Description of new Instant Answer, or changes
Limit pypi to only popular packages.

## Related Issues and Discussions
Fixes #533 

## People to notify
@moollaza @jdorweiler 

---

Instant Answer Page: https://duck.co/ia/view/py_pi

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
@souravbadami looks good, just one comment. I installed the new data on the beta server for testing. 

https://duckduckgo.com/?q=python+gevent&t=hu&atb=v23&ia=about

This fixes the weird result for `python lambda`. 
https://duckduckgo.com/?q=python+lambda&t=hu&atb=v23&ia=about

**Comment by souravbadami** [comment]
@jdorweiler -- I can't find any comment in the thread ?

**Comment by jdorweiler** [comment]
:+1:  thanks @souravbadami

**Pull request merged**
