### PR TITLE
MDN CSS: More improvements

### PR DESCRIPTION
**Pull request by moollaza**
- #322 Remove extra newlines from code snippets, use `<ul>` for Initial Value
- #325 Add sorting output.txt to parse.sh so git diffs are easier to read
- #327 Generate new, sorted, output.txt
- #329 Generate new output.txt again, ensure trailing spaces are kept

https://duck.co/ia/view/mdn_css

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by hchienjo** [comment]
@moollaza I will send another PR after this gets merged into master.

**Comment by moollaza** [comment]
@hchienjo merged!

**Comment by hchienjo** [comment]
Awesome!

**Pull request merged**
