### PR TITLE
Added MDN Functions Section

### PR DESCRIPTION
**Pull request by mbad0la**
Fixing #332 [WIP]

**To Do**
* [x] fetch articles from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions
* [ ] when parsing them, include as an abstract at least the first sentence in the article and the syntax; it's better to check the syntax contains more than one word, otherwise it will be useless to show it (see for example the Arguments object article - sometimes it can be very long too, though. In that case we might want to cut it after a double newline, eg for the Arrow functions article
* [x] also include the first example with its description
* [x] generate redirects adding "syntax" and "example - for instance, the Method definitions article could have a "methods syntax" and "methods example" among the redirects to it.

<hr>

IA Page : [https://duck.co/ia/view/mdnjs](https://duck.co/ia/view/mdnjs)
Forum Topic : [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This Pull Request is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

### CODE REVIEW

**Comment by daxtheduck** [comment]
@mbad0laThanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
@mbad0la Thanks, it's on beta!
- [js arguments object](https://beta.duckduckgo.com/?q=js+arguments+object&t=h_&ia=about)
- [js arrow functions](https://beta.duckduckgo.com/?q=js+arrow+functions&t=h_&ia=about)
- [js method definitions](https://beta.duckduckgo.com/?q=js+method+definitions&t=h_&ia=about)
- [js getter](https://beta.duckduckgo.com/?q=js+getter&t=h_&ia=about)

Let me know if you have any questions, nice job so far :smile:

**Comment by mbad0la** [comment]
@MariagraziaAlastra I've made some changes. 
Please check them and deploy this to beta.

**Comment by MariagraziaAlastra** [comment]
@mbad0la Thank you, it's on beta! [js functions rest parameters](https://beta.duckduckgo.com/?q=js+functions+rest+parameters&t=h_&ia=about)

**Comment by moollaza** [comment]
Changes should be live on Beta 👍

**Comment by moollaza** [comment]
@mbad0la @MariagraziaAlastra this Thanks! This LGTM :+1:

**Pull request merged**
