### PR TITLE
New MDN CSS Fathead

### PR DESCRIPTION
**Pull request by hchienjo**
CSS Rules Reference. (Work in Progress)

Fixes: https://github.com/duckduckgo/zeroclickinfo-fathead/issues/226

https://duck.co/ia/view/mdn_css

### CODE REVIEW

**Comment by daxtheduck** [comment]
@hchienjo Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gaulrobe** [comment]
@hchienjo you are on the right track. Be sure to separate the fetching of the HTML and the parsing of the HTML into two separate files. That'll isolate the logic here to make it easier to review :smile: 

(fetch.sh and fetch.pl)
(parse.sh and parse.pl)

**Comment by moollaza** [comment]
@hchienjo this is looking awesome! 💯 

Thanks a lot for writing this in Perl and submitting a PR so quickly!

@jdorweiler will deploy this to beta for me and then we can start testing it and give you some feedback 👍

**Comment by hchienjo** [comment]
@moollaza It's still not quite complete though. The parsing implementation has not been completed, committed and merged.

**Comment by hchienjo** [comment]
@moollaza many thanks for the feedback and support. Will keep pushing commits and will alert you as soon as it is ready.

**Comment by moollaza** [comment]
@hchienjo whoops, my mistake.

Please let me know what you need help with, if anything.

Also, if you've created an IA Page for this, please paste the link to it in the PR description as that will be required to get this onto Beta eventually

**Comment by hchienjo** [comment]
@moollaza Will do so.

**Comment by hchienjo** [comment]
@moollaza @gaulrobe I have implemented the parsing and the output.txt file looks like this
[output.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/files/337043/output.txt)
Any comments/suggestions?

**Comment by gaulrobe** [comment]
@hchienjo I'm not the best person to review the Perl code 😜 but this is looking pretty reasonable from a high level. Do you mind pushing an output.txt file so that we can see what that is looking like? That'll help find any potential problem areas. :)

**Comment by hchienjo** [comment]
@gaulrobe  Done.

**Comment by moollaza** [comment]
@hchienjo thanks a lot! This is looking great.

We're going to get this on Beta for testing. Looking at the output, I think we'll definitely want to add in example code snippets where possible. 

As well, we should provide links to the documentation so clicking the title will take you to the correct MDN  article.

The JavaScript MDN Fathead does a good job of this:  https://duckduckgo.com/?q=Array.prototype.sort&ia=about

The output.txt is here: https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdnjs/output.txt

**Comment by hchienjo** [comment]
@moollaza Noted. Taking your suggestions into consideration and will work on them. Thanks.

**Comment by hchienjo** [comment]
Take for example this [link](https://developer.mozilla.org/en-US/docs/Web/CSS/:active), should the snippet include both the html and the css? And is it possible to show even the rendered representation of how the html is affected by the CSS? Basically this 
sample

**Comment by moollaza** [comment]
@hchienjo I would say for now grab the CSS snippet.

We may be able to show both snippets, but we won't be able to show that rendered output. We'd need to be able to create an iFrame with that content + the required CSS which isn't possible right now.

However I see that they have a "View on Codepen" button. We could potentially but out that link. We may also be able to create a DDG button using our classes: https://duckduckgo.com/styleguide#buttons

**Comment by moollaza** [comment]
@hchienjo I just realized we can add an external link in field #9, if you set it to `[[https://example.org]]` -- If we can pull out the Codepen link we should be able to use that field to add a link.

**Comment by hchienjo** [comment]
@moollaza Noted.

**Comment by moollaza** [comment]
@hchienjo can you please create an Instant Answer page for this and paste the link in the PR Description above? An IA Page is required for the PR to be deployed to Beta.

Instructions are here: http://docs.duckduckhack.com/submitting/pull-request.html

**Comment by hchienjo** [comment]
@moollaza on it.

**Comment by hchienjo** [comment]
@moollaza Is that really the right format? Please help/

**Comment by sahildua2305** [comment]
@hchienjo No. Please add the link in the first comment of the PR.

For example, see [this](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/221).

**Comment by moollaza** [comment]
@hchienjo this is now deployed to Beta!

https://beta.duckduckgo.com/?q=css3+text-decoration-color&ia=about

For also gave it the trigger word "css3" -- we'll change that shortly to include "css" so all the expected queries like "css text-shadow" will work 👍 

Please add the data source URL to the output.txt for each item to correct the "More at" link.

**Comment by hchienjo** [comment]
I will keep pushing commits and updates as I verify things on my end.

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=css3 text-decoration)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/mdn_css_mobile.png?5nvutjPyex)

**Comment by hchienjo** [comment]
@moollaza The link to codepen is triggered by clicking and is not visible directly in the html, however, the rendered output has a [direct link](https://mdn.mozillademos.org/en-US/docs/Web/CSS/:active$samples/example?revision=1004837)

What do  you suggest I do? Grab the CSS, HTML and link to rendered output?

**Comment by gaulrobe** [comment]
@hchienjo I think that is a good idea to get all three of those seeing as it gives users really good context of how to use and visually verify they are using the CSS correctly.

**Comment by hchienjo** [comment]
@gaulrobe Thanks. Let me work on this.

**Comment by moollaza** [comment]
@hchienjo thanks for doing a great job so far 💯  This is looking great.

It's still got lots of room for improvement, but it's decent enough to be merged. Please continue working. on improving this. I would say the next big win will be getting the code snippet in here. We don't necessarily need the CodePen/JSFiddle links yet -- it looks like they will be a little more difficult than I had hoped anyways 👍

**Comment by daxtheduck** [comment]
@hchienjo this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Comment by hchienjo** [comment]
This is great! I am working on it getting more and more features 
implemented. You are right the CodePen link is pretty hard.
Thanks.

**Comment by moollaza** [comment]
@wrt2 were you trying to leave a comment about something?

**Pull request merged**
