### PR TITLE
Django: Rework fathead to handle sub modules

### LINKED ISSUE #766: Django Suggestion: Extend parser to include submodules + methods
### Description

This is a really cool IA, but it's not covering much of the search space and it's definitely under-triggering based on the unanswered query data. Currently, we are only scraping the top module and need information on sub modules and their methods. For example:

Triggers: `django admin`
Doesn't trigger: `django admin modelAdmin`

## People to notify
Maintainer: @vigzmv

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/django

### PR DESCRIPTION
**Pull request by Hestben**
* Sort output uniquely.
        The original output had 1101 lines. Now the unique output shows that
        only 359 entries were actually unique.

    * Download all sources, not specific pages.

    * Parsing module names, functions, methods and attributes.

    * Add redirect.py and sort properly and uniquely.

    * Add output_statistics.awk

    * Add output.txt.

## Description of new Instant Answer, or changes

This is a complete rework of the fathead, and adds a lot of articles and a huge amount of redirects.

One con is that the [django allowed_hosts](https://duckduckgo.com/?q=Django+allowed_hosts&ia=about) query and other queries for settings will not work. I could look into that, if it is necessary.

## Related Issues and Discussions

Fixes #766 

## People to notify

@pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/django

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by Hestben** [comment]
I just noticed, that classes, methods, functions and attributes didn't get a parsed paragraph properly, so I added a commit to fix that.

**Comment by Hestben** [comment]
@pjhampton, @moollaza  Are we getting anywhere with this PR?

**Comment by vigzmv** [comment]
@moollaza Have a look at this when possible.

**Comment by nmalkin** [comment]
As a user, looking forward to seeing this incorporated!

Just wanted to mention that the [latest Django release is now 1.11](https://docs.djangoproject.com/en/stable/releases/); this PR uses 1.10, but it looks like it should now be just a one-line change.

**Comment by moollaza** [comment]
@Hestben Thanks! This LGTM :+1:

**Pull request merged**
