### PR TITLE
Remove modules, move scripts to lib

### LINKED ISSUE #190: Remove Metadata
We still have lots of file with metadata in! This is handled by https://duck.co now.

Pretty sure we want to be removing the metadata from FatHeads too @moollaza?

### PR DESCRIPTION
**Pull request by zachthompson**
* Remove Perl modules which only served to house metadata.
* Move scripts to lib/ since they are shared and would conflict with js/css/handlebars if and when we allow templating.

The move to lib/ will probably need to be coordinated with path updates internally (only see three instances of share/fathead.)

Resolves #190

cc @b1ake @mrshu

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by GuiltyDolphin** [comment]
@zachthompson I assume this resolves #190?

**Comment by zachthompson** [comment]
@GuiltyDolphin yes indeed.  I have a branch for goodies too that @moollaza is verifying will work internally first.

**Comment by zachthompson** [comment]
@jdorweiler We are so close to victory.  Don't fear the fatheads.

**Comment by jdorweiler** [comment]
:+1:

**Comment by russellholt** [comment]
niiiiiiice. finally
:+1:

**Pull request merged**
