### PR TITLE
Fixed html tree

### PR DESCRIPTION
**Pull request by andreasjacobsen93**
If this is a bug fix:
GitManual

## Related Issues and Discussions
Fixes issue #825 

---

Instant Answer Page: https://duck.co/ia/view/git_manual

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@andreasjacobsen93 thanks for fixing this! Can you please generate the updated output.txt and push it here?

That way it will be installed to Beta for testing 👍

**Comment by samskeller** [comment]
@moollaza @andreasjacobsen93 this LGTM, but I'll hold off on approving this PR until the updated output.txt is added

**Comment by andreasjacobsen93** [comment]
Now quite sure how to do that. Could you point me in the right direction?

**Comment by samskeller** [comment]
@andreasjacobsen93 you'll need to run the `fetch.sh` shell script in the `git_manual` to download the html files, then you'll need to run the `parsh.sh` shell script to parse through it and produce the `output.txt` file. You'll also need to make sure you have the right dependencies installed (probably via a virtual environment if you're familiar with that) to run the Python script that `parsh.sh` calls -- Python 3.4 or above, `beautifulsoup4==4.4.1`, and `requests==2.9.1`. Just let me know if you have more questions

**Comment by moollaza** [comment]
@andreasjacobsen93 Thanks! This LGTM :+1:

**Pull request merged**
