### PR TITLE
New Haddock FatHead

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
@jdorweiler This will be my attempt at a Haskell FatHead :wink:

---

IA Page: https://duck.co/ia/view/haddock
Maintainer: @GuiltyDolphin

### CODE REVIEW

**Comment by daxtheduck** [comment]
@GuiltyDolphin Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
thanks @GuiltyDolphin!  will check this out soon

**Comment by moollaza** [comment]
@GuiltyDolphin though this is pretty cool, I'd prefer we stick to standard languages we already support: Perl, Python, Ruby 

@jdorweiler any opinions? 

I'd rather see us standardize around a few languages, and develop tools, plus templates around writing Fatheads in those languages so it can be greatly simplified.

Nearly every Python and Perl Fathead we have looks different and we can probably use a common approach in all cases. I think that would help make it even easier to create Fatheads?

**Comment by GuiltyDolphin** [comment]
@moollaza This is a little experiment @jdorweiler and I are trying :wink:

Haskell utilities are likely to be some of the easiest to standardize - pretty much everything I've written so far is essentially a 'utility' library we could easily pull out (and type safety should help ensure the correct use of utilities).

I'm going to try getting a parser up today, so we can see what the result looks like; hopefully good!

**Comment by GuiltyDolphin** [comment]
@jdorweiler I've got it to the point where you can test out some articles (try `Paragraph` and `Special Characters`) - enjoy.

**Comment by pjhampton** [comment]
Hey @GuiltyDolphin !

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, with the above in mind, this isn't something we can action and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to triage this issue.

**Pull request closed without merging**
