### PR TITLE
Python: unify python2 and python3 docs

### LINKED ISSUE #272: Python: unify python2 and python3 docs
**Background**

We have coverage of docs.python.org for Python3 but none for Python2. Even though Python2 is considered a legacy version, it still has a lot of use. 

**Objective**

Unify our python docs fathead to cover both Python3 and Python2. 

The exact implementation is up to whoever develops this but I think the general idea is to:

- Default to python3 docs in cases where both python3 & 2 are identical
- In cases where they're different show the Python3 docs but include an infobox link to the Python2 docs. 

How I think this could work technically:

- update parse.py to parse both Python3 and Python2 docs 
- Generate separate output.txt files for each
- Go through both output files comparing keys and abstracts
- If the Python3 version is identical to the Python2 just keep the Python3 entry
- If they're different we can default that search to Python3 but show an infobox that links to the Python2 version.

---

IA Page: https://duck.co/ia/view/python

### PR DESCRIPTION
**Pull request by gerlachry**
fixes #272.  Add download of python2 docs and parsing.  Produce final output.txt file with python3 records that have different abstract then python2 to have a category and add python2 record w/ same category but the key prefixed with 'python2 '.   
Apologies for the messy commit history.

---

IA Page: https://duck.co/ia/view/python

### CODE REVIEW

**Comment by daxtheduck** [comment]
@gerlachry Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by edgesince84** [comment]
thanks for the PR, @gerlachry!   I'm CCing @jdorweiler so he can come in and review 👍

**Comment by jdorweiler** [comment]
@gerlachry this looks great!

I installed it on beta. Test it out and let me know if you see anything weird. 
https://beta.duckduckgo.com/?q=python+print&ia=about&atb=v23

**Comment by gerlachry** [comment]
@jdorweiler I tested out some queries last night and this morning and seems to be working as expected so far.  Is there other formal testing needed?  I did not see any existing in the fathead code base.

**Comment by jdorweiler** [comment]
@gerlachry nope, I tested a bunch of queries and everything looks great. Thanks for fixing this!

**Pull request merged**
