### PR TITLE
Python: Fix #297 -- Added disambiguations for deleted keys.

### LINKED ISSUE #297: Python: add disambiguations
In #270 we removed articles with namespace conflicts. 
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/python/redirect.py#L172
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/python/redirect.py#L182

We could try to generate a disambiguation in these cases. 
http://docs.duckduckhack.com/resources/fathead-overview.html

------
IA Page:  http://duck.co/ia/view/python 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @gaulrobe

### PR DESCRIPTION
**Pull request by souravbadami**
Fixes #297 

IA Page: https://duck.co/ia/view/python

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@souravbadami thanks! This is now deployed to Beta.

Can you please confirm it's working correctly?

**Comment by moollaza** [comment]
@souravbadami this should be on Beta now, can you please confirm?

**Comment by moollaza** [comment]
This is now live on beta!

https://beta.duckduckgo.com/?q=asyncio+python&ia=meanings

**Pull request merged**
