### PR TITLE
Ryzom: search the wiki

### PR DESCRIPTION
**Pull request by rubdos**
I implemented an IA using fathead for the free software Ryzom game's wiki. C&C is welcome, if everything is okay, a merge is welcome.

In the future, I'll add the Ryzom Intelligent Plants and other articles. Probably will build some form of an infobox, if this is possible in ddhack.

What does your Instant Answer do?
 * It provides instant answers to search requests for Ryzom mobs data. It will display the first two sentences of the wiki and will provide an image of the mob.

What problem does your Instant Answer solve (Why is it better than organic links)?
 * It save the user making redundant clicks by giving the most popular definition for a term.

What is the data source for your Instant Answer? (Provide a link if possible)
 * http://en.wiki.ryzom.com

Why did you choose this data source?
 * It is the official Ryzom Wiki

Are there any other alternative (better) data sources?
 * Probably http://ballisticmystix.net/ has a lot of additional information.

What are some example queries that trigger this Instant Answer?
 * "ryzom Yelk"
 * "ryzom Izam", ...

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
 * Ryzom gamers and developers.

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
 * Not that I know of...

Which existing Instant Answers will this one supercede/overlap with?
 * No one AFAIK

Are you having any problems? Do you need our help with anything?
 * Well, we understand that I cannot really test the Fathead plugins, so would wait for your review.

Where did you hear about DuckDuckHack? (For first time contributors)
 * I duckduckgo'd for an API or something.

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
 * No idea yet...

### CODE REVIEW

**Comment by moollaza** [comment]
Hey @rubdos I was actually expecting you to reply to my email, I wish you would have waited to implement this! As it turns out, one of our team members has a handy script which he was able to use to parse the Ryzom Wiki and produce a data file that our internal Wiki processing scripts can handle. 

This means we can very easily produce a closed-source Fathead for Ryzom. The benefit is that our script does an excellent job of parsing the data and its tailored to our setup. In favour of having a better Fathead, with more coverage we're going to user our own internal Fathead for this.

I'm really sorry that we can use your pull request, but we really appreciate you taking the time to contribute. Is there perhaps another Instant Answer you'd like to work on? Remember, if it's a Wiki (wikia powered) site, we can handle it very easily internally so if you're itching to code, it's best you find another type of source.

**Comment by moollaza** [comment]
@rubdos sorry for the lack of progress updates, we haven't forgotten about this!

It turns out our internal parsing script didn't work out as well as we were hoping due to the internal structure of the Ryzom Wikia (it's not quite what our scripts are tailored to).

It looks like the best way to move forward is to use your original script in this PR. My colleague @mrshu took some time to test your script, but he noticed it was also missing many pages from the Ryzom wikia. He has some feedback for you so that your code can be improved to gather more data from Ryzom. Depending on where this ends up, we're consider generalizing this code for the community so that we can offer other develoeprs an open-source Wiki parser, built by the community.

/cc @mrshu

**Comment by rubdos** [comment]
Interesting. I only took the Animals that walk on Atys for now in this script, in a later phase I'd implement other pages. I can generalize this to fetch every page though, that's not that difficult. If you give me a go, I'll try to do that this week. You'll also have to point me to some documentation about the infobox I can generate, as I can't find anything about that.

Thank you for you time and coming back to my question :)

**Comment by moollaza** [comment]
@rubdos if you wouldn't mind generalizing this for the rest of the Ryzom wiki that'd be great. With regards to the infobox, @mrshu will know more. I'm not entirely sure if open-source Fatheads can utilize it or not.

**Comment by rubdos** [comment]
> I'm not entirely sure if open-source Fatheads can utilize it or not. - @moollaza

Could you or @mrshu look at that for me? If it's not possible, that could be a useful feature request :)

I will try to work on it this week.

**Pull request closed without merging**
