### PR TITLE
'data type', 'data' postfix for data type queries in MDN JS

### LINKED ISSUE #556: MDN JavaScript: "data type" articles should have redirects with "type" and "data type" postfixed
Currently "javascript null type" doesn't trigger the Fathead. However, "javascript null" does.

We should have redirect for each "data type" article.

For example,  "null type" and "null data type" should redirect to "null".

------
IA Page:  http://duck.co/ia/view/mdnjs 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ericedens

### PR DESCRIPTION
**Pull request by mbad0la**
## MDN JS

Fixes #556 

## People to notify

@moollaza @tagawa @bfmags 

---

IA Page: http://duck.co/ia/view/mdnjs

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by bfmags** [comment]
@mbad0la code looks good!

@moollaza checks are failing due to missing/incorrect path rakefile: `$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)`

**Comment by moollaza** [comment]
> @moollaza checks are failing due to missing/incorrect path rakefile: $ rake rake aborted! No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

@bfmags that can be ignored -- I enabled Travis on the Fathead repo for my PR that adds a .travis.yml -- for now travis is just guessing that it's a ruby project because it's seeing .rb files

**Comment by bfmags** [comment]
@moollaza 

I can see the redirects in the output file, but can't get them to trigger [on DDG beta](https://beta.duckduckgo.com/?q=javascript+null+type) 

`null data type	R	null`
`null type	R	null`
`global null	R	null`

**Comment by moollaza** [comment]
@mbad0la can you please push a commit removing the output.txt, and then another adding it back?

We've just added support for Fathead autodeploys, so each time the output.txt changes in the PR, it will be automatically installed on Beta 👍 

That should ensure this is properly deployed.

**Comment by bfmags** [comment]
Code looks good 👍 

https://beta.duckduckgo.com/?q=mbad0la+uint32x4+data+type&t=ffsb&ia=about

Unfortunately there's still some triggering problems, investigating what the problem might be :confused:

**Comment by moollaza** [comment]
> Unfortunately there's still some triggering problems, investigating what the problem might be 😕

@bfmags what issues are you seeing?

**Comment by moollaza** [comment]
Without the username it seems to be working correctly?

https://beta.duckduckgo.com/?q=uint32x4+data+type&t=ffsb&ia=about

**Comment by MariagraziaAlastra** [comment]
@bfmags I think it's an internal issue with redirecting to a single word article. I suggest you merge this regardless, if it looks good!

**Comment by tagawa** [comment]
Hi @bfmags. Just wanted to let you know that this PR has now been released: https://duckduckgo.com/?q=javascript+uint32x4&ia=about

Thanks again for your work, as always!

**Pull request merged**
