### PR TITLE
Spring framework

### PR DESCRIPTION
**Pull request by mandekisd**
## People to notify

@moollaza 

---

Instant Answer Page: https://duck.co/ia/view/spring_framework

### CODE REVIEW

**Comment by moollaza** [comment]
@mandekisd it looks like you've made these changes from the branch you previously used?

Whenever you make a Pull Request, you want to start with a clean branch, that is branched off of the current master repo.

This PR is trying to re-apply commits that already exist and so it has conflicts.

Please read https://docs.duckduckhack.com/resources/git-workflow.html#step-3-create-a-working-branch-for-coding

**Comment by moollaza** [comment]
I'm closing this PR as I'll need you to open a new one 👍

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=AbstractAdaptableMessageListener)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/spring_framework_mobile.png?8dt9TxSDdC)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=AbstractAdaptableMessageListener)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/spring_framework_mobile.png?TJtsUwWM7Y)

**Comment by daxtheduck** [comment]
Automated screenshot from [beta.duckduckgo.com](https://beta.duckduckgo.com/?q=AbstractAdaptableMessageListener)
                
                [Mobile screenshot](https://images.duckduckgo.com/iu/?u=https://ia-screenshots.s3.amazonaws.com/spring_framework_mobile.png?QNPBSUBm2E)

**Pull request closed without merging**
