### PR TITLE
Fixes issue #733: Added Ruby Fathead Cover

### PR DESCRIPTION
**Pull request by acflint**
Issue link: https://github.com/duckduckgo/zeroclickinfo-fathead/issues/733

@pjhampton 
@kotoshenya 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/ruby

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by acflint** [comment]
@kotoshenya that was indeed a mistake, thanks! I think I've resolved that now. Sorry, I'm still getting used to git, so I'm a bit clumsy. Thanks again!

**Comment by moollaza** [comment]
@acflint it looks like the text files are empty? Please run your script so that the text files are not empty.

Also, please move the script out of the cover directory, as it should only contain text files.

Also, to create additional redirects for this Fathead automatically, you can user specific filenames. Please see the docs for more details: https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html#using-coverage-data-to-generate-redirects

**Comment by acflint** [comment]
@moollaza Thanks! I've made those changes. I'm not sure what happened, but these changes are now included in this pull request: https://github.com/duckduckgo/zeroclickinfo-fathead/pull/816

**Comment by pjhampton** [comment]
Hey @acflint!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
