### PR TITLE
Initial Scikit fathead

### PR DESCRIPTION
**Pull request by jrasanen**
Fathead for [Python Scikit](http://scikit-learn.org/stable/auto_examples/index.html).

Work in progress. Feedback is welcomed. :)

---
IA Page: https://duck.co/ia/view/scikit_learn

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
Thanks @jrasanen 
Check it out on beta https://beta.duckduckgo.com/?q=scikit+bayesian+ridge+regression&t=hb&ia=about&iax=1

**Comment by jdorweiler** [comment]
Want to try parsing out one of the images and see how that looks? One of the fields in the tsv file is for an image url.
selection_431

**Comment by jdorweiler** [comment]
@jrasanen looks good to me. Is there anything else you wanted to add to it?

**Comment by jrasanen** [comment]
@jdorweiler nothing more to add :)

**Comment by jdorweiler** [comment]
Thanks @jrasanen :sunglasses:

**Pull request merged**
