### PR TITLE
Fix #525: Python - Added python versions as subtitle.

### LINKED ISSUE #525: Python: add python version as subtitle
### Description
Add subtitles for the python version. 
To do this add the python version to the article title in parenthesis, in the output.txt file. 
For example, `unittest (python3)`

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python

### PR DESCRIPTION
**Pull request by souravbadami**
## Description of new Instant Answer, or changes
Added python versions as subtitle.

## Related Issues and Discussions
Fixes #525 

## People to notify
@moollaza @jdorweiler 

---

Instant Answer Page: https://duck.co/ia/view/python

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
I'm seeing some entries that have duplicate subtitles. 
```
python2 sqlite3.Connection.execute (python2) (python2)
os.stat_float_times (python3) (python3)
```

**Comment by souravbadami** [comment]
@jdorweiler -- It doesn't appear on my output file.

`os.stat_float_times (python3)	A										<section class="prog__container"><p>Determine whether stat_result represents time stamps as float objects. If newvalue is True, future calls to stat() return floats, if it is False, future calls return ints. If newvalue is omitted, return the current setting.</p><pre><code>os.stat_float_times([newvalue])</code></pre></section>	https://docs.python.org/3.5/library/os.html#os.stat_float_times`

`python2 sqlite3.Connection.execute (python2)	A			sqlite3.Connection.execute							<section class="prog__container"><p>This is a nonstandard shortcut that creates an intermediate cursor object by calling the cursor method, then calls the cursor’s execute method with the parameters given.</p><pre><code>execute(sql[, parameters])</code></pre></section>	https://docs.python.org/2.7/library/sqlite3.html#sqlite3.Connection.execute`

**Comment by jdorweiler** [comment]
You're right. I was running parse.sh and redirect.py separately.

**Comment by moollaza** [comment]
@souravbadami @jdorweiler I've deployed this to Beta but I'm having difficulty triggering the IA now. I will need to investigate further.

----

Also, unrelated to this PR, but fwiw, when you sort the output, it becomes apparent that the first 100 lines in the output.txt are very lengthy, awkward strings, that have numbers in them:

`35.1. posix — The most common POSIX system calls (python3)`

We're also creating redirects for these. We should probably be ignoring these?

**Comment by moollaza** [comment]
Whoops, the Beta deploy never happened. Deploying it now...

**Comment by souravbadami** [comment]
@moollaza -- These are currently not ignored. I'll add a separate PR to handle this problem. For the current PR, Is it deployed to beta ? It's not getting triggered for me.

**Comment by moollaza** [comment]
> For the current PR, Is it deployed to beta ? It's not getting triggered for me.

@souravbadami it is deployed, but it looks like it's creating a lot of problems. 

I've created an issue explaining how I think this can be solved: 

https://github.com/duckduckgo/zeroclickinfo-fathead/issues/555

Closing this PR as it's clear now this isn't the path we should go down.

Thanks for the awesome work @souravbadami 👍

**Pull request closed without merging**
