### PR TITLE
Continuing PR #647

### PR DESCRIPTION
**Pull request by gautamkrishnar**
## Background

Continuing PR #647  -- Developer was unable to complete the Pull Request

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page**
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/php

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by gautamkrishnar** [comment]
@ioanmoldovan looking good 👍

**Comment by gautamkrishnar** [comment]
Looks like this has some merge conflicts with #672

**Comment by moollaza** [comment]
@gautamkrishnar @ioanmoldovan looks like this is able to create duplicates, and empty results:

https://beta.duckduckgo.com/?q=php+constants&ia=about

Look at the output.txt entries for this. There are 5 identical articles for `constants` that only contain empty `<p>` and `<pre><code>` tags...

**Comment by moollaza** [comment]
Let's also sort the output to make it a little easier to read. @gautamkrishnar did you try running the Fathead tests? They should have caught the duplicates..

**Comment by gautamkrishnar** [comment]
Yes! I forgot that @moolaza.
```
duckpan test php
```
is giving too many errors. @ioanmoldovan can you fix it. Do you have write access on this PR?

**Comment by moollaza** [comment]
> is giving too many errors. @ioanmoldovan can you fix it. Do you have write access on this PR?

@gautamkrishnar most of those are the 18K missing entries in the Output file -- that's OK, because the coverage file lists more than the output has (yet). It looks like there are 10 duplicates that need to be fixed though 👍

**Comment by gautamkrishnar** [comment]
Closing this PR since it is not writable by the original contributor

**Pull request closed without merging**
