### PR TITLE
MDN CSS: Add aliases for background-*

### LINKED ISSUE #637: MDN CSS: Add aliases (redirects) -- background
### Description

This IA shows answers for searches such as [background color](https://duckduckgo.com/?q=css+background+color&t=lm&ia=about) but not for searches such as `color background`. 

## What to do.
Create a new text file called redirects.txt in the same folder as [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt).

Create aliases for each entry in [articles.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/mdn_css/articles.txt) for which `background` is prepended or appended to one of the following words:

-  color
-  width
-  height
-  position
-  size
-  align
-  center
-  image

Each alias goes to its line in redirects.txt in the following format: `alias,original name`

## Example entries
`background-color,color-background`

## People to notify

@moollaza @hchienjo

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/mdn_css

### PR DESCRIPTION
**Pull request by onchance**
Fixes #637. MDN CSS entries like "background-color" weren't being triggered by searches like "color background". Added redirects.txt aliases to specify these cases explicitly.

Instant Answer Page: https://duck.co/ia/view/mdn_css

### CODE REVIEW

**Comment by daxtheduck** [comment]
@onchance Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
@onchance Thanks, your PR was deployed to beta, see the result for [css blend background](https://beta.duckduckgo.com/?q=css+blend+background&t=h_&ia=about) :smile:

**Comment by onchance** [comment]
@MariagraziaAlastra Thanks! That was fast.

**Comment by MariagraziaAlastra** [comment]
@onchance Looks good, thanks! 👍

**Pull request merged**
