### PR TITLE
New fathead kanji_info

### PR DESCRIPTION
**Pull request by MarkMcCaskey**
Work in progress.  The `output.txt` generated from my code appears to be correct.  However it may need to be updated as the design changes.  I'm uncertain about how to go about dealing with the SVGs or any of the frontend really.  Instructions are provided in my README.txt for generating the SVGs.
https://duck.co/ia/view/kanji_info

### CODE REVIEW

**Comment by daxtheduck** [comment]
@MarkMcCaskey Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by jdorweiler** [comment]
@MarkMcCaskey Thanks! Adding images will be interesting. I don't think we have a contributed fathead that does that yet. I'll see if I can get it working though.

**Comment by jdorweiler** [comment]
@MarkMcCaskey the svg animations won't work. Could you convert them to gif? There are no problems with using a gif at the image.
https://beta.duckduckgo.com/?q=kanji+亜&t=canonical&ia=about

**Comment by jdorweiler** [comment]
The data is installed on beta with the trigger word `kanji`. I'll add the other trigger words later. 

@tagawa You're probably a better person to review the content of this IA.
https://beta.duckduckgo.com/?q=kanji+%E5%AE%89&t=canonical&ia=about

**Comment by tagawa** [comment]
Thanks @jdorweiler - great to see it on beta.

@MarkMcCaskey 
Do you know if there are animated GIF alternatives to the SVGs? If not, we could release the IA without the animations and add them later. It's still a useful reference IMO.

Also, the stroke count for the kanji is correct and updated dynamically but the readings are fixed, as though they're hardcoded. Is this just a temporary thing as it's in progress?

**Comment by MarkMcCaskey** [comment]
@jdorweiler @tagawa Thanks!!

I'll look into converting them to gifs now and get back to you soon.

@tagawa 
I don't think I see what you mean.  They appear to be in the same <pre><code> block on the page.  If you mean in the Ruby program, I didn't check if the stroke count exists in the file before trying to read it, which it probably should.  But other than that they should be the same as far as I can tell.  If I'm missing something, please let me know and I'll do my best to fix it. Thanks!

**Comment by tagawa** [comment]
@MarkMcCaskey Sorry for not being clear - I meant whichever kanji I search for the readings don't change and so are incorrect, but the stroke order does change per kanji and is correct.

**Comment by jdorweiler** [comment]
@MarkMcCaskey that's too bad about the GIFs. I really like the SVG animations but the fathead data goes through a bunch of processing on our end and somewhere in there the animations are broken. 

I don't think we can make the stroke order frames work. The size of the image is going to be hard to deal with across desktop and mobile browsers.

@mrshu what do you think about the SVG animations? I dug around in our image processing scripts to see if I could get this working but no luck. I'm afraid it might take a lot of hacking.

**Comment by jdorweiler** [comment]
@MarkMcCaskey lets go without the animations for now. Do you know if there is an API for them?

**Comment by MarkMcCaskey** [comment]
@jdorweiler Okay, that's fine -- thanks!  No, not that I know of.
I'd be happy to try and add support for SVG animations to the image processing code, if that's possible.

**Comment by jdorweiler** [comment]
@MarkMcCaskey unfortunately it's not open source or well documented. I'll make an issue to see if I can get it working though. 

@tagawa does the content look okay or is there anything else to do?

**Comment by tagawa** [comment]
Sorry, not quite there yet. The layout looks OK but it's not showing the correct data. For example, these two kanji searches show the same (incorrect) values except for stroke count:
https://beta.duckduckgo.com/?q=kanji+%E6%97%A5&ia=about
https://beta.duckduckgo.com/?q=kanji+%E6%9C%AC&ia=about

I can't work out why though.

**Comment by jdorweiler** [comment]
@MarkMcCaskey still working on this?

**Comment by MarkMcCaskey** [comment]
@jdorweiler Not currently, no.

**Comment by edgesince84** [comment]
I'd like to see this continued in the future when it can be addressed again, but I'm going to close this out for now.  @MarkMcCaskey if you get some more time to work on this, or anything else, you can [join us](https://forum.duckduckhack.com/) at our new forum!

**Pull request closed without merging**
