### PR TITLE
Add DebianPkgs module.

### PR DESCRIPTION
**Pull request by elebow**
# Fathead Pull Request

**What does your instant answer do?**
Returns the version and short description of a Debian package in the current stable and testing repositories.

**What problem does your instant answer solve (Why is it better than organic links)?**
It provides enough information at a glance to tell a user the generalities of a package and the current versions in Debian. Organic links rarely provide such information without navigating to the destination.

**What is the data source for your instant answer? (Provide a link if possible)**
https://packages.debian.org/stable/allpackages?format=txt.gz
https://packages.debian.org/testing/allpackages?format=txt.gz

**Why did you choose this data source?**
This is the authoritative list of packages in Debian

**Are there any other alternative (better) data sources?**
There are alternatives, but they are not likely to be better than the list from packages.debian.org.

**What are some example queries that trigger this instant answer?**

    debian vim
    debian package plink
    netcat debian pkg

**Which communities will this instant answer be especially useful for? (gamers, book lovers, etc)**
Debian users; possibly Ubuntu users

**Is this instant answer connected to a DuckDuckHack [instant answer idea](https://duck.co/ideas)?**
https://duck.co/ideas/idea/277/debian-and-derivatives-like-ubuntu-package-infor

**Which existing instant answers will this one supercede/overlap with?**
None known. There is a unmerged branch at https://github.com/duckduckgo/zeroclickinfo-fathead/tree/debian_pkgs, but it hasn't been touched in years.

**Are you having any problems? Do you need our help with anything?**
None.

### CODE REVIEW

**Comment by moollaza** [comment]
ping! @elebow are you still interested in working on this?

**Comment by elebow** [comment]
@moollaza sure

Can we get a design decision on whether the distro lines should stay or go? It is useful information, since many debian users run a version other than the stable release.

**Comment by Two-Tone** [comment]
I feel like they should stay and be links to those versions on the Package Search because of what elebow said.

**Comment by moollaza** [comment]
@jdorweiler I can't remember if we allow HTML in Fatheads? I would opt for a `<table>` or something to list the versions in a nicer way. 

If not, I think putting the 3 links in a row might look okay, like:

Stable: [2.5.3-2](#), Testing: [2.5.4-2](#), Unstable: [2.6.1-1](#)

---

I'm not a Debian user so I'm not sure how valuable having those links would be, but if you think it's beneficial I think we should allow it.

@jdorweiler any thoughts?

**Comment by jdorweiler** [comment]
No tables but the pypi fathead has a table like format that is made by adding <br> tags to separate each line.  https://duckduckgo.com/?q=python+pandas&t=canonical&ia=about

I like the three links in a single row.  Let's try that out and see how it looks.

**Comment by moollaza** [comment]
FWIW another dev is planning to implement a basic Spice for debian packages using an API. Right now the API only gives package names, but he's hoping to reach out to Debian and improve the API.

I think a Spice is definitely the way to go for this kind of data that's more likely to change somewhat regularly.

**Comment by jdorweiler** [comment]
The spice version of this is merged https://github.com/duckduckgo/zeroclickinfo-spice/pull/1697

**Pull request closed without merging**
