### PR TITLE
Abbreviations.com IA Fathead Plugin

### PR DESCRIPTION
**Pull request by stands4**
Fathead Pull Request Template
Using this template will help us better understand your Instant Answer and assist you when necessary. Simply copy and paste the markdown below into the description of your GitHub pull request and complete as appropriate.

What does your Instant Answer do?
- It provides instant answers to acronyms and abbreviations related queries.

What problem does your Instant Answer solve (Why is it better than organic links)?
- It save the user making redundant clicks by giving the most popular definition for a term.

What is the data source for your Instant Answer? (Provide a link if possible)
- http://www.abbreviations.com

Why did you choose this data source?
- We are the operators of Abbreviations.com and been approached by the Business Development Team at DuckDuckGo

Are there any other alternative (better) data sources?
- Well, we're biased but don't think so...

What are some example queries that trigger this Instant Answer?
"what does ASAP mean"
"What does ASAP stand for"
"What is ASAP short for"

Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)
- All audience

Is this Instant Answer connected to a DuckDuckHack Instant Answer idea?
- Not that we know of...

Which existing Instant Answers will this one supercede/overlap with?
- No one AFAIK

Are you having any problems? Do you need our help with anything?
- Well, we understand that we can really test the Fathead plugins, so would wait for your review

Where did you hear about DuckDuckHack? (For first time contributors)
- You've approached us

What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)
- No idea yet...

https://duck.co/ia/view/abbreviations

### CODE REVIEW

**Comment by jdorweiler** [comment]
@stands4 Thanks!  Looks pretty good.  There were a few carriage returns in the data that were causing problems.  Could you remove those?

**Comment by jdorweiler** [comment]
selection_389

**Comment by stands4** [comment]
Thanks @jdorweiler - we've took care of the carriage returns characters in the data, no sources affected.

Screenshot looks great! Can you please just change 'abbreviations.com' to 'Abbreviations.com' (with capital 'A')?

**Comment by jdorweiler** [comment]
@stands4 thanks, I added the new data to ddh4.
https://ddh4.duckduckgo.com/?q=airport+01a&ia=about
selection_397

**Comment by stands4** [comment]
Thanks Jason! Looks pretty neat...

May I ask what kind of queries trigger the IA? I'm seeing responses for
'<term> abbreviation' occasionally (e.g.
https://ddh4.duckduckgo.com/?q=rdbms+abbreviation&ia=about) but not always
(e.g. https://ddh4.duckduckgo.com/?q=isis).

Also, I believe the most appropriate queries would be:

what does <term> stand for?
what does <term> stand for?

Best,
Yigal

**Comment by stands4** [comment]
Sorry, I meant

what does <term> stand for?
what does <term> mean?

**Comment by moollaza** [comment]
@stands4 @jdorweiler one question -- I noticed "Yolo" on the Abbreviations.com has "You only live once" (the meaning I was expecting) as the first result, however we show the 2nd result from the site "Your once in a lifetime opportunity" -- any reason for that? The first result from the site seems more "correct".

**Comment by stands4** [comment]
Good catch, Zaahir!

The query we used for the dump missed an additional order directive. This
is fixed now, you may need to re-run fetch/parse again to grab the new
dataset - no additional checkins involved.

Thanks,
Yigal

**Comment by jdorweiler** [comment]
@stands4 trigger words are either at the start or end of the query so we won't be able to do things like
 `what does <term> stand for?`

I added the triggers:
- what is
- what is the
- airport(s)
- code
- abbreviation

Any others that you want added?

How often should we update the data once this is live?

**Comment by stands4** [comment]
The data is being updated all the time, but I guess a weekly or even
monthly updates should suffice.

I would also add some of the following triggers if possible:

   - acronym
   - texting
   - shorthand
   - meaning of
   - full form of

Thanks,
Yigal

**Comment by jdorweiler** [comment]
@stands4 Can we exclude entries that have 10 or fewer characters in their abstract?

**Comment by stands4** [comment]
Sure, we'll work on this early next week.

**Comment by stands4** [comment]
This is now done on the web service - no code changes involved.

Please let me know if there's anything else that you'd like to add or
change.

**Comment by jdorweiler** [comment]
@stands4 Thanks!  Everything looks good.  I'll ping you again when it's live.

**Comment by stands4** [comment]
Great news! Thanks Jason - looking forward...

**Pull request merged**
