### PR TITLE
SQLAlchemy: Refactor to use doc index

### LINKED ISSUE #735: SQLAlchemy: List all topic titles and language features to help measure coverage
### Description
For every Fathead, we need to gather the set of articles we wish to provide coverage for.
Create a `cover/` directory containing text files that list all the topic titles and language features to cover. 
These lists will then be used as Unit tests to help you measure the Fathead's coverage. 
For more info please see [the docs](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html).

## Get Started
- [x] 1) Claim this issue by commenting below
- [x] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [x] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [x] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/sqlalchemy

### PR DESCRIPTION
**Pull request by knowledgewarrior**
## Description of new Instant Answer, or changes
Refactor to use doc index 

## Related Issues and Discussions
Fixes #735 

## People to notify

@pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [x] Uniformly indented, well commented
- [x] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [x] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures
duckpan test sqlalchemy passes

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/{ID}

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@knowledgewarrior thanks for contributing!

Unfortunately these changes are heading in the wrong direction.

Implementing #735 is a much simpler task than this: We need to add a `/cover` directory in `lib/fathead/sqlalchemy` with a `.txt` file listing all the keywords in the SQLAlchemy docs that we expect our Fathead to cover and show a result for.

Your changes have removed all the content from the `output.txt` and replaced it with redirects to articles that don't exist.

First you need to have an article (`A`) entry in the output.txt.

If you want to create an alias for that article title, you can add a redirect (`R`) from `Foo` to `Bar` where `Bar` is the title of an existing article (`A`).

I think you're trying to improve the entire Instant Answer? However we need to ensure we're generating abstracts, which means parsing the documentation like the code currently does.

Does this make more sense?

**Comment by knowledgewarrior** [comment]
@moollaza 

Thanks for reviewing the pull request.  I refactored due to the fact the fathead documentation actually mentions SQLAlchemy as an example of using the wrong docs.  The current live IA uses the tutorial whereas the getting started docs state it should use the reference docs.  

I wasn't sure of the exact output so I created the PR anyway.

I will do the simpler request and work on improvement later :)

**Comment by moollaza** [comment]
> Thanks for reviewing the pull request. I refactored due to the fact the fathead documentation actually mentions SQLAlchemy as an example of using the wrong docs. The current live IA uses the tutorial whereas the getting started docs state it should use the reference docs.
Good catch!

> I wasn't sure of the exact output so I created the PR anyway.
No problem! Thanks for giving it a shot 👍 
 
> I will do the simpler request and work on improvement later :)
Perfect, thanks!

**Pull request closed without merging**
