### PR TITLE
Rewrite jQuery fathead

### LINKED ISSUE #279: JQuery Fathead: rewrite it from scratch
## Background
The JQuery Fathead is actually part of a larger collection of parsers used to generate docs for searchcode.com. See the directory [here](https://github.com/duckduckgo/zeroclickinfo-fathead/tree/85911ef28b2b7c00eeedb2e2219910a7f7e90a62/lib/fathead/UNCLEAN).

As the README states, none of those files, including the [JQuery parser](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/85911ef28b2b7c00eeedb2e2219910a7f7e90a62/lib/fathead/UNCLEAN/parse_jquery.py), conforms to the current DDG Fathead standards.

Furthermore, the JQuery Fathead has huge triggering gaps and a big potential in covering the JavaScript search space, and right now it's impossible to even debug it effectively.

## To Do

- Create a /jquery directory in this repo
- Add a fetcher for [api.jquery.com](http://api.jquery.com/) - you'll need to add two files: fetch.sh and fetch.py (or fetch.pl, depends on which language you want to use).
- Add a parser - you'll need two files in this case too: parse.sh and parse.py (or parse.pl, depending on the language)
- Generate an output.txt file that has all the article titles from [api.jquery.com](http://api.jquery.com/), together with the type, the abstract and the source url separated by tabs.

## Examples
Here are some examples of the files required to create a Fathead:
- [fetch.sh](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/py_pi/fetch.sh) and [fetch.py](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/py_pi/fetch.py)
- [parse.sh](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/py_pi/parse.sh) and [parse.py](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/py_pi/parse.py)
- [output.txt](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/85911ef28b2b7c00eeedb2e2219910a7f7e90a62/lib/fathead/mdnjs/output.txt)

## Docs
[Learn more about Fatheads](http://docs.duckduckhack.com/resources/fathead-overview.html)

## Forum
See the forum topic [Improve JQuery Fathead](https://forum.duckduckhack.com/t/improve-jquery-fathead/180) for more details.

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

-----------------------------
IA Page: https://duck.co/ia/view/jquery

### PR DESCRIPTION
**Pull request by kotoshenya**
This is a rewrite of the jQuery Instant Answer, discussed in #279 and [on the forum](https://forum.duckduckhack.com/t/improve-jquery-fathead/180).

[parse.js](https://github.com/kotoshenya/zeroclickinfo-fathead/blob/3cb0340ee8384850704c591b8b6475d05277a6ea/lib/fathead/jquery/parse.js) is written in Node and uses [xpath](https://www.npmjs.com/package/xpath) with [xmldom](https://www.npmjs.com/package/xmldom) for parsing.  The [api.jquery.com](https://github.com/jquery/api.jquery.com) XML source is used as a more reliable documentation source than screen scraping.

Example entry:

> #### jQuery.each() 
> 
> A generic iterator function, which can be used to seamlessly iterate over both objects and arrays. Arrays and array-like objects with a length property (such as a function's arguments object) are iterated by numeric index, from 0 to length-1. Other objects are iterated via their named properties.
>
>     jQuery.each(array, callback, indexInArray, value) → Object
>     jQuery.each(object, callback, propertyName, valueOfProperty) → Object
>
> [More at jQuery API](https://api.jquery.com/jQuery.each/)
>
> **Categories:** jQuery methods

***

Closes #279
IA: [jQuery](https://duck.co/ia/view/jquery)
Forum topic: [Improve jQuery Fathead](https://forum.duckduckhack.com/t/improve-jquery-fathead/180)

This PR is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@kotoshenya thanks for the updates! The updated Fathead is now live on Beta:
https://beta.duckduckgo.com/?q=event.isPropagationStopped()&t=hd&ia=about

**Comment by moollaza** [comment]
@kotoshenya @MariagraziaAlastra a few thoughts:

- we may want to create redirects by splitting the function names into separate words
  - E.g. looking at the autocomplete I see the query `jquery mouse down`
- we may also want to create redirects with the word "event" added to event names
  - E.g. looking at the autocomplete I see the query `jquery mousedown event`

What do you think?

**Comment by kotoshenya** [comment]
@moollaza sounds good to me, we could special case `“mouse<x>” → “mouse <x>”` and split `“camelCase” → “camel case”`.

The XML gives us general and specific categories (e.g., [`.mousedown()` belongs to *events/mouse-events*](https://github.com/jquery/api.jquery.com/blob/master/entries/mousedown.xml#L77)) so we can add a few levels of redirects and create some more category pages.

Is there a copy of the current Fathead’s output available?  It would be useful to see what redirects already exist and check for regressions.

**Comment by MariagraziaAlastra** [comment]
@kotoshenya Thanks for working on this! You can find a dump of the output [here](https://gist.github.com/MariagraziaAlastra/61f08bae5510258483d12124ea076503).

@moollaza I totally agree, I'm sure that's a common way for people to search for these reference articles.

**Comment by MariagraziaAlastra** [comment]
@kotoshenya I think for events we might also want to have redirects in the form of "on" + the event (eg: "on scroll", "on mousedown", "on hover" etc).

Anyway, I'm testing this on [beta](https://beta.duckduckgo.com/?q=jquery+ajaxsuccess&ia=about) and it's looking good, but some important redirects are missing. 
Eg we have no result for:
- [jquery post](https://beta.duckduckgo.com/?q=jquery+post&ia=web)
- [jquery get](https://beta.duckduckgo.com/?q=jquery+get&ia=web)

While the IA shows up for:
- [jquery jQuery.post()](https://beta.duckduckgo.com/?q=jquery+jQuery.post()&ia=about)
- [jquery jQuery.get()](https://beta.duckduckgo.com/?q=jquery+jQuery.get()&ia=about)

**Comment by MariagraziaAlastra** [comment]
It's on beta!

The queries in the comment above work as expected.
Just a minor issue: [jquery get json](https://beta.duckduckgo.com/?q=jquery+get+json&ia=about)  and [jquery get JSON](https://beta.duckduckgo.com/?q=jquery+get+JSON&ia=about) work, but the following don't:

- [jquery getJSON](https://beta.duckduckgo.com/?q=jquery+getJSON&ia=iatesting)
- [jquery getjson](https://beta.duckduckgo.com/?q=jquery+getjson&ia=iatesting)
- [jquery getJSON()](https://beta.duckduckgo.com/?q=jquery+getJSON()&ia=iatesting)
- [jquery .getJSON()](https://beta.duckduckgo.com/?q=jquery+.getJSON()&ia=iatesting)

**Comment by kotoshenya** [comment]
That last commit should have added the getJSON redirects, except possibly for [jquery .getJSON()](https://beta.duckduckgo.com/?q=jquery+.getJSON()&ia=iatesting) depending on whether the loader script removes the dot.

**Comment by kotoshenya** [comment]
> - [jquery getJSON](https://beta.duckduckgo.com/?q=jquery+getJSON&ia=about)
> - [jquery getjson](https://beta.duckduckgo.com/?q=jquery+getjson&ia=about)
> - [jquery getJSON()](https://beta.duckduckgo.com/?q=jquery+getJSON()&ia=about)
> - [jquery .getJSON()](https://beta.duckduckgo.com/?q=jquery+.getJSON()&ia=about)

These should all work now, as well as [jquery .getJSON](https://beta.duckduckgo.com/?q=jquery+.getJSON&ia=about).

**Comment by MariagraziaAlastra** [comment]
Latest version deployed to beta!
The queries above are all working, as well as the ones with "jQuery" replaced by "$", like [$.getJSON()](https://beta.duckduckgo.com/?q=%24.getJSON()&ia=about).

I'm not seeing any issues with triggering so far, but the content for the query [jquery fade in](https://beta.duckduckgo.com/?q=jquery+fade+in&ia=about) is a bit odd.

Looking at the [docs](http://api.jquery.com/fadeIn/) I see there are indeed three ways to call this method, but it would be nice to show the different arguments they require as well.

Thanks!

**Comment by MariagraziaAlastra** [comment]
Another little issue: the code snippet gets ellipsis for the query [jquery css](https://beta.duckduckgo.com/?q=jquery+css&ia=about), but for other queries, eg [jquery ajax](https://beta.duckduckgo.com/?q=jquery+ajax&ia=about), the snippet is scrollable on the x axis, allowing users to see the overflowing part as well.

screenshot-beta duckduckgo com 2016-08-17 14-55-29
screenshot-beta duckduckgo com 2016-08-17 14-55-43

**Comment by kotoshenya** [comment]
Thanks!

> the content for the query [jquery fade in](https://beta.duckduckgo.com/?q=jquery+fade+in&ia=about) is a bit odd

It currently looks like this:

> Display the matched elements by fading them to opaque.
>
>     .fadeIn → jQuery
>     .fadeIn → jQuery
>     .fadeIn → jQuery

and [should look like this](https://api.jquery.com/fadeIn/):

>     .fadeIn( [duration ] [, complete ] ) → jQuery
>     .fadeIn( options ) → jQuery
>     .fadeIn( [duration ] [, easing ] [, complete ] ) → jQuery

The [code that reconstructs the function signatures](https://github.com/kotoshenya/zeroclickinfo-fathead/blob/c55e89d03fe7318aa52cb51a3a4222498df07b93/lib/fathead/jquery/parse.js#L108) is a bit hacky, I’ll need to improve it to handle these types of signatures.

> the code snippet gets ellipsis for the query jquery css, but for other queries, eg jquery ajax, the snippet is scrollable on the x axis, allowing users to see the overflowing part as well.

I think this is a front-end issue: the description for the query [jquery css](https://beta.duckduckgo.com/?q=jquery+css&ia=about) is truncated to a certain number of characters with CSS or JavaScript.  The whole description is visible [when expanded](https://beta.duckduckgo.com/?q=jquery+css&ia=about&iax=1).

**Comment by MariagraziaAlastra** [comment]
>The [code that reconstructs the function signatures](https://github.com/kotoshenya/zeroclickinfo-fathead/blob/c55e89d03fe7318aa52cb51a3a4222498df07b93/lib/fathead/jquery/parse.js#L108) is a bit hacky, I’ll need to improve it to handle these types of signatures.

Sounds good, thanks!
I think this PR can be merged after you solve this. everything else looks alright and it's already way better than what we have in production.

>> the code snippet gets ellipsis for the query jquery css, but for other queries, eg jquery ajax, the snippet is scrollable on the x axis, allowing users to see the overflowing part as well.

>I think this is a front-end issue: the description for the query [jquery css](https://beta.duckduckgo.com/?q=jquery+css&ia=about) is truncated to a certain number of characters with CSS or JavaScript.  The whole description is visible [when expanded](https://beta.duckduckgo.com/?q=jquery+css&ia=about&iax=1).

Yeah you're right. Don't worry about it then.

**Comment by kotoshenya** [comment]
Methods like `.fadeIn()` use an alternative way of listing arguments which wasn’t being picked up, that should be fixed now.

I’ve also added some more context to signatures: selectors look like `$(".class") → jQuery` instead of just being the name of the article, and methods and properties on instances of `jQuery` are prefixed with `$(selector)` so it’s more obvious where they apply.

Optional arguments are not currently flagged up (e.g., by being wrapped in brackets.)  This is possible, but would take a bit of extra time to get the formatting right.  Arguments to function arguments are also not displayed in any way.

**Comment by kotoshenya** [comment]
@MariagraziaAlastra disambiguation pages are still to do.  Would you like those before this gets merged, or as a separate PR?

**Comment by MariagraziaAlastra** [comment]
@kotoshenya if they're quickly done I can wait, otherwise I wouldn't block release.

By the way, on beta! [jquery fade in](https://beta.duckduckgo.com/?q=jquery+fade+in&ia=about)

**Comment by kotoshenya** [comment]
@MariagraziaAlastra I’ll give it a go :grin:

**Comment by MariagraziaAlastra** [comment]
@kotoshenya While further testing the PR, I found issues with triggering on some exact article titles:

- [jquery all selectors](https://beta.duckduckgo.com/?q=jquery+all+selector&ia=about) triggers but [jquery All Selectors ("*")](https://beta.duckduckgo.com/?q=jquery+All+Selector+(%22*%22)&ia=iatesting) doesn't
- [jquery animated selector](https://beta.duckduckgo.com/?q=jquery+animated+selector&ia=about) triggers but [jquery :animated Selector](https://beta.duckduckgo.com/?q=jquery+%3Aanimated+Selector&ia=web) doesn't
- [jquery Child Selector (“parent > child”)](https://beta.duckduckgo.com/?q=jquery+Child+Selector+(%E2%80%9Cparent+%3E+child%E2%80%9D)&ia=iatesting) doesn't trigger. I tried lowercasing it, removing the parentheses content altogether, still nothing. Some attempts: 
    - [jquery child selector](https://beta.duckduckgo.com/?q=jquery+child+selector&ia=iatesting) (this works [in production](https://duckduckgo.com/?q=jquery+child+selector&t=ffab&ia=about))
 - [jquery child selector ("parent > child")](https://beta.duckduckgo.com/?q=jquery+child+selector+(%22parent+%3E+child%22)&ia=web)
 -  [jquery child selector parent child](https://beta.duckduckgo.com/?q=jquery+child+selector+parent+child&ia=iatesting)
  - [jquery Child Selector](https://beta.duckduckgo.com/?q=jquery+Child+Selector&ia=iatesting) (this too works [in production](https://duckduckgo.com/?q=jquery+Child+Selector&t=ffab&ia=about))

**Comment by kotoshenya** [comment]
@MariagraziaAlastra I’ve removed the selectors from those titles, as the already appear in the IA.  Hopefully that fixes the triggering, and the category page display bug that [also appeared in the Ruby Fathead](https://github.com/duckduckgo/zeroclickinfo-fathead/pull/277#issuecomment-236632919).

“:animated Selector” is an exact title, so I’m not sure why it doesn’t trigger.  Could be that “:” is interpreted as something when it’s inserted into the database?

**Comment by MariagraziaAlastra** [comment]
@kotoshenya Thanks, latest version is on beta!

[jquery child selector](https://beta.duckduckgo.com/?q=jquery+child+selector&ia=iatesting) and [jquery Child Selector](https://beta.duckduckgo.com/?q=jquery+Child+Selector&ia=iatesting) are triggering now, like in production.

> “:animated Selector” is an exact title, so I’m not sure why it doesn’t trigger. Could be that “:” is interpreted as something when it’s inserted into the database?

Yeah apparently the ":" is used for categories, so it gets stripped when article titles are inserted in the database.

**Comment by kotoshenya** [comment]
@MariagraziaAlastra awesome, thanks!

Disambiguation works for [jquery get](https://beta.duckduckgo.com/?q=jquery+get&ia=meanings), but the [.get()](https://beta.duckduckgo.com/56/.get()?ia=definition) link from that page just shows a definition.

From [the docs](http://docs.duckduckhack.com/resources/fathead-overview.html) I *think* I can change the links to `[[jQuery ${title}|${title}]]` so “.get()” is shown but the linked search has the keyword “jQuery”.  Is that right, and the best way to do it?

**Comment by MariagraziaAlastra** [comment]
@kotoshenya yeah you need to prepend (or append) the keyword to the link or the article won't trigger in most cases, if it's too ambiguous

**Comment by MariagraziaAlastra** [comment]
@kotoshenya Ok, this is ready to go. Merging! Any further improvements can be done in a different PR.

Thanks a lot, great job!

**Comment by kotoshenya** [comment]
@MariagraziaAlastra awesome! Thanks for all the help! :tada:

**Comment by kotoshenya** [comment]
@MariagraziaAlastra awesome! Thanks for all the help! :tada:

**Comment by MariagraziaAlastra** [comment]
@kotoshenya It's live!

[$.ajax()](https://duckduckgo.com/?q=%24.ajax()&t=ffab&ia=about)

screenshot-duckduckgo com 2016-08-18 23-03-14

Thanks again! :smile:

**Pull request merged**
