### PR TITLE
Perl 6 Documentation: Fix parse.pl so that it can handle the latest html structure.

### LINKED ISSUE #689: Perl 6 Documentation Bug: parse.pl fails in parsing code snippets
### Description
As you can see, some Perl 6 IA lack their code snippets:
https://duckduckgo.com/?q=perl6+Cool.chomp&t=h_&ia=about

Recently, the official documentation of Perl 6 changed its syntax highlighter.
See: https://github.com/perl6/doc/commits/12a65aa80ba13aedf17efbf16a83b49057f18748/highlights

I found that the above modification also changes the structure of html documents and it's cause of  this parsing failures:

+ 2016/7/20
Wed Jul 20

+ 2017/01/12
current

## Steps to recreate
Fix the parser so that it can handle the html of the latest Perl 6 documentation.

## People to notify

---

Instant Answer Page: https://duck.co/ia/view/perl6doc

### PR DESCRIPTION
**Pull request by titsuki**
## Description of new Instant Answer, or changes
I fixed the parse.pl so that it can handle the latest html structure.

+ Warnings
If you run the test using the following command: `duckpan test perl6doc`, it will show many warnings (i.e. `# 566 DISAMBIGUATION TITLES MISSING FROM ARTICLES:'` ), but I think it's because the original Perl 6 documentation still have a lot of undocumented things (e.g. `Numeric.match`,  `Rational.EVALFILE`).

+ HTML::TagParser
I used `HTML::TagParser` instead of the previous one. However I'm not sure where to add the  CPAN dependency.

## Related Issues and Discussions
Fix #689

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/perl6doc

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@titsuki this looks great, nicely done 👍 💯 

> If you run the test using the following command: duckpan test perl6doc, it will show many warnings (i.e. # 566 DISAMBIGUATION TITLES MISSING FROM ARTICLES:' ), but I think it's because the original Perl 6 documentation still have a lot of undocumented things (e.g. Numeric.match, Rational.EVALFILE).

That's no problem 👍 

> HTML::TagParser
> I used HTML::TagParser instead of the previous one. However I'm not sure where to add the CPAN dependency.

You can mention it in the README, or if you really want, you can create a cpanfile so it can be installed via [carton](https://metacpan.org/pod/Carton). The MDN CSS Fathead is an example 👍

**Comment by moollaza** [comment]
@titsuki Thanks! This LGTM :+1:

**Comment by titsuki** [comment]
Thanks for reviewing !

**Pull request merged**
