### PR TITLE
Improving MDN Javascript Fathead

### PR DESCRIPTION
**Pull request by bfmags**
Make MDN JS perform faster with Wget
https://duck.co/ia/view/mdnjs

- [ ] MDN JavaScript: update parser to use Wget results https://github.com/duckduckgo/zeroclickinfo-fathead/issues/257
- [x] MDN JavaScript: use Wget to fetch data https://github.com/duckduckgo/zeroclickinfo-fathead/issues/256

----------------------------------
IA Page: https://duck.co/ia/view/mdnjs
Forum topic: [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This pull request is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

### CODE REVIEW

**Comment by daxtheduck** [comment]
@bfmags Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please head to https://quackslack.herokuapp.com/ to get an invite.

>More Info: http://docs.duckduckhack.com/submitting/submitting-overview.html

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
Thanks @bfmags!

Copied from my comment on issue #256:

>I tried it and it gives me this error: 
><pre>fetch.sh: 23: fetch.sh: Syntax error: "(" unexpected (expecting "}")</pre>

>Looks like it's [this line](https://github.com/bfmags/zeroclickinfo-fathead/blob/bfmags/mdnjs/lib/fathead/mdnjs/fetch.sh#L23)

**Comment by MariagraziaAlastra** [comment]
So, as suggested by @bfmags, bash fetch.sh works!
Unlike the previous script, it takes just a couple seconds to download the articles - way faster than before.

Thanks @bfmags and let me know how I can help you with the parser as well!

**Comment by MariagraziaAlastra** [comment]
@bfmags I just tested this on beta, and it triggers even more than the current Fathead! 
For instance, the weird issue with the query [js boolean](https://beta.duckduckgo.com/?q=js+boolean&ia=about) is solved! :fireworks: 

Before merging this, though, there's a content issue that should be addressed: look at the output for "js date" [on beta](https://beta.duckduckgo.com/?q=js+date&ia=about) vs [in production](https://duckduckgo.com/?q=js+date&t=ffab&ia=about).
As you can see, the one on beta misses the example, and I noticed that's the case for a good amount of other queries. 
Could you include the first example from the MDN article in the abstract?

Thanks, you're doing great! :smile:

**Comment by MariagraziaAlastra** [comment]
@bfmags Awesome, thanks! I'm going to have this installed on beta again so it can be tested properly. If this works I want to merge and release it right away :smile:

**Comment by bfmags** [comment]
Thanks Maria 😄

**Comment by MariagraziaAlastra** [comment]
A little summary of where we stand: this PR was installed on beta but the results didn't change (aka still examples missing).
They were also missing in the output.txt file on my machine, but after deleting and cloning again the repo (and fetching and parsing again, too) I got the correct results. 
So the code seems to work, we just have some issue with overwriting the existing files, it seems.

In the meantime @bfmags is tweaking the fetcher to make sure all articles get fully downloaded, and adding a line to the parser to delete the cachejournal.

We'll have to figure out how to update the results correctly on beta too tomorrow, and then we can run more tests!

**Comment by moollaza** [comment]
@bfmags thanks for the updates! I believe I've deployed the changes, however it may not have been successful. I'm still investigating!

**Comment by moollaza** [comment]
@bfmags @MariagraziaAlastra I believe I figured out the problem with Crypto v crypto.

You have both an Article and a Redirect with the same name. I think `crypto` is technically setup as a disambiguation which links to `Crypto`, the same goes for history and document.

I'm still not sure if the backend is case-sensitive, but judging by the Database content which is all lowercased, I assume not. I think the solution is to avoid having any identical article, disambiguation, and redirect titles.

**Comment by moollaza** [comment]
I also just noticed that for `crypto` not only do you have a disambiguation, but you also have a redirect.

This is definitely a problem  too. We can't have more than one entry with the same title.

```
crypto	D								*[[Crypto]] The Crypto interface represents basic cryptography features available in the current context.\n*[[Window.crypto]] The Window.			
api crypto	R	Crypto										
crypto	R	Window.crypto										
window crypto	R	Window.crypto										
```

**Comment by moollaza** [comment]
..and unfortunately it looks like `mdn document` still doesn't work. I suspect it's because the article titles aren't allowed to be case sensitive.

**Comment by moollaza** [comment]
@bfmags @MariagraziaAlastra after a little more digging I found something interesting. It looks like Case Sensitivity isn't the problem! Or at least possibly not...

It looks like the database does actually return a result for `mdn document`: https://beta.duckduckgo.com/?q=mdn+document&t=hc&format=json

However, it's a disambiguation with only 1 Related Topic -- so that may be the real issue.

It looks like [sourcebuffer](https://beta.duckduckgo.com/?q=mdn+sourcebuffer&t=hc&format=json) is nearly identical to `document` (lowercase with a disambugation to different casing) however it returns a disambiguation with **two** results from the API, and in turn it works as expected:

https://beta.duckduckgo.com/?q=sourcebuffer&t=hc&ia=meanings&iai=%2F92%2FSourceBuffer

---

Internally @bfmags @MariagraziaAlastra we use the DDG API to grab the result so whatever comes out of the API is should appear on the SERP

**Comment by moollaza** [comment]
This one is even weirder! https://beta.duckduckgo.com/?q=mdn+focusevent&t=hc&ia=meanings

It looks like "focusevent" produces a disambiguation for `FocusEvent` and `FocusEvent()` and both `mdn FocusEvent` and `mdn FocusEvent()` produce unique results...

**Comment by bfmags** [comment]
@moollaza @MariagraziaAlastra I see where the issue is for "focusevent", it's creating 2 different articles corresponding to 2 urls in sitemap.xml, one for the interface and other for constructor

https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent
https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/FocusEvent

**Comment by moollaza** [comment]
@bfmags can you generate the output.txt and add it to this PR?

There are still clearly some minor bugs, but it's unclear to me if these are internal or results of the parser's output. 

Regardless, the majority of this IA is working as expected and we don't need to prevent this from moving forward because of those case-sensitive articles.

Let's get this merged!

**Comment by moollaza** [comment]
@bfmags thanks for the updates!

This is now live on Beta.

`mdn document` now works 👍 

https://beta.duckduckgo.com/?q=mdn+document&t=hd&ia=about

**Comment by moollaza** [comment]
@bfmags I've confirmed that Fatheads can definitely be case sensitive. An example of this is covered in our API documentation.

Can you remove the forced lowercasing again?

You can see that [blackberry](https://duckduckgo.com?q=blackberry) and [BlackBerry](https://duckduckgo.com?q=BlackBerry) produce different results, where the lowercased version shows a dismbiguation, but the TitleCased spelling displays an article 👍

**Comment by bfmags** [comment]
@moollaza Done

Removed the forced lowercasing https://github.com/bfmags/zeroclickinfo-fathead/commit/c3e8596a86337983053f4408fdf35ef7f8ac0f49

Had to make some tweaks to not end up with article and redirect for same keyword -> can you please test ?

**Pull request merged**
