### PR TITLE
C: New C Fathead

### PR DESCRIPTION
**Pull request by shreelock**
## Description of new Instant Answer, or changes
Generating a Fathead for Instant Answers related to C Programming Language
https://duck.co/ia/view/c_reference

## Related Issues and Discussions
The plan is to complete #717 

## People to notify
@pjhampton @rasikapohankar : This is the first draft of `output.txt` for the **C Reference Fathead** which I am currently working on, please have a look at it. If you like, feel free to suggest any changes in the other scripts as well. I am currently trying to test it via `duckpan` in _Codio._

**PS**: There is still work left for generating other fields of the fathead **_and_** with respect to code readability and  formatting. _(I don't write ugly code)_ 😅

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/c_reference

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by shreelock** [comment]
@rasikapohankar Yes, I am working on text clean up for non ascii characters, and will also add formatting to these subheadings. Also, redirects file wasn't added last time, I'll add support for that next.

**Comment by pjhampton** [comment]
Hey @shreelock!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Comment by shreelock** [comment]
@pjhampton Will DDG be open to take up this task at a later stage in time?
I started my college, so had gotten busy and couldn't finish it; but this is a good feature I think duckduckgo should have; and I would really love to see this being used in production.

**Comment by pjhampton** [comment]
Hey @shreelock, 

That's understandable! I hope college is going well.
It's not clear what the next version of DDH will look like, but when nwe IAs are accepted again I would endorse this feature 👍

**Pull request closed without merging**
