### PR TITLE
Fixes #598: Increase number of pypi packages from pypi-rankings to 15,000

### LINKED ISSUE #598: PyPi: increase the number of packages we cover
## Description

We limited PyPi to only the top 10000 packages in #533 to try to improve the relevancy of the results. It looks good so far and so I'd like to bump it up to 15000 and see how that looks. 

## What to do
Increase this limit to the appropriate number. 
https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/py_pi/parse.py#L15

------
IA Page:  http://duck.co/ia/view/py_pi 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ezgraphs

### PR DESCRIPTION
**Pull request by danidee10**
## Description of new Instant Answer, or changes
Increases the number of pypi packages from [pypi-rankings](http://pypi-ranking.info/) from 10,000 to 15,000

## Related Issues and Discussions
Fixes #598 

## People to notify
@moollaza @jdorweiler @tagawa 

---

Instant Answer Page: https://duck.co/ia/view/py_pi

### CODE REVIEW

**Comment by daxtheduck** [comment]
@danidee10 Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
This looks great! 😍 
Thanks for your contribution @danidee10 

Merge when ready @duckduckgo/community-leaders

**Comment by gautamkrishnar** [comment]
Is it okay to merge @pjhampton ?

**Comment by pjhampton** [comment]
Yep, @gautamkrishnar. Merge when ready 👍

**Comment by danidee10** [comment]
Just checking in, hope my PR hasn't been forgotten :smiley:

**Comment by danidee10** [comment]
Thanks for merging, looking forward to more contributions.

**Comment by gautamkrishnar** [comment]
Good Job @danidee10 😄 ❤️

**Pull request merged**
