### PR TITLE
Nginx: Add IA for nginx confuguration directives

### PR DESCRIPTION
**Pull request by pfirsichbluete**
**What does your Instant Answer do?**

The IA adds nginx configuration directives.

**What problem does your Instant Answer solve (Why is it better than organic links)?**

It shows the authorative answer right on the first page without need
for clicking. Also the “More at” takes you to the relevant anchor
directly.

**What is the data source for your Instant Answer? (Provide a link if possible)**

The mercurial repository at

  http://hg.nginx.org/nginx.org

**Why did you choose this data source?**

The alternatives would be to parse the nginx html documentation, or
fetch the xml sources from somewhere else.

Parsing the nginx html documentation seemed rather fragile, as html
changes from time to time. And each time the nginx html documentation
updates, one would have to also update the scripts to parse
them. That'd only be tech debt from the start.

Fetching the nginx documentation's xml sources from somewhere else
would be possible. But their trac forbids fetching through robots.txt,
and fetching through the repo's http pages at
http://hg.nginx.org/nginx.org/raw-file/default/xml/en/docs/http
turned out to be twice as slow as cloning the whole repo.

Hence, I chose to clone the whole repo, as the repo is small anyways.

**Are there any other alternative (better) data sources?**

I am not aware of any.

**What are some example queries that trigger this Instant Answer?**

nginx access_log
nginx fastcgi_connect_timeout
nginx fastcgi_ignore_client_abort

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**

Server administrators, Devops

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**

Yes.

https://duck.co/ideas/idea/4795/nginx-instant-answers

**Which existing Instant Answers will this one supercede/overlap with?**

I am not aware of any.

**Are you having any problems? Do you need our help with anything?**

The docs say to not include output.txt >=1MB.
This IA's current output.txt is 100KB, hence I included it.

Also, I am having a hard time to test the output.txt, as duckpan does
not work with fatheads :-/

**Where did you hear about DuckDuckHack? (For first time contributors)**

I saw it on a friend's list of forked repos.

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**

duckpan does not allow to test fatheads :-(

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[] Wrote test file and added to t/ directory
^ not sure how to do that for fatheads
[X] Verified that Instant Answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[X] Verified that Instant Answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility
^ not sure how to do that given that duckpan does not support fatheads
    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by moollaza** [comment]
@pfirsichbluete thanks a lot for contributing, we really appreciate it! We'll be sure to review this shortly and give you some feedback!

**Comment by jdorweiler** [comment]
@pfirsichbluete Thanks!  This looks pretty good.  I'll put this up on a server to test shortly.

**Comment by jdorweiler** [comment]
@pfirsichbluete could you remove the `|` from some of the entries and could you replace the `<br>` in the code blocks with `\n`?

**Comment by jdorweiler** [comment]
Actually let's leave the `|`.
Here it is: https://ddh4.duckduckgo.com/?q=nginx+fastcgi_cache&ia=about

**Comment by pfirsichbluete** [comment]
It seems the links on the `server` disambiguation page came out wrong. Updating PR to  58c9767ce9286e5668450a0c4b98dac9889cd159 which tries to improve on that.

---------------------------

> could you replace the `<br>` in the code blocks with `\n`?

Also Done in 58c9767ce9286e5668450a0c4b98dac9889cd159.

(The "`<br>` in code blocks" approach originates from the perl6doc fathead. Hence, also opening pull requests for the [perl6doc](https://github.com/duckduckgo/duckduckgo-documentation/issues/210 ) and the [fathead documentation](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/121).)

**Comment by jdorweiler** [comment]
@pfirsichbluete what about putting the block quotes in a code block too?   That should make entries like this easier to read. 
selection_373
http://nginx.org/en/docs/http/ngx_http_dav_module.html#dav_access

**Comment by pfirsichbluete** [comment]
> what about putting the block quotes in a code block too?

Mhmm ... one is allowed to use more mark-up in fatheads? Awesome!
I've been bold and also put literals in plane `<code/>` tags.

Additionally:

* Stripped lists (as they are rather lengthy).
* Added rendering of link texts.
* Improved detection of first sentence.

Pull request updated.

**Comment by jdorweiler** [comment]
@pfirsichbluete looks much better :+1: 
The new data on here if you want to test it out. https://ddh4.duckduckgo.com/?q=nginx+dav+access&ia=about
selection_378

**Comment by jdorweiler** [comment]
In line `<code> ` looks nice! 
selection_379

**Comment by pfirsichbluete** [comment]
@jdorweiler Thanks for the update! Looks great.

I only noticed two things:

1. It seems [searches with “nginx” in the query](https://ddh4.duckduckgo.com/?q=nginx+add_after_body&ia=about) show the “Nginx” span in the title and the “More at Nginx.org” footer
icon_present
, while [searches without “nginx” in the query](https://ddh4.duckduckgo.com/?q=add_after_body&ia=about) show the same IA, but are missing the “Nginx” span in the title and the “More at Ngin.org” footer:
icon_missing
Is this an artifact of the test setup, or is this something I can tweak in code myself?

2. Also my second attempt at the disambiguation page for [server](https://ddh4.duckduckgo.com/?q=server+nginx&ia=meanings) did not work as expected. So I resorted now to a plain `[[...]]` without bells/whistles to spare us the experimenting.

Updated the Pull Request accordingly.

**Comment by jdorweiler** [comment]
@pfirsichbluete thanks for finding that.  It was just an artifiact of the test setup.  I fixed it so you should see the correct subtitle and moreAt link for all nginx results.  

What was wrong with the disambiguation?  There's a known bug with disambiguation tiles that only sometimes link to their corresponding result.  Is that what you saw?  Either way I'll check to see if there will be a fix for that sometime soon.

**Comment by pfirsichbluete** [comment]
> What was wrong with the disambiguation?

Sorry for being too vague.

Nginx uses the `server` directive twice.

* Once in the `core` module, and
* once `upstream` module.

To tell them apart, I called the `server` page of the `core` module: `core.server`, and the `server` page of the `upstream` module: `upstream.server`. To aid finding them, I added a disambiguation page for `server`.

For the first version that got deployed to the test instance, the relevant part of the `output.txt` was:

```
upstream.server A [...]
core.server     A [...]
server          D [...] *[[core.server|server (core)]] sets configuration for a virtual server.\n*[[upstream.server|server (upstream)]] defines [...]
```

Using the standard syntax of `[[link target|link text]]`.

Searching for `nginx server` showed the disambiguation page. But clicking on the first item resulted in a query for `server (core)`. So a query for the `link text` (instead of a forward to the `link target`).

So instead of the standard Wiki syntax for links, the above behaviour on the test instance suggested a syntax of `[[link text|query string]]`. Hence, for the second version that got deployed to the test instance, the relevant part of the `output.txt` was:

```
upstream.server A [...]
core.server     A [...]
server          D [...] [[server (Nginx, core)|nginx core.server]] sets configuration for a virtual server.\n*[[server (Nginx, upstream)|nginx upstream.server]] defines [...]
```

(which uses the above suggested syntax). But now the `server` disambiguation page interpreted the links as [[<ignored>|link text and link target]].

To end this confusion, the new Pull Request just uses `[[link target]]` syntax and that's it. No nice name, no nothing.

```
upstream.server A [...]
core.server     A [...]
server          D [...] [[core.server]] sets configuration for a virtual server.\n*[[upstream.server]] defines [...]
```

That does not provide for the nicest possible disambiguation page, but at least the disambiguation page should be working ... hopefully :-D

**Comment by jdorweiler** [comment]
@pfirsichbluete Whoa cool.  The disambiguation tile links work. :cake: 

This looks great though.  I'll have to put the most recent data on a test instance and the we'll get some design feed back.

**Comment by jdorweiler** [comment]
Newest data is on ddh4: https://ddh4.duckduckgo.com/?q=nginx+gzip+static&ia=about
Here are a few screen shots
selection_386
selection_385

Passing to @abeyang to for design sign off

**Comment by abeyang** [comment]
Looks good! :+1:

**Comment by jdorweiler** [comment]
@pfirsichbluete looks great, thanks! 
I'll ping you when it's live.

**Comment by jdorweiler** [comment]
@pfirsichbluete It's live!
https://duckduckgo.com/?q=nginx+dav+access&ia=about

**Comment by pfirsichbluete** [comment]
@jdorweiler Awesome! Thanks.

**Pull request merged**
