### PR TITLE
jQuery: Create separate category pages depending on an article's master category

### LINKED ISSUE #517: jQuery: Create separate category pages depending on an articles master category
### Description
Use different categories pages depending on the article's master category: right now all the articles are under "jquery methods" but it might be more useful to divide them and have, e.g, a "CSS" category page, as well as "Attributes", "Core", "Data"...

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/jquery

### PR DESCRIPTION
**Pull request by rafaelpadovezi**
## Description of new Instant Answer, or changes
Use different categories pages depending on the article's master category: right now all the articles are under "jquery methods" but it might be more useful to divide them and have, e.g, a "CSS" category page, as well as "Attributes", "Core", "Data"...

## Related Issues and Discussions
Fixes #517 
jQuery: Create separate category pages depending on an articles master category

## People to notify
@MariagraziaAlastra 

---

Instant Answer Page: https://duck.co/ia/view/jquery

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by bfmags** [comment]
Thanks @rafaelpadovezi we'll deploy this to beta to get tested 👍

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi @bfmags it's on beta! Thanks 😄

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra The beta is still with the old categories.
image

**Comment by MariagraziaAlastra** [comment]
Hey @rafaelpadovezi, sorry, there must have been something going on while we were testing autodeploying to beta.
Can you remove the output, commit and push, and then add it again? That should cause beta to autodeploy the changes now :smile: 
Generally any time the output changes, your PR will be deployed there automatically

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra It worked! I will test later. But I can see that categories like Manipulation doesn't work very well ([](https://beta.duckduckgo.com/56/c/Manipulation?ia=iatesting)).
Should I add an identifier for each Category like "jQuery Manipulation"?

**Comment by bfmags** [comment]
@rafaelpadovezi Thanks! 👍 

Manipulation category seems to be working well 
https://beta.duckduckgo.com/?q=jquery+after&ia=about

screen shot 2016-12-05 at 17 28 57

**Comment by MariagraziaAlastra** [comment]
Hey @rafaelpadovezi! I was testing on beta and noticed when the articles have just one category, clicking on it then shows the list correctly: https://beta.duckduckgo.com/56/c/Callbacks_Object?ia=list

So I'm wondering if there's any way to select just one of those categories for each article, the most important one? Maybe the first would work?
Thanks!

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra It seems that the first category can be used as most important. But I don't think that just one category will solve this. For example, [jquery next](https://beta.duckduckgo.com/?q=jquery+next&ia=about) has 2 categories: [Traversing](https://beta.duckduckgo.com/56/c/Traversing?ia=iatesting) and [Tree Traversal](https://beta.duckduckgo.com/56/c/Tree_Traversal?ia=list). The former, doesn't show the list correctly and the latter does show correctly.

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi sorry I just edited my comment after further investigation.

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra  The output.txt doesn't contain the "". The encoding of the output.txt is utf-8. Later I will try another commit, with only one category.

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi No no, a `"\"`, not an empty string.

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra The `"\"` at the end of each category is because the escaped new line.
The category at the output.txt is `Attributes\\nManipulation\\nClass Attribute\\nCss`
image

**Comment by moollaza** [comment]
@rafaelpadovezi @MariagraziaAlastra I think that is a typo in the documentation the categories probably need to be separated by a `\n`, not `\\n` -- I will update the docs 👍 

i.e. `Attributes\nManipulation\nClass Attribute\nCss`

/cc @jdorweiler I think that's why Ruby still only shows one category for each result

**Comment by rafaelpadovezi** [comment]
@MariagraziaAlastra I tried just one category, but the problem still occurs. Maybe the problem are the categories with ambiguous names, like `Manipulation`, `Attributes`. If so, a solution is to put a "jQuery" before each category, like `jQuery Attributes`, `jQuery Manipulaion`, etc. This solution is now on beta.

**Comment by MariagraziaAlastra** [comment]
@rafaelpadovezi Looking good so far, thanks! 
Can you either solve the conflicts with master or just remove the output file? And then we can merge 👍

**Pull request merged**
