### PR TITLE
Spring Framework: Add Redirects

### LINKED ISSUE #789: Spring Suggestion: Add Redirects (Split Casing)
## Description

Spring is currently the most queried Java Web Framework work on DuckDuckGo, but this IA is under-triggering. I suspect because of the long class / method names and the fact the triggering doesn't reflect how a user queries. I think it would be good to experiment breaking up the camel / pascal / snake case with a regex and generating the redirects. 

**Triggering**

triggered

**Not Triggering**

nottriggered

An example of this in action is: https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/angularjs/output.txt#L1 where R is the redirect.

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) ping @pjhampton

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/spring_framework

### PR DESCRIPTION
**Pull request by BillyBarbaro**
## Description of new Instant Answer, or changes

Modified the parse script to add in a redirect entry by splitting each class on the capital letters.  The one exception to this is in classes containing SQL which is just treated as a word.  Also converted some of the method names from camelCase to snake_case in accordance with PEP8.

## Related Issues and Discussions

Fixes #789.  

## People to notify

@mandekisd 
@pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/spring_framework

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by BillyBarbaro** [comment]
This fathead has a few duplicate entries for classes with the same name from different packages.  Don't know if this is the reason I have been able to see my redirects on beta.  Should I try and fix these here or does that belong on its own issue?

**Comment by pjhampton** [comment]
Hey @BillyBarbaro! Yes, please fix them here 😄

**Comment by BillyBarbaro** [comment]
@pjhampton I went ahead and added disambiguations to remove the duplicate entries.   I've having the same issue I ran into with the iText PR where the contents of my output.txt don't seem to end up on beta.  (For instance, AbstractHandlerExceptionResolver should return a disambiguation page).  I've looked around trying to find invalid entires but had no luck.  Any suggestions for this one?

**Comment by pjhampton** [comment]
Hey @BillyBarbaro!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work. 

PS: Sorry for missing your message! 😞

**Pull request closed without merging**
