### PR TITLE
New Instant Answer: Apple Docs watchOS Fathead

### PR DESCRIPTION
**Pull request by souravbadami**
A new Fathead for the Apple watchOS, similar to our iOS, macOS and tvOS Fatheads

----

- IA Page: https://duck.co/ia/view/apple_docs_watchos
- [Forum Link](https://forum.duckduckhack.com/t/create-a-fathead-that-shows-watchos-apis/935)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@souravbadami Thanks! This LGTM :+1:

This is live on beta: https://beta.duckduckgo.com/?q=CLKComplicationServer+reloadTimelineForComplication&t=ho&ia=about

**Comment by moollaza** [comment]
@souravbadami can you update this to also use the new Fathead template elements?

https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract

**Comment by moollaza** [comment]
After that this will be good for merge 👍

**Comment by souravbadami** [comment]
@moollaza -- Thanks! I'll update this according to the new template.

**Comment by souravbadami** [comment]
@moollaza -- I've pushed the changes. PTAL.

**Comment by moollaza** [comment]
@souravbadami Thanks! This LGTM :+1:

https://beta.duckduckgo.com/?q=CLKComplicationServer+reloadTimelineForComplication&t=ho&ia=about

**Comment by daxtheduck** [comment]
@souravbadami this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
