### PR TITLE
Minimal working version of CountryData

### PR DESCRIPTION
**Pull request by rohit-gupta**
**What does your Instant Answer do?**
At present it gives results for queries about any country's gdp, if this is accepted, the further steps would include inclusion of more economic and demographic data.

**What problem does your Instant Answer solve (Why is it better than organic links)?**
It quickly pulls in economic and demographic data from an authoritative source. Organic links can often contain results from low quality sources and are inconvenient to navigate.

**What is the data source for your Instant Answer? (Provide a link if possible)**
http://data.worldbank.org

**Why did you choose this data source?**
While other sources like IMF, CIA World Fact Book, etc exist, worldbank data was chosed is easier to use as it (provides .csv files directly), and is the primary source for the relevant data. (UN uses their results as well)

**Are there any other alternative (better) data sources?**
See Above.

**What are some example queries that trigger this Instant Answer?**
india gdp, united states gdp

**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, etc)**
Its a general reference source, but should be particularly useful for journalists, economists and students

**Is this Instant Answer connected to a DuckDuckHack [Instant Answer idea](https://duck.co/ideas)?**
https://duck.co/ideas/idea/4643/country-facts-especially-population

**Which existing Instant Answers will this one supercede/overlap with?**
None that I am aware of.

**Are you having any problems? Do you need our help with anything?**
I can only locally test my parse.py and fetch.sh files. Would be great if the whole thing could be tested.

**Where did you hear about DuckDuckHack? (For first time contributors)**

**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Saw a link somewhere, probably reddit

A lot of this doesn't seem relevant to fatheads:

## Checklist
Please place an 'X' where appropriate.

```
[X] Added metadata and attribution information
[] Wrote test file and added to t/ directory
[] Verified that Instant Answer adheres to design guidelines (https://duck.co/duckduckhack/design_styleguide)
[] Verified that Instant Answer adheres to code styleguide (https://duck.co/duckduckhack/code_styleguide)
[] Tested cross-browser compatibility
    Please let us know which browsers/devices you've tested on:
    - Windows 8
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 10

    - Windows 7
        [] Google Chrome
        [] Firefox
        [] Opera
        [] IE 8
        [] IE 9
        [] IE 10

    - Windows XP
        [] IE 7
        [] IE 8

    - Mac OSX
        [] Google Chrome
        [] Firefox
        [] Opera
        [] Safari

    - iOS (iPhone)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - iOS (iPad)
        [] Safari Mobile
        [] Google Chrome
        [] Opera

    - Android
        [] Firefox
        [] Native Browser
        [] Google Chrome
        [] Opera
```

### CODE REVIEW

**Comment by MrChrisW** [comment]
Hi @rohit-gupta, thanks for your contribution! 

After reviewing I think this may be better suited as a [Spice](https://duck.co/duckduckhack/spice_overview) rather then a Flathead as then we can continue to provide updated information or even different years depending on the query. 

We already have a few Spices using the `api.worldbank.org` endpoint 

+ [Population](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Population.pm)
+ [Rainfall](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Rainfall.pm)

Let me know if you have any questions :smile:

**Comment by rohit-gupta** [comment]
Oh, well I only spent a few hours on this, should have read the documentation better. I had a couple of concerns about Spice though:

* Is it possible to do some basic cleaning on the data with Spice ? Like for instance giving the latest available gdp (say 2012) if its not available for 2015

* Also Spice seems to be triggered by fixed keywords, is it possible to alias something like "How many people live in X ?" or "What is the number of people in X" to population, for instance ? 

 I don't have any experience with perl, so I will take a look at the existing worldbank data based Spices for help, thanks for pointing me that way !

**Comment by MrChrisW** [comment]
@rohit-gupta Definitely don't want your hard work to go to waste!

>Is it possible to do some basic cleaning on the data with Spice ? Like for instance giving the latest available gdp (say 2012) if its not available for 2015

Sure, you could specify the [years](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Rainfall.pm#L48) that have data manually or check the response from the API and call a Spice.fail() if there's no data returned for the year searched. 

>Also Spice seems to be triggered by fixed keywords, is it possible to alias something like "How many people live in X ?" or "What is the number of people in X" to population, for instance ? 

Sure, take a look at the [triggers documentation](https://duck.co/duckduckhack/spice_triggers) you could do something like `triggers any => "number of people", "how many people live";` then remove unused words and triggers in the `handle` function and extract the country. 

>I don't have any experience with perl, so I will take a look at the existing worldbank data based Spices for help, thanks for pointing me that way !

No problem! Happy to help out. There's some great documentation on duck.co https://duck.co/duckduckhack/spice_overview

I've also noticed there's a pending pull request that provides the "gdp" Instant Answer using data from worldbank also, you can check it out here https://github.com/duckduckgo/zeroclickinfo-spice/pull/1285

I think the queries you suggested are great and should be added to the existing Population IA! 

+ "what is the number of people in"
+ "how many people live in"

Thanks

**Comment by moollaza** [comment]
@rohit-gupta @MrChrisW closing this.

It should really be a Spice, and after the launch of the recent Quandle IA, a new WorldBank IA, which covers all there data is coming soon, which will cover this AI (and some others like the Population Spice).

@rohit-gupta Thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit more Instant Answers!

**Pull request closed without merging**
