### PR TITLE
Java: added coverage for Fathead and some minor fixes for errors I experienced

### LINKED ISSUE #490: Java: Update parser to create output.txt articles for class methods
### Description
Add coverage for class methods so we have answers for things like `decimalstyle equals`. 

https://docs.oracle.com/javase/8/docs/api/index.html?java/time/format/DecimalStyle.html

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/java

### PR DESCRIPTION
**Pull request by aegis2501**
## Description of new Instant Answer, or changes

Adds coverage for Java methods. Also fixes a TypeError I got when saving class data to output.txt as well as in getcontent(), where I would eventually run into a UnicodeDecodeError. Both fixes just involve adding binary mode in file() for both functions.

## Related Issues and Discussions

Fixes #490 

## People to notify
@moollaza @marti1125 

## Testing & Review
To be completed by Language Leader (or DDG Staff)

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/java

### CODE REVIEW

**Comment by daxtheduck** [comment]
@aegis2501 Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@aegis2501 I think the wording in the issue may have been a bit misleading. The issue was meant to suggest that we need to add the methods to our output.txt -- your changes add these to the `cover/` directory, which is good because now we can use the `methods.txt` file to check for the existence of the methods in our output (like a unit test).

@aegis2501 can you also update the parser to create articles for all the methods in the `output.txt` -- that will allow us to actually show Instant Answers when the names of those methods are searched 👍

**Comment by aegis2501** [comment]
Ok cool. I'll work on it. Thanks for the feedback!

**Comment by aegis2501** [comment]
@moollaza does this work?

**Comment by moollaza** [comment]
@aegis2501 looks like some of these are more than 1 line? each entry should only be 1 line and should match an entry we have (or expect to have) in the `output.txt`

**Comment by moollaza** [comment]
@aegis2501 also, can we alpha-sort the list? That should help make it a bit easier to read/check

**Comment by aegis2501** [comment]
@moollaza do you mean sorting the coverage data?

**Comment by moollaza** [comment]
> @moollaza do you mean sorting the coverage data?

Yup!

> To be honest I'm not sure the methods.txt file is a meaningful check...

What do you mean by this?

@aegis2501 I think there is still some confusion about how the methods.txt file will be used. Every line in the methods.txt file (or any file in the `/cover` directory) should match the title (first column) of a line in the `output.txt` file.

The output.txt is generated, and as changes are made to the docs and code, we have no way of knowing if we're losing coverage. We also have no way of knowing if the output.txt contains everything we expect it to.

To solve this, we decided to have a `cover/` dir with files listing all the article titles we expect to see in our output.txt file. So, each line of `methods.txt` should match an article title (i.e. a unique query) we expect to trigger the Java Fathead.

Right now, the methods.txt file lists the input parameters for most methods. We don't expect anyone to search things like `write(byte[] b,int off,int len)` or `java write(byte[] b,int off,int len)`.

However, we might expect them to search, `java write()`, `java write` or `java write method`. So our output should contain an article (type 'A') for "write()", and we can have a redirect from `write` to `write()`.

By including a cover dir with a file named `methods.txt`. which has `write()`, we can ensure that our output.txt contains an article with a title of `write()` and we'll automatically generate a redirect entry for `write() method`  to `write`, if it doesn't already exist.

@aegis2501 does this help make sense of the methods.txt file, and how we'll be using it?

**Comment by aegis2501** [comment]
@moollaza yes! Thank you for the explanation.

**Comment by moollaza** [comment]
@aegis2501 this is looking better!

- Please remove the arguments inside the parentheses, we should just have `()`
- Please ensure there are no duplicates in the `methods.txt`

**Comment by moollaza** [comment]
@aegis2501 this is looking much better! Looks like we still need to strip out the duplicate names from `cover.txt` -- Can you also generate he new `output.txt` and push it here? Then it will be deployed to Beta 👍

**Comment by aegis2501** [comment]
@moollaza already on it! sorry that it's taking a while

**Comment by aegis2501** [comment]
@moollaza I've added the output.txt file as well. Is this ok?

**Comment by moollaza** [comment]
@aegis2501 looking better -- I noticed that not all the abstracts in output.txt are wrapped in a `<section>` though. Further, all of those lines (without `<section>` are missing 1 tab character so they're being tossed out by our parser.

Please fix that and then I'll be able to ensure it all installs to beta correctly 👍

**Comment by aegis2501** [comment]
@moollaza done!

**Comment by moollaza** [comment]
@aegis2501 thanks! I remove the output.txt and merged on a separate branch. Usually it closed the original PR, but I think because of the squashed commits that didn't work here.

Closing as this is now merged.

Excellent work! 💯 🚀  Thanks for doing an awesome job

**Pull request closed without merging**
