### PR TITLE
New Meteor API Fathead

### PR DESCRIPTION
**Pull request by mayank**
New Meteor API Fathead

## Description of new Instant Answer, or changes
Meteor API functions covered.

## Related Issues and Discussions
Issue #780 

## People to notify
@pjhampton 

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [x] Uniformly indented, well commented
- [x] Fetch.sh and Parse.sh run without errors
- [x] Output contains no blank lines, or multi-line entries
- [x] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/meteor_api

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Hey @mayank 

This is now live on beta 💙  💜  💛  ❤️

**Comment by mayank** [comment]
@pjhampton Seems working fine, some issue with docs link ... fixed now. :cake: 

image

**Comment by mayank** [comment]
@moollaza, @bfmags, @pjhampton any update?

**Comment by moollaza** [comment]
@mayank Thanks! This LGTM :+1:

**Comment by daxtheduck** [comment]
@mayank this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Comment by Lord-Lavios** [comment]
@mayank This fathead is currently missing examples and arguments. You should add that. 😄
For instance - [meteor wrapsync](https://beta.duckduckgo.com/?q=meteor+wrapasync&atb=v44-6&ia=about&iax=1) and [meteor startup](https://beta.duckduckgo.com/?q=meteor+startup&atb=v44-6&ia=about).

**Comment by mayank** [comment]
@Lord-Lavios For sure!

**Pull request merged**
