### PR TITLE
Fatheads: Add Travis.yml, run validate_fatheads.t for each PR

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes
- Add `.travis.yml` file
- Enables all Fatheads to be tested on each PR, similar to CheatSheets in Goodies repo

## People to notify
@jbarrett

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
This is now ready. Tests are failing because we have several issues in the Output.txt files!

**Comment by jbarrett** [comment]
I don't think we can release this with failing tests as it affects automated deployment - failing build won't get a deploy status ID, so we can't update PRs with deploy status (is this correct, @jdorweiler?)

**Comment by jdorweiler** [comment]
@jbarrett no it's okay. I forgot that I handled failing CI builds on beta.

**Comment by jbarrett** [comment]
@jdorweiler @moollaza Is there some way we can get the PR# or fathead ID in travis so we can just target the pushed fathead with this?

Thinking we also need to split up the tests so we can run a subset of them depending on which files are included in a PR.

**Comment by moollaza** [comment]
> Is there some way we can get the PR# or fathead ID in travis so we can just target the pushed fathead with this?

@jbarrett I think there may be a way to do that with a shell/perl script and git -- I considered if we would want the tests to run for all fatheads on each PR like we do for Goodies, or if we just wanted to test the modified IAs.

If all the existing Fatheads were in a passing state the current approach wouldn't be so bad...

**Comment by moollaza** [comment]
Closing this for now as it's not currently needed.

**Pull request closed without merging**
