### PR TITLE
ESLint Suggestion: Add Examples to Description (#822)

### LINKED ISSUE #822: ESLint Suggestion: Add Examples to Description
### Description

This is quite a popular IA, but the high Click Through Rate (66.7%) suggests that it's not helpful for those searching the command. I _think_ it might be because it doesn't have the examples listed:

screen shot 2017-02-23 at 7 38 00 pm

screen shot 2017-02-23 at 7 38 45 pm

I think we should scrape and include the examples to see if we can get the CTR down!

## People to notify

@zodiac403
@moollaza 
@pjhampton

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request
- [ ] 5) Ping @zodiac403 or @pjhampton

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/eslint

### PR DESCRIPTION
**Pull request by zodiac403**
## ESLint Suggestion: Add Examples to Description (#822)
- Parse **full documentation**
- Display **code example** and **summary text** for each article
- Add more **categories**

## Related Issues and Discussions
Fixes #822 for https://duck.co/ia/view/eslint

## People to notify
@moollaza
@pjhampton

## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [x] Title follows correct format (Specifies Instant Answer + Purpose)
- [x] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [x] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [x] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/eslint

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@zodiac403 this is looking great! Please add the new output.txt to the PR so we can test it on Beta 👍

**Comment by zodiac403** [comment]
@moollaza, you're quick ;)
I thought I added a note above, but obviously I forgot it: This PR is still **work in progress**. I just created it to show of how it's progressing. I'll let you know, when I am ready.

**Comment by zodiac403** [comment]
Found some time today to bring this further.

@moollaza, I ran **duckpan test eslint** for the current *output.txt* on Codio and it threw some errors.

~~~
# 3 POSSIBLY UNESCAPED CHARACTERS FOUND:
# Line 5     contains: /\x, ;\x, /\x, ;\x
# Line 73    contains:  \2,  \2,  \x
# Line 91    contains: ;\x, ;\3
~~~

All three come from `<code>` blocks in rules for escape chars in JavaScript. I checked the rendered output from **duckpan server eslint**. All three look fine.

Do I have to consider the failing test as a problem?

**Comment by zodiac403** [comment]
@bfmags @moollaza @pjhampton 

Hi folks,
just pushed the last commits today. From the code side, **this PR should be ready to review now**. As mentioned above, the new version should improve this:

- Parse full documentation
- Display code example and (more verbose) summary text for each article
- Add more categories

By now, I tested the following:

- **duckpan test** runs without errors
- **output.txt** does not contain unescaped HTML characters (we had a problem with this midways)
- **duckpan server** displays content + layout as expected

Any comments or feedback is welcome.

**Comment by zodiac403** [comment]
Hi @bfmags, @moollaza, @pjhampton,
just saw, this PR is still open. Anything left to do on my side?

**Comment by pjhampton** [comment]
Hey @zodiac403

Sorry for the delay in getting this reviewed. There was a major shift in direction from our side which seen us focusing on improving the existing IAs such as the Calculator, Unit Converter. I will put this on hold for now and hopefully we can come back to it in the future 💙  💛  ❤️  I really appreciate all your hard work with the programming mission.

**Comment by zodiac403** [comment]
Hi @pjhampton,
thanks for your feedback. Actually this PR should improve the existing IA: It fixes issue #822 by adding examples and additional descriptions.

&mdash; How much effort is it to review + merge the PR?

**Comment by pjhampton** [comment]
Hey @zodiac403!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
