### PR TITLE
Added MDN Classes and Statements Section

### PR DESCRIPTION
**Pull request by mbad0la**
Fixing #331 , #335 [WIP]
<hr>

IA Page: https://duck.co/ia/view/mdnjs
Forum Topic : [Improve MDN JavaScript Fathead](https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155)

This Pull Request is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [JavaScript related searches](https://forum.duckduckhack.com/t/javascript-search-overview/94)!

People to notify
@MariagraziaAlastra @moollaza

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by MariagraziaAlastra** [comment]
Hey @mbad0la thanks so much, it's on beta now!
See some examples:
- [js block](https://beta.duckduckgo.com/?q=js+block&t=h_&ia=about)
- [js break](https://beta.duckduckgo.com/?q=js+break&t=h_&ia=about)

Just a couple things:
- for articles using the triple period we should have redirects that replace them with spaces. E.g. [js if...else](https://beta.duckduckgo.com/?q=js+if...else&t=h_&ia=about) should also trigger for "js if else", "js if", "js else"

- sometimes there's an empty code snippet showing up (eg see [js for](https://beta.duckduckgo.com/?q=js+for&t=h_&ia=about))
screenshot-beta duckduckgo com 2016-09-12 12-11-19

**Comment by mbad0la** [comment]
@MariagraziaAlastra thanks for the review :smile: 
The empty code snippet is probably due to the IA template and it's rendering on different screens and content sizes. 
Any ideas on how to modify it?

**Comment by tagawa** [comment]
The empty snippet seems to be because the IA is not expanded. If you click on "Show More" it will appear properly. Seems like this could be a problem with the template itself rather than this IA.

**Comment by MariagraziaAlastra** [comment]
@mbad0la it's on beta again!
- [js if](https://beta.duckduckgo.com/?q=js+if&t=h_&ia=about)
- [js if else](https://beta.duckduckgo.com/?q=js+if&t=h_&ia=about)

Looking good so far. I'll test it more and I'll let you know. Thanks so much!

**Comment by MariagraziaAlastra** [comment]
@mbad0la can you please fix the merge conflicts? Thanks 😄

**Comment by mbad0la** [comment]
@MariagraziaAlastra I've rebased and fixed the conflicts. Please review and merge. 
Thanks! :)

**Comment by MariagraziaAlastra** [comment]
@mbad0la 
Hey, it's on beta again! Let me test it further to make sure there are no issues after the rebase and then I'll merge if it looks good :)

**Comment by MariagraziaAlastra** [comment]
Looking good, thanks! 👍

**Pull request merged**
