### PR TITLE
Python Requests: Extend Parser and Add Coverage

### LINKED ISSUE #729: Python Requests Suggestion: Extend Parser and Add Coverage
## Description

It seems that this Fathead (Python Requests) just isn't triggering based on the following stats:

- Bounce Rate: 100%
- Engagement Rate: 0% 

This is a shame because there is a lot of people searching for requests related stuff. For example:

```
python requests hypermedia 
python requests irc 
python requests jsonrpc 
python requests limit page size time 
python requests oauth2 
python requests proxies 
python requests proxy 
python requests read 
python requests response headers 
python requests result filepointer 
python requests show headers 
python requests socks proxy 
python requests status_code 
python requests test url 
python requests ThreadPoolExecutor 
python requests tls streaming exception 
python requests tls streaming exception RST 
python requests unsupported browsers check 
python requests urljoin 
python requests utf8 
python requests write response 
python requests x-form-url-encoded 
python requests.get 
```

Further, I have noticed that:

Triggers: `JSON Response Content`
Doesn't Trigger: `requests JSON Response Content`

I think it would be helpful if we:

1. Scaled the existing parser to cover the [API docs](http://docs.python-requests.org/en/master/api/)

2. Added [coverage data](https://docs.duckduckhack.com/programming-mission/creating-effective-fatheads.html)

## People to notify
@hchienjo (Maintainer)
@duckduckgo/duckduckhack-contributors 

## Get Started
- [ ] 1) Claim this issue by commenting below
- [ ] 2) Review our [Contributing Guide](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/CONTRIBUTING.md)
- [ ] 3) [Set up your development environment](https://docs.duckduckhack.com/welcome/setup-dev-environment.html), and fork this repository
- [ ] 4) Create a Pull Request

## Resources
- Join [DuckDuckHack Slack](https://quackslack.herokuapp.com/) to ask questions
- Join the [DuckDuckHack Forum](https://forum.duckduckhack.com/) to discuss project planning and Instant Answer metrics
- Read the [DuckDuckHack Documentation](https://docs.duckduckhack.com/) for technical help

---

Instant Answer Page: https://duck.co/ia/view/python_requests

### PR DESCRIPTION
**Pull request by hchienjo**
## Description of new Instant Answer, or changes

1. Improve parser so that more methods are tested.
2. Add coverage data so that the IA is testable.

## Related Issues and Discussions

Fixes #729 

## People to notify

@pjhampton 
## Testing & Review
To be completed by Language Leader (or DDG Staff) when reviewing Pull Request

**Pull Request**
- [ ] Title follows correct format (Specifies Instant Answer + Purpose)
- [ ] Description contains a valid Instant Answer Page Link (e.g. https://duck.co/ia/view/my_ia)

**Instant Answer Page** (for new Instant Answers)
- [ ] Instant Answer page is correctly filled out and contains:
    - One topic for the Search Space Language (Java, Python, Scala, Ruby, etc.)
    - One topic from: Reference, Help, Libraries, Tools
        - Documentation Fatheads are considered "Reference"
    - Description, Data source, and 2+ example queries
    - Perl Module (e.g. "DDG::Fathead::PerlDoc" -- we only need a name, not an actual file)
    - Source Name (for "More at <source_name>" link)
    - Source Domain (must contain http:// or https:// -- can be the same as Data Source)
    - Source Info (used as Subtitle for each Article -- usually matches the IA Name)
    - 'Skip Abstract' is checked off
    - Source ID (ping @moollaza to assign one, once Fathead is ready for Beta deploy)

**Code**
- [ ] Uniformly indented, well commented
- [ ] Fetch.sh and Parse.sh run without errors
- [ ] Output contains no blank lines, or multi-line entries
- [ ] Fathead Tests are passing (run `$ duckpan test <fathead_id>`)
    - Tester should report any failures

**Pull Request Review Guidelines**: https://docs.duckduckhack.com/programming-mission/pr-review.html

---

Instant Answer Page: https://duck.co/ia/view/python_requests

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by hchienjo** [comment]
@pjhampton will making trigger.txt improve the triggering?

**Comment by pjhampton** [comment]
@hchienjo I don't have any data right now, but I would assume it would :)

**Comment by pjhampton** [comment]
Hey @hchienjo!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
