### PR TITLE
iOS: Changed docset source to dash.

### PR DESCRIPTION
**Pull request by souravbadami**
## Type of Change

- [ ] New Instant Answer
- [x] Improvement
  - [ ] Bug fix
  - [x] Enhancement
- [ ] Non–Instant Answer
  - [ ] Other (Role, Template, Test, Documentation, etc.)
## Description of new Instant Answer, or changes

Changed docset source to dash.
## People to notify

@moollaza 

---

IA Page: https://duck.co/ia/view/apple_docs_ios

Forum Topic:

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@souravbadami looking at the results of this, the output.txt only contains ~7K lines, whereas the current version has about ~35K.

Can you investigate what the differences are? I'm not comfortable switching sources if we're going to have 5x less data!

**Comment by moollaza** [comment]
@souravbadami Ping! Would you be able to finish this one up? We'd love to get this live!

**Comment by souravbadami** [comment]
Hey @moollaza! -- The dash source seems to be old or something. I think, it's better the keep the existing one unless we find a new and stable source.

**Pull request closed without merging**
