### PR TITLE
New Apple Docs fathead

### PR DESCRIPTION
**Pull request by shanmbic**
Hey @moollaza !

This is the apple_docs fathead , as we discussed in #744  ! It contains the classes for each framework . 

Linked to - #718 
Documentation - https://developer.apple.com/reference
IA Page - I think it should be linked the the existing IA page for apple docs.

Also, for now , in output file, the title only contains the name of the symbol class "nsatstypesetter", should i also include the framework name like this "appkit nsatstypesetter" ?? 
Please review and suggest improvements. :)

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by pjhampton** [comment]
Hey @shanmbic! Is there an IA page for this?

**Comment by shanmbic** [comment]
Hey @pjhampton , I haven't created the IA page yet , since we are restructuring the apple_docs ( #744 ) , I guess this should be linked to the existing IA page for old apple_docs fathead. Or should I create a new one ?

**Comment by pjhampton** [comment]
That's cool, @shanmbic. Please use the existing one.

**Comment by pjhampton** [comment]
Hey @shanmbic!

[DuckDuckHack is now in Maintenance Mode](https://duckduckhack.com/) and from now on, we are only accepting issues and PRs for essential bugs and bug fixes.

Unfortunately, this is non-essential and will be closed.

We appreciate you taking the time to contribute and apologize for not being able to include your work.

**Pull request closed without merging**
