### PR TITLE
Fix #424: Dive Into Python - Switched to new fathead template.

### LINKED ISSUE #424: Dive Into Python: Switch to use new Fathead Template Elements
We now have [Fathead Template Elements](https://docs.duckduckhack.com/resources/fathead-overview.html#formatting-the-abstract) designed specifically for Programming Fatheads. These are HTML elements that should be added to the output.txt by each Programming Fathead's parsing script(s).

This Fathead should be updated to use the templates:

- The entire abstract should be wrapped in a `<div>` with class `prog__container`
- Any text before/after the code blocks must be wrapped in `<p>` tags
- Any subheadings should be wrapped in a `<div>` with class `prog__sub`

Here is an example:

```html
<div class="prog__container">
    <p>Creates a JavaScript Date instance that represents a single moment in time.</p>
    <pre>
        <code>
            new Date;
            new Date(value);
            new Date(dateString);
            new Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);
        </code>
    </pre>
    <span class="prog__sub">Return Value</span>
    <p>The removed element.</p>
</div>
```

---

This issue is part of the [Programming Mission](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53): help us improve the results for [Python related searches](https://forum.duckduckhack.com/t/python-search-overview)!
   

------
IA Page:  http://duck.co/ia/view/diveintopython 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jdorweiler

### PR DESCRIPTION
**Pull request by souravbadami**
Fixes #424 

---
IA Page: https://duck.co/ia/view/diveintopython

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@souravbadami I'm having some issues running the parser here.

First it looked like I needed to upgrade `pytidylib`, but after that I'm still seeing an error:

```
Traceback (most recent call last):
  File "parse.py", line 282, in <module>
    data = PythonData(file_path)
  File "parse.py", line 22, in __init__
    self.load_data()
  File "parse.py", line 32, in load_data
    document, errors = tidy_document(data_file.read())
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/tidy.py", line 221, in tidy_document
    return get_module_tidy().tidy_document(text, options)
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/tidy.py", line 233, in get_module_tidy
    _tidy = Tidy()
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/tidy.py", line 95, in __init__
    if self._tidy is None:
AttributeError: 'Tidy' object has no attribute '_tidy'
```

Could you investigate this? Were you able to run the parser recently?

**Comment by souravbadami** [comment]
@moollaza -- Could you try with **python3** ?

**Comment by moollaza** [comment]
> Could you try with python3 ?

@souravbadami I believe I did. Tried again with Python 3.5.2 and no luck.

I created a virtualenv, ran `pip install -r requirements.txt` and then ran parse.py:

```
Traceback (most recent call last):
  File "parse.py", line 7, in <module>
    from tidylib import tidy_document
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/__init__.py", line 68, in <module>
    raise OSError("Could not load libtidy using any of these names: %s" % (",".join(LIB_NAMES)))
OSError: Could not load libtidy using any of these names: libtidy,libtidy.so,libtidy-0.99.so.0,cygtidy-0-99-0,tidylib,libtidy.dylib,tidy
```

**Comment by moollaza** [comment]
After running `pip install pytidylib --upgrade` that error goes away, but I end up where I did before:

```
Traceback (most recent call last):
  File "parse.py", line 282, in <module>
    data = PythonData(file_path)
  File "parse.py", line 22, in __init__
    self.load_data()
  File "parse.py", line 32, in load_data
    document, errors = tidy_document(data_file.read())
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/tidy.py", line 221, in tidy_document
    return get_module_tidy().tidy_document(text, options)
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/tidy.py", line 233, in get_module_tidy
    _tidy = Tidy()
  File "/mnt/ebs/usr/local/ddh/zeroclickinfo-fathead/lib/fathead/diveintopython/venv/lib/python3.5/site-packages/tidylib/tidy.py", line 95, in __init__
    if self._tidy is None:
AttributeError: 'Tidy' object has no attribute '_tidy'
```

**Comment by moollaza** [comment]
@souravbadami I realized that I was missing the system package required by pytidylib!

Thanks! This LGTM :+1:

Live on beta: https://beta.duckduckgo.com/?q=dictionaries+in+a+boolean+context&ia=about

**Pull request merged**
