### PR TITLE
React API Docs: Broaden search results by adding more aliases (#597)

### LINKED ISSUE #597: React API Docs: Broaden search results by adding more aliases
### Description

The ReactJS Instant Answer currently only shows up for searches like [React.Component](https://duckduckgo.com/?q=React.Component&ia=about), but not for [react component](https://duckduckgo.com/?q=react+component&ia=software).

### What to do
For each line in the [articles.txt file](https://github.com/duckduckgo/zeroclickinfo-fathead/blob/master/lib/fathead/reactjs/articles.txt), create aliases and store them in a new redirects.txt file, in the same directory.

Each line of the redirects.txt file should be structured as follows: alias,original line.
E.g: `component,React.Component`

The aliases should have:
- The word "React" removed
- Symbols such as dots replaced with spaces
- Parentheses removed
- CamelCase words split into different words (eg "createClass" would become "create class")

This change will allow the Instant Answer to trigger for more searches.

------
IA Page:  http://duck.co/ia/view/reactjs

### PR DESCRIPTION
**Pull request by bfmags**
## Description of new Instant Answer, or changes
Add list of redirects to ReactJS

Fixes #597 

---

Instant Answer Page: https://duck.co/ia/view/reactjs

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by tagawa** [comment]
Thanks for the PR @bfmags. Apparently there's an internal issue that prevents this triggering on the `react` keyword, but a fix is in the pipeline. When that's released, it should be ready to review on the beta server: https://beta.duckduckgo.com/?q=React+Component&ia=about
/cc @jdorweiler

**Comment by tagawa** [comment]
In the meantime, this should work with the `reactjs` keyword, e.g. https://beta.duckduckgo.com/?q=Reactjs+Component&ia=about

**Comment by bfmags** [comment]
Seems to be working : https://beta.duckduckgo.com/?q=Reactjs+proptypes+array+of&ia=about&iax=1 😄 
I'll run more tests meanwhile

**Comment by moollaza** [comment]
@bfmags Thanks! This LGTM :+1:

**Comment by moollaza** [comment]
@bfmags should we updated parse.sh to execute this as well?

**Comment by MariagraziaAlastra** [comment]
No need to do that in this PR, the redirects will be added automatically when deploying the fathead from the txt file

**Pull request merged**
