### PR TITLE
jQuery: Added Coverage Data

### PR DESCRIPTION
**Pull request by moollaza**
## Description of new Instant Answer, or changes

Adds jQuery coverage data.

I collected this list from api.jquery.com, and after running the coverage tests, it looks like we're actually missing one article that exists in the docs!

## Related Issues and Discussions
Solves #518 

## People to notify
@pjhampton 

---

Instant Answer Page: https://duck.co/ia/view/jquery

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
Live here: https://docs.duckduckhack.com/v/a4ffd5f12672047241f904655e56d65efed91b7c/programming-mission/pr-review.html

LGTM 👍

**Comment by moollaza** [comment]
LGTM 👍

**Comment by MariagraziaAlastra** [comment]
@moollaza Actually it's not missing, you just have to update the output before running the test: https://duckduckgo.com/?q=jquery+deferred.catch()&bext=msl&atb=v32-1__&ia=about

**Pull request merged**
