### PR TITLE
New Spark Scala API Fathead

### LINKED ISSUE #643: Spark Scala Reference:  New Fathead
Reference Source: http://spark.apache.org/docs/latest/api/scala/index.html
------
IA Page:  http://duck.co/ia/view/spark_scala_reference 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Hasil-Sharma

### PR DESCRIPTION
**Pull request by Hasil-Sharma**
Fixed #643

IA Page: https://duck.co/ia/view/spark_scala_reference

### CODE REVIEW

**Comment by daxtheduck** [comment]
@Hasil-Sharma Thanks for the pull request! Unfortunately, we're only accepting contributions and improvements to a limited portion of the search space.
            
The staff and community are currently focused on making DuckDuckGo the [best search engine for programmers](https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53). To ensure we're making as much progress as possible, **we are only accepting Instant Answers and updates related to the programming mission**.
    
If this is not related to the Programming Mission, it will likely be closed but you can:
    
1. Help us prevent further confusion by telling us where you found out about DuckDuckHack or where we could've alerted you earlier.
2. Keep this code handy! We'll be expanding into other search topics in the future!
3. Join us at our new home: https://forum.duckduckhack.com/

If this is related to the Programming Mission, it will be reviewed by staff and the community as soon as possible!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by Hasil-Sharma** [comment]
fixes #643

**Comment by Hasil-Sharma** [comment]
Can somebody please help me here.

**Comment by bfmags** [comment]
Hi @Hasil-Sharma for reference you can use the [Fathead Docs](https://docs.duckduckhack.com/resources/fathead-overview.html)
The article titles should not contain the namespace eg.`org.apache.spark`, instead should be the page title the user will search for eg.`spark Accumulable` -> `Accumulable    A...`

**Comment by Hasil-Sharma** [comment]
Thanks @bfmags

**Comment by moollaza** [comment]
> The article titles should not contain the namespace eg.org.apache.spark, instead should be the page title the user will search for eg.(search:)spark Accumulable -> (output.txt entry)Accumulable

@Hasil-Sharma @bfmags I think it's best to have the namespace as the article title, and then create aliases (redirects) such as `spark accumulable` that show the result for the namespace.

This way we can cover both kinds of queries 👍

**Comment by moollaza** [comment]
@Hasil-Sharma this is now live on Beta: org.apache.spark.Accumulable

**Comment by moollaza** [comment]
@Hasil-Sharma I've filled out the IA page with more information so the `More at` URL will display correctly. I've also added a subtitle.

**Comment by moollaza** [comment]
@Hasil-Sharma Thanks! This LGTM :+1:

The next step is to start adding redirects and more trigger words, with a `trigger_words.txt` file 👍

**Comment by daxtheduck** [comment]
@Hasil-Sharma this is now merged! It should be live on DuckDuckGo within one week (or during the next release) and we'll be sure to notify you when it happens.

After your Instant Answer goes live for the World to use, you will be able to see [traffic information](http://docs.duckduckhack.com/maintaining/tools.html#monitor-your-instant-answer-page) about your IA as well as receive feedback directly from users. 
                
Please refer to the [maintenance guide and docs](http://docs.duckduckhack.com/maintaining/guidelines.html) to keep up with potential changes to your Instant Answer.
                
Thank you again for your help!

**Pull request merged**
